### ISSUE TITLE
Misc issues and other

### ISSUE THREAD

**Issue by FrKaram** [billziss-gh/winfsp#100]
Hi Bill,

Still working on my FS which is fully implemented but still presents some stability issues. So I need some advice :-)

I use WinFSP to mount a local drive which maps a remote server.
As such, I have to assume that the server could be unreachable at any time.
1\ How should I handle this, is there a status that I can return in the methods to tell the OS that the FS is not available ?

2\ I have an issue when deleting files.
I delete the file when the Cleanup method is called and CleanupDelete is set.
One of the file cannot be deleted so the call to the repository raise an exception that I catch.
As Cleanup does not expect a return value, I cannot notify the OS that the deletion failed.
After this deletion fails, I experience 2 behaviour :
- either WinFSP "freezes"
- or WinFSP enter an infinite loop of GetSecurityByName / Open / Close on the root element (see image)
![image](https://user-images.githubusercontent.com/8916606/29176072-2287ea50-7deb-11e7-9f18-67bba6610802.png)

I don't know how to handle that deletion failure correctly.

3\ The protocol I use between the PC and the server does not allow me to know in advance what are the permissions on the files when GetSecurityByName is called. I will know that I don't have enough permissions only when I will try to read / write the file. How should I handle that ?

Thanks !

**Comment by billziss-gh** [comment]
@FrKaram apologies for the late response. I am on vacation and do not check GitHub regularly.

> I use WinFSP to mount a local drive which maps a remote server.
As such, I have to assume that the server could be unreachable at any time.
1\ How should I handle this, is there a status that I can return in the methods to tell the OS that the FS is not available ?

There is no such status code to return. Your file system must be prepared to handle requests whether the server is reachable or not. It is acceptable to return errors if the server is not reachable. For example, it may be acceptable to return `STATUS_VIRTUAL_CIRCUIT_CLOSED` if a `Read` cannot be satisfied because of a timeout.

I have not researched what the appropriate status codes are in these cases. You may want to research the proper codes (and post the results here :) You may want to search for the word "network" in the [NTSTATUS Values](https://msdn.microsoft.com/en-us/library/cc704588.aspx) document. Another interesting document appears to be: https://msdn.microsoft.com/en-us/library/cc227077.aspx

> 2\ I have an issue when deleting files.
I delete the file when the Cleanup method is called and CleanupDelete is set.
One of the file cannot be deleted so the call to the repository raise an exception that I catch.
> ...
> I don't know how to handle that deletion failure correctly.

This is indeed a problem with `Cleanup`. There is no way to return failure from `IRP_MJ_CLEANUP`. This is a Windows limitation.

In general you should check if file deletion is possible during `CanDelete` and delete the file during `Cleanup`. Is it not possible to see if the repository will raise the exception during `CanDelete`?

I am not sure why you get the loop of `GetSecurityByName`, `Open`, `Close`. What app exhibits this behavior (Explorer, Command Prompt, etc.)? WinFsp will not retry calls like that on its own, so it must be a user app or another system component that causes this behavior.

> 3\ The protocol I use between the PC and the server does not allow me to know in advance what are the permissions on the files when GetSecurityByName is called. I will know that I don't have enough permissions only when I will try to read / write the file. How should I handle that ?

By changing the protocol? :)

Maybe one way around this is to always return full permissions, but then return `STATUS_ACCESS_DENIED` (or `STATUS_MEDIA_WRITE_PROTECTED`) when an I/O cannot be satisfied because of permission problems. It is not ideal but it does mirror what your protocol can do.

**Comment by FrKaram** [comment]
Hi Bill,

doesn't seems to me that you took time to respond, moreover if you're on vacation :-)

1\ I'll check the available return values

2\ The problem occur with the explorer ... Could it be because in CanDelete I return true while in fact the deletion fails ? Maybe the explorer is expecting a change in the file list ...
Can I try to delete the file in the CanDelete method instead of Cleanup ? Or can CanDelete be called even though finally no deletion will be requested afterwards ?

3\ I cannot change the protocol :-( I'll try with the return values you gave me

**Comment by FrKaram** [comment]
I found out that either the "proxy" object or the session linked to this proxy becomes corrupted after the failure of the deletion. As I use the same object for all methods, this was the reason for the infinite loop.
I now recreate a proxy for each call and do not encounter any issues anymore.

Please keep this issue open as I may have other questions. I'll close it myself when my implementation is complete.

**Comment by billziss-gh** [comment]
@FrKaram i am glad this got resolved.

**Comment by FrKaram** [comment]
Hi Bill,
FYI, I have released an alpha (barely) of the program I've been working with.
All that thanks to WinFSP and your support
Even though there are sill many things to be enhanced, it does work
https://github.com/FrKaram/KS2.Drive

**Comment by FrKaram** [comment]
Hi Bill,
is there a way to mount the drive as a "Network Drive" instead of a "HDD Drive" ?
Windows explorer is making a lot of requests on the drive and I think it does less lot requests when he knows that it is a network drive

**Comment by billziss-gh** [comment]
@FrKaram 

> FYI, I have released an alpha (barely) of the program I've been working on.

CONGRATULATIONS! I will check your project some time next week when finally back from vacation.

> is there a way to mount the drive as a "Network Drive" instead of a "HDD Drive" ?

Set a volume prefix using the `FileSystemHost.Prefix` property. I believe the syntax should be along the lines of `\server\share` (notice the single backslash at the beginning) to present the drive under `\\server\share`.

**Comment by billziss-gh** [comment]
I am now having a look at KS2.Drive. A few suggestions:

- Consider using 4096 for the sector size. I use 512 in MEMFS for testing purposes, but for most file systems 4096 is a better option.
- `CanDelete` should return `STATUS_DIRECTORY_NOT_EMPTY` if a directory has files. I think though you have mentioned previously that this was not possible (or cheap) during `CanDelete`.
- `SetSecurity` should probably return `STATUS_INVALID_DEVICE_REQUEST`.
- In some cases you return `-1` from some file system methods. You should always return a `STATUS_*` code. For exceptions you can return `STATUS_UNEXPECTED_IO_ERROR` which is what the default `ExceptionHandler` does (BTW, you can override this method).

**Comment by FrKaram** [comment]
Thanks Bill for those inputs. I'll definitelly have a close look at them.

Regarding STATUS_DIRECTORY_NOT_EMPTY. My remote system does allow deleting a folder even if it contains files so I guess I can also allow it in my filesystem, can't I ?

**Comment by billziss-gh** [comment]
You are the file system author, so you get to choose. OTOH these might be surprising semantics for some apps.

**Comment by FrKaram** [comment]
I still have upcoming questions but I don't no yet when I'll hae time to work on this subject.
I can close the thread and I'll open a new one in times.
