### ISSUE TITLE
FUSE: add flags (Windows file attributes) support

### ISSUE THREAD

**Issue by philrykoff** [billziss-gh/winfsp#114]
Is it possible with winfsp (fuse) to set a file as hidden and system?

The reason I am asking is that I would like to add a desktop.ini to the virtual drive, but that file is only being evaluated by windows, if it is a system file. In addition to that, hiding it from the user would be great.

https://superuser.com/questions/882442/self-created-desktop-ini-does-not-work

I searched your and libfuse API docs and although they are great, maybe I lack the experience to search for the right needle in the haystack.

**Comment by philrykoff** [comment]
I typically don't crosspost, but I just felt like the jnr-fuse issue board might be a better place for asking this, since I use jnr-fuse on top of winfsp (from my Java app). 

Yet, if winfsp might not support this, there is probably nothing jnr-fuse can do.

I'll post any insights gained over there here.

**Comment by billziss-gh** [comment]
WinFsp supports the hidden and system file attributes. However the FUSE API originated in Linux, which does not in general support those attributes (some BSD's and Apple's OSX do). So you cannot use FUSE and at the same time support those attributes.

The only thing that we could do is to consider adding an extension to FUSE to support those attributes.

**Comment by philrykoff** [comment]
Here is some info I found about `chflags`:

- Usage in osxfuse: https://github.com/osxfuse/fuse/blob/master/example/fusexmp_fh.c#L299-L426
- Apple man file: https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/chflags.1.html

Would you consider adding a comparable extension to the fuse layer of WinFSP - mapping to windows file flags?

**Comment by philrykoff** [comment]
Another possibility may be (again, not the expert speaking here) extended attributes (http://man7.org/linux/man-pages/man7/xattr.7.html) ?

**Comment by billziss-gh** [comment]
The `flags` is how FreeBSD and Darwin encode what Windows calls "file attributes". So we would have to add `flags` support to WinFsp-FUSE.

We would need to:

- Get the flags. OSXFUSE uses `getattr`, because `struct stat` in OSX includes a `st_flags` field (see [`man 2 stat`](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man2/stat.2.html) on OSX). Unfortunately WinFsp-FUSE uses a `struct stat` that is compatible with Cygwin, which does not include this field!

- Set the flags. OSXFUSE uses `chflags` for this purpose. It is conceivable that we could add this operation to `fuse_operations` in WinFsp-FUSE, but we would have to make sure that we do not break compatibility somehow.

So I am open to add this extension to WinFsp-FUSE with the following caveats:

- We must make sure to do so in a backwards compatible manner. In particular our solution must **not** break Cygwin or any existing WinFsp-FUSE file systems, even if they are not recompiled!

- I do not currently have time to do this. I do accept well-written PR's however :)

> Another possibility may be (again, not the expert speaking here) extended attributes (http://man7.org/linux/man-pages/man7/xattr.7.html)?

The `getattr_x` and `setattr_x` are not the usual extended attributes, but a method for OSXFUSE to get/set additional `stat` fields that are outside POSIX (including `flags`). They are rather OSX specific and I would avoid duplicating these to WinFsp-FUSE.

**Comment by billziss-gh** [comment]
Here is a more fleshed out (potential) plan to add this feature to the FUSE interface:

- Introduce `struct fuse_stat_ex` (or `struct fuse_bigstat`?) in [`winfsp_fuse.h`](https://github.com/billziss-gh/winfsp/blob/v1.1/inc/fuse/winfsp_fuse.h) with the definition:

    ```C
    struct fuse_stat_ex
    {
        struct fuse_stat base;
        uint32_t st_flags;
        uint64_t st_reserved[3];
    };
    ```

- Introduce new capability `FSP_FUSE_CAP_FLAGS` in [`fuse_common.h`](https://github.com/billziss-gh/winfsp/blob/v1.1/inc/fuse/fuse_common.h) with the definition below. This capability instructs the FUSE layer to treat every `struct fuse_stat` as `struct fuse_stat_ex`:

    ```C
    #define FSP_FUSE_CAP_FLAGS              (1 << 23)   /* file system supports BSD/OSX flags */
    ```

- The operations `getattr` and `fgetattr` and the `typedef` `fuse_fill_dir_t` should not be changed. However if the `FSP_FUSE_CAP_FLAGS` is present (during `init`), then the `struct fuse_stat` can be treated as `struct fuse_stat_ex`. The following conversion will be valid within `getattr`, `fgetattr` and `fuse_fill_dir_t`:

    ```C
    struct fuse_stat_ex *exbuf = (struct fuse_stat_ex *)stbuf;
    ```

- Add `chflags` to `fuse_operations`. The FUSE layer receives the size of the `fuse_operations` struct in `fuse_main_real` and/or `fuse_new`, so it is possible to determine if this operation is included or not. [The logic in this [location](https://github.com/billziss-gh/winfsp/blob/v1.1/src/dll/fuse/fuse.c#L557-L558) will have to become smarter, for example.]

- Implement the internal changes required (in [`fuse_intf.c`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/dll/fuse/fuse_intf.c)) to support the new `getattr`, `fgetattr` and `fuse_fill_dir_t`.

This wraps up extending the FUSE interface in a (hopefully) backwards compatible manner. Somewhat hairy and incompatible with OSXFUSE, so I am not hugely fond of it. Better alternatives are welcome.

**Comment by billziss-gh** [comment]
Any opinions on this? I will be away next week, but I may look into implementing it for the upcoming `1.2` release.

Ping @SerCeMan. If this was added to WinFsp-FUSE would you be able to add support for it from jnr-fuse?

**Comment by philrykoff** [comment]
Your concept is sound and seems backward compatible. Sorry that I cannot help - wrong language /:

**Comment by SerCeMan** [comment]
@billziss-gh As far as I can see, from jnr-fuse point of view, the only required change is adding new win-only fields to struct which should not be a problem at all. 

Although, the solution itself sounds a bit brittle to me, but it solves the problem.

**Comment by billziss-gh** [comment]
@SerCeMan thanks for the feedback.

> The solution itself sounds a bit brittle to me, but it solves the problem.

How would you suggest we make it more robust?

**Comment by billziss-gh** [comment]
Work in progress.

**Comment by billziss-gh** [comment]
This functionality has now been added. It is currently in the pvt-flags branch but will be merged into master soon. Expect to see it in the next Beta release (`v1.2B3`).
