### ISSUE TITLE
curious read issue

### ISSUE THREAD

**Issue by wesley1975** [billziss-gh/winfsp#115]
HI billziss
I almost completed the migration, but encountered a read problem, the file can be read and write without any problems. But still is the right-click issue, up to now I found this issue affects the following documentation : ppt, pptx, doc, docx.
I found that there are some failures from the filespy:

13972	explorer.exe	FASTIO_QUERY_BASIC_INFO		\Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	FAILURE	
13973	explorer.exe	IRP_MJ_QUERY_INFORMATION     \Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	STATUS_SUCCESS	FileBasicInformation CreateTime: 01D35EB5-BC974C80 LastAccTime: 01D35EB5-BC974C80 LastWrtTime: 01D35EB5-BC974C80 ChangeTime: 01D35EB5-BC974C80 Attrib: 00000801
13974	explorer.exe	FASTIO_QUERY_STANDARD_INFO	\Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	FAILURE

does the failure lead to the subsequent reading operation?

and more when it read the file, the offset is increased slowly , it will ignore the number of data has been read out from the previous read operation：

Read: FileNode: FileName: \orders\Lab01.pptx, Openedhandle: 222, FileSize: 15996146, Buffer: 2081588248576, Offset: 15890036, Length: 4096, bytesReaded: 4096 , TID: 14

Read: FileNode: FileName: \orders\Lab01.pptx, Openedhandle: 222, FileSize: 15996146, Buffer: 2081588248576, Offset: 15890040, Length: 4096, bytesReaded: 4096 , TID: 14

Read: FileNode: FileName: \orders\Lab01.pptx, Openedhandle: 222, FileSize: 15996146, Buffer: 2081588248576, Offset: 15890082, Length: 4096, bytesReaded: 4096 , TID: 14

Read: FileNode: FileName: \orders\Lab01.pptx, Openedhandle: 222, FileSize: 15996146, Buffer: 2081588248576, Offset: 15890117, Length: 4096, bytesReaded: 4096 , TID: 14

Read: FileNode: FileName: \orders\Lab01.pptx, Openedhandle: 222, FileSize: 15996146, Buffer: 2081588248576, Offset: 15890121, Length: 4096, bytesReaded: 4096 , TID: 14

this behavior will consume a lot of time . any idea for this issue?

BTW,  the add the volume prefix doesn't work in this case and  I have clear all the context handle of explorer using the this tools
https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns

**Comment by billziss-gh** [comment]
> I found that there are some failures from the filespy:
>
> 13972	explorer.exe	FASTIO_QUERY_BASIC_INFO	\Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	FAILURE
> 13973	explorer.exe	IRP_MJ_QUERY_INFORMATION \Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	STATUS_SUCCESS	FileBasicInformation CreateTime: 01D35EB5-BC974C80 LastAccTime: 01D35EB5-BC974C80 LastWrtTime: 01D35EB5-BC974C80 ChangeTime: 01D35EB5-BC974C80 Attrib: 00000801
> 13974	explorer.exe	FASTIO_QUERY_STANDARD_INFO	\Device\Volume{5debc353-cd8e-11e7-8f3d-e4a7a064c4e9}\orders\Lab01.pptx	FAILURE
>
> does the failure lead to the subsequent reading operation?

No. These failures are perfectly normal.

There are two modes of low-level I/O in Windows: "IRP" based and "FastIO". The IRP method is the primary I/O method and is the one supported by WinFsp. FastIO is a secondary method that can only be used in specific circumstances and is **not** supported by WinFsp at this time.

What the FileSpy log is showing is that Windows is first trying the FastIO method (`FASTIO_QUERY_BASIC_INFO`) and when that fails it falls back to the IRP based method (`IRP_MJ_QUERY_INFORMATION`) which succeeds.

All this happens within the kernel and the application never knows anything about the differences between IRP-based and FastIO. Furthermore a FastIO failure cannot induce the application or even the operating system to perform a read operation.

> and more when it read the file, the offset is increased slowly , it will ignore the number of data has been read out from the previous read operation：

This is just the pattern that this particular application is using. It has nothing to do with the Windows OS or WinFsp.

If you look at your FileSpy logs you should see the `IRP_MJ_READ` operations coming into your file system and they should have the same offsets/lengths as in your logs. FileSpy will also report the original application that issued the `READ`'s.

If you are concerned about performance you need to have a caching layer somewhere. You can enable caching at the kernel level by setting `FSP_FSCTL_VOLUME_PARAMS::FileInfoTimeout==-1` in your call to `FspFileSystemCreate` (there are similar options for FUSE and .NET). This will work well; the primary gotchas are (depending on your file system): (1) that you may have cache coherency issues in a distributed/networked file system and (2) that Windows will keep files open for an indefinite amount of time.

Another alternative is to implement a caching layer in your file system. In general I prefer to let Windows uses its system cache instead of creating my own caching layer. In one file system (closed source) I use both the system cache and my own caching layer.

**Comment by wesley1975** [comment]
got it ,thanks
