### ISSUE TITLE
Wishlist: a way to get status info of mounted volumes.

### ISSUE THREAD

**Issue by mhogomchungu** [billziss-gh/winfsp#121]
I have a project called SiriKali[1] and i am investigating porting it to windows to allow users of securefs[2] to use it with a GUI.

securefs uses your project and this led me here.

In SiriKali,i will need a few things for it to work without too much effort from my part.

The things are:

1. Having a way to get a list of mounted volumes. Each volume should have the following entries: cipher folder path,mount point drive letter,file system type(this could be a name of the binary that runs the volume),if volume is run in read only or read/write mode.

2. Having a way to be notified if a new volume was mounted or a mounted volume was unmounted.

3. Having a way to unmount a mounted winfsp managed volume. In linux,fusermount command is used and in macos,umount command is used to unmount a fuse based mounted volume.

The first two can be accomplished by having an executable that hangs and simply prints information about volumes when they go online/offline. The last one can be accomplished by the same executable when given appropriate option.

Is there any tool in windows that can do any of the above three?, i am new in windows development and my google searches have so far been unsuccessful.

For the curious among us, in linux,i monitor for mount events here[3] and here on macos[4].

[1] https://mhogomchungu.github.io/sirikali/

[2] https://github.com/netheril96/securefs

[3] https://github.com/mhogomchungu/sirikali/blob/577ce427c75d19c73ec09fffb6d76287d6046b69/src/mountinfo.cpp#L271

[4] https://github.com/mhogomchungu/sirikali/blob/577ce427c75d19c73ec09fffb6d76287d6046b69/src/mountinfo.cpp#L307

**Comment by billziss-gh** [comment]
@mhogomchungu thanks for reaching out.

> 1. Having a way to get a list of mounted volumes. Each volume should have the following entries: cipher folder path,mount point drive letter,file system type(this could be a name of the binary that runs the 
volume),if volume is run in read only or read/write mode.

You ask for:
- Cipher folder path: Not possible for WinFsp to know. This is information known only to the specific file system being used. Most file systems might not even have such a concept.
- Mount point drive letter: Possible. See below.
- File system type and read only or read/write mode: Possible. See [`GetVolumeInformation`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364993(v=vs.85).aspx).

WinFsp has a way of enumerating the currently mounted volumes. There are two ways:

- Using the low-level API `FspFsctlGetVolumeList`. An example usage is shown in the `fsptool` [source](https://github.com/billziss-gh/winfsp/blob/master/src/fsptool/fsptool.c#L98-L128).
- The new (in the soon to be released `v1.2`) `fsptool` is a utility that has an `lsvol` command that lists all WinFsp volumes: [`fsptool.c`](https://github.com/billziss-gh/winfsp/blob/master/src/fsptool/fsptool.c). Presumably you could parse the output of the `lsvol` command.

These methods will simply enumerate the low-level volume paths and (in the case of `lsvol`) any drive association if there is one. For example, output from `lsvol` will look something like this:

```
# Cygwin prompt
$ ./fsptool-x64.exe lsvol
Y:  \Device\Volume{b1262245-cfdd-11e7-9ebf-080027b7ef02}\sshfs\billziss@macbook-pro-2
```

> 2. Having a way to be notified if a new volume was mounted or a mounted volume was unmounted.

Windows does not have mounting/unmounting in the UNIX sense. Here is what happens on Windows:

- A new volume (file system) is created that is accessible through a low-level name like `\Device\Volume{GUID}` or `\Device\HarddiskVolume1` (that is not normally accessible to Win32 applications). There is no event associated with volume creation/removal.

- A volume becomes available to a general application in two ways:
    - Through a special drive "symbolic link". You **CAN** listen for drive creation/removal using [`WM_SETTINGCHANGE`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725497(v=vs.85).aspx). [Disclaimer: I have not used this message in a very long time.]
    - Through a different kind of special "symbolic link" (called a "junction"), which is used to "mount" on directories. You **CANNOT** listen for this event.

> 3. Having a way to unmount a mounted winfsp managed volume. In linux,fusermount command is used and in macos,umount command is used to unmount a fuse based mounted volume.

There is currently no way to do this in WinFsp.

WinFsp was designed with the idea that the whole volume can be managed in user mode by a single kernel `HANDLE`. [Kernel `HANDLE`'s in Windows are somewhat similar to file descriptors in UNIX.] This has multiple benefits. For example, closing the volume handle (voluntarily or because of a crash) makes the volume go away: the kernel ensures that all associated kernel resources are properly cleaned up and freed. There are no ill effects, like ghost volumes, system instability, etc. Contrast this with FUSE where ghost volumes are possible.

For this reason there was never a need for an "unmount" utility in WinFsp. Furthermore, because `HANDLE`'s are private to a process, it is not possible for an "unmount" utility to get ahold of a volume `HANDLE` and somehow stop the file system (without the user mode file system's cooperation at least).

An alternative that has been discussed in #47 is to have a way to list file system **processes** (rather than volume instances -- a single file system process may control multiple volumes) and be able to send a "kill" signal to them. Unfortunately none of the solutions that we discussed seemed bulletproof to me.

The primary problem is that Windows does not have a generic method to send a "kill" signal like UNIX. For example, console vs GUI applications have different ways/protocols for asking the process to exit. The default method for ending console processes (which most file systems are) is to use [`GenerateConsoleCtrlEvent`](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent). Unfortunately this API is not very reliable and does not work in many circumstances that you would need it to work (for example, you could not use it from your GUI app to terminate a console app).

[There is always [`TerminateProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686714(v=vs.85).aspx), but that is forcible termination.]

**Comment by mhogomchungu** [comment]
```
Cipher folder path: Not possible for WinFsp to know. This is information known only to the specific file system being used. Most file systems might not even have such a concept.
```

Fuse solved this problem by allowing its clients to give it an arbitrary string it then uses as a place holder for the cipher folder. It helps in having the system hold all relevant information about an unlocked volume.

In SiriKali for example, full options it sends to securefs are like:

```
"C:/Users/Francis Banyikwa/bin/securefs.exe" mount -b  -o rw -o fsname=securefs@"C:/vault" -o subtype=securefs "C:/vault" "Z:"
```

The "subtype" argument is sent to FUSE to be "displayed" back to users as a volume file system and "fsname" option is also sent to FUSE to be "displayed" back to the user as a cipher folder path.

Will it be possible for your project to also take these FUSE options and "display" them back the way FUSE does it?.

Downloading now 1.2B3 to check it out.

**Comment by billziss-gh** [comment]
> Will it be possible for your project to also take these FUSE options and "display" them back the way FUSE does it?.

Unfortunately this is not possible in Windows. The problem is that there is only a "FileSystemName", which is equivalent to what FUSE calls "type". For example, the "FileSystemName" for all NTFS volumes is "NTFS". You cannot differentiate between NTFS volumes by looking at "FileSystemName".

Because of this reason WinFsp-FUSE ignores the `-ofsname=` and `-osubtype=` parameters and instead uses a different parameter to set the file system name: `-ofstypename=securefs`.

**Comment by mhogomchungu** [comment]
Like i explained in that securefs thread,i think the best approach for SiriKali will be to "baby sit" its backends processes on windows. The solution is not very elegant but its good enough.

This will:

1. Solve the problem of trying to close a volume since terminating a managed process will lock the volume.

2. Solve the problem of finding out information about unlocked volumes since the info is gathered when the volume is being unlocked.

Thanks for your detailed explanations. They were very informative.

**Comment by mhogomchungu** [comment]
I'll try the launcher path and see how it will go.

**Comment by billziss-gh** [comment]
Great. Let me know if I can be of help.

**Comment by mhogomchungu** [comment]
Is there more documentation for the "launchctl" command?

I have the register part setup like below and i think i am good with this part
```
[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\WinFsp\Services\securefs]
"Executable"="C:\\bin\\securefs.exe"
"CommandLine"="mount -o rw -o fstypename=securefs %1 %2"
"Security"="D:P(A;;RPWPLC;;;WD)"
"JobControl"=dword:00000001
```

Below command works but nothing happens and i assume its because securefs is stuck waiting to read password from stdin

```
C:\Program Files (x86)\WinFsp\bin>launchctl-x64.exe stop securefs securefs
OK
```

Stopping the above service seems to work as below output show
```
C:\Program Files (x86)\WinFsp\bin>launchctl-x64.exe stop securefs securefs
OK
```

So,i though i need to use the the method that takes a secret and this one fails as below output show
```
C:\Program Files (x86)\WinFsp\bin>launchctl-x64.exe startWithSecret securefs securefs C:\vault Z: "xxx"
KO launcher: error 87

```

1. What is "error 87"?
2. How do i make the launchctl take a password to send to the managed instance of securefs?

**Comment by billziss-gh** [comment]
> Is there more documentation for the "launchctl" command?

Unfortunately not at this time.

The launcher has the concept of a `ClassName` and an `InstanceName` for a file system. An example of a `ClassName` is `securefs`. An example of an `InstanceName` might be `C$\CipherFolder`.

You can start and stop a file system using the `start` and `stop` commands. You can get information about a particular instance using the `info` command, which will give you the actual command line used to launch a file system. You can list all active file systems using the `list` command.

There is also `startWithSecret` which allows you to start a file system that requires a "secret" (password, key, etc). The file system is supposed to accept the secret in standard input and is supposed to respond with "OK" in the standard output when authentication succeeds. Any other response is considered an error.

The file system must also be careful to "flush" or "close" the standard output or the "OK" message may remain in stdio buffers and never reach the launcher.

> What is "error 87"?

This error is `ERROR_INVALID_PARAMETER`.

> ```
> C:\Program Files (x86)\WinFsp\bin>launchctl-x64.exe startWithSecret securefs securefs C:\vault Z: "xxx"
> KO launcher: error 87
> ```

Your usage of `startWithSecret` looks correct to me. The `KO launcher: error 87` message comes from the launcher itself. This tells me that `launchctl` accepted your `startWithSecret` command and contacted the launcher, but the launcher responded with `ERROR_INVALID_PARAMETER`. I am not sure why.

> Why not check the return status and assume "OK" when the return status is zero? This seems the the most logical thing to check.

How could this work? If authentication succeeds the file system will start serving files and will not exit until it is stopped.

Perhaps we could say that if the file system does not exit it implies success. But how long should the launcher wait before assuming success? 5 seconds? 15?

Clearly an alternative method to signify success was needed. I could have chosen a fancy Windows IPC method, but I wanted something that worked on native Windows and Cygwin apps. This made stdio the only reliable (and portable) option even if it means that sometimes file systems have to be modified to return the "OK" response.

**Comment by mhogomchungu** [comment]
I updated my previous comment to put a correct command that starts a service without using a secret. Previous,it a command to stop a service. 

Listening on stdout for "success" signal from clients seems like the simplest approach and i will make a request with securefs for it to respond with "OK" to make it compatible with the launcher. Maybe the problem is here.

I have played around a bit with launchctl and i think it has everything i need.

Passing secrets as command line argument is not a good idea because those secrets will be visible to everybody who inspects the process arguments[1]. I think it will be better if you read them from stdin.

[1] https://superuser.com/questions/415360/how-do-i-find-out-command-line-arguments-of-a-running-program

**Comment by mhogomchungu** [comment]
```
The file system is supposed to accept the secret in standard 
input and is supposed to respond with "OK" in the standard 
output when authentication succeeds. Any other response is
considered an error.
```

This seems like a harsh requirement because it means processes are no longer allows to use stdout to communicate anything with their clients because launcher will get confused when these processes are managed by it.

A better solution is to request that the first line of the printed text be "OK". This way, process can make launcher happy by printing the line first and continue to use stdout normally.

**Comment by billziss-gh** [comment]
> Passing secrets as command line argument is not a good idea because those secrets will be visible to everybody who inspects the process arguments[1]. I think it will be better if you read them from stdin.

I agree in principle. This is why the launcher passes the secret over stdin and not as a command line argument to the file system.

OTOH, `launchctl` was designed to be a test utility and for this reason I have not cared much about its security until now. If now we start using it as a utility to access WinFsp functionality from external programs (as you are doing with SiriKali) then perhaps we need to change this. Please also note that `launchctl` is a short-lived process, so the problem is somewhat mitigated.

Note also that the builtin way of using the launcher (the "Network Provider" that enables the "Map Network Drive" functionality) does not use `launchctl` and does not suffer from this problem. Instead it connects to the launcher directly. Perhaps it would be best if SiriKali did this too. To facilitate this I could abstract some of the `launchctl` functionality into a library of sorts.

> A better solution is to request that the first line of the printed text be "OK". This way, process can make launcher happy by printing the line first and continue to use stdout normally.

I think what you are asking for, will work in reality. But the stdout will go missing because it cannot be seen and is not logged anywhere when running in the Windows Service context (under the launcher).

Here is what I do with [SSHFS-Win](https://github.com/billziss-gh/sshfs-win) instead, which is a port of the Linux [SSHFS](https://github.com/libfuse/sshfs). I added an option [`password_stdout `](https://github.com/billziss-gh/sshfs-win/blob/master/patches/01-passwd.patch) to the file system. When that option is given the file system prints "OK" on authentication success or "KO" on authentication failure and then closes the stdout. So the file system can be run in the command line without the `--password-stdout` option and behave normally, or it can be passed the `--password-stdout` option for launcher authentication purposes.

Closing the stdout does two things: it flushes the stdio buffers and it also ensures that no unnecessary output is sent in the Windows Service context. This of course assumes that the file system does not do something like checking the return value of `printf`. If you do not like the "close stdout" pattern you can also flush the stdout instead.

**Comment by billziss-gh** [comment]
BTW, in thinking about your use of the launcher and launchctl I am finding that:

- The launcher functionality was designed primarily to facilitate the Explorer "Map Network Drive" and the command line `net use` functionality ("Network Provider" functionality). I am wondering if also using it for SiriKali purposes can confuse the Network Provider and/or SiriKali and make either one of them perform suboptimally.
    - Going forward I am thinking of introducing a `"Filter"="AGENT"` registry value that describes which external "agent" (SiriKali, Network Provider, etc.) is the primary user of a particular launcher entry. This way you could create multiple entries for SiriKali without worrying that they might interfere with the Network Provider by using `"Filter"="SiriKali"` for them.
- It may be worthwhile to abstract the launchctl functionality into a library for use by external applications as discussed earlier.

**Comment by mhogomchungu** [comment]
A library interface is better than calling CLI components.

**Comment by mhogomchungu** [comment]
I am closing this one because "launchctl" provides the information i need. This also means i just tied SiriKali to winfsp and support for securefs will be possible only when/if securefs starts to use the launcher infrastructure.

**Comment by billziss-gh** [comment]
@mhogomchungu just wanted to let you know that I have added a "launch" API in commit e111451475574f5888719a57c474db5d1780a8cc. This is currently in a private branch, but I will be merging into master soon.

Here are the docs:

```C
/**
 * @group Launch Control
 */
/**
 * Call launcher pipe.
 *
 * This function is used to send a command to the launcher and receive a response.
 *
 * @param Command
 *     Launcher command to send. For example, the 'L' launcher command instructs
 *     the launcher to list all running service instances.
 * @param Argc
 *     Command argument count. May be 0.
 * @param Argv
 *     Command argument array. May be NULL.
 * @param Argl
 *     Command argument length array. May be NULL. If this is NULL all command arguments
 *     are assumed to be NULL-terminated strings. It is also possible for specific arguments
 *     to be NULL-terminated; in this case pass -1 in the corresponding Argl position.
 * @param Buffer
 *     Buffer that receives the command response. May be NULL.
 * @param PSize
 *     Pointer to a ULONG. On input it contains the size of the Buffer. On output it
 *     contains the number of bytes transferred. May be NULL.
 * @param PLauncherError
 *     Receives the launcher error if any. This is always a Win32 error code. May not be NULL.
 * @return
 *     STATUS_SUCCESS if the command is sent successfully to the launcher, even if the launcher
 *     returns an error. Other status codes indicate a communication error. Launcher errors are
 *     reported through PLauncherError.
 */
FSP_API NTSTATUS FspLaunchCallLauncherPipe(
    WCHAR Command, ULONG Argc, PWSTR *Argv, ULONG *Argl,
    PWSTR Buffer, PULONG PSize, PULONG PLauncherError);
/**
 * Start a service instance.
 *
 * @param ClassName
 *     Class name of the service instance to start.
 * @param InstanceName
 *     Instance name of the service instance to start.
 * @param Argc
 *     Service instance argument count. May be 0.
 * @param Argv
 *     Service instance argument array. May be NULL.
 * @param HasSecret
 *     Whether the last argument in Argv is assumed to be a secret (e.g. password) or not.
 *     Secrets are passed to service instances through standard input rather than the command
 *     line.
 * @param PLauncherError
 *     Receives the launcher error if any. This is always a Win32 error code. May not be NULL.
 * @return
 *     STATUS_SUCCESS if the command is sent successfully to the launcher, even if the launcher
 *     returns an error. Other status codes indicate a communication error. Launcher errors are
 *     reported through PLauncherError.
 */
FSP_API NTSTATUS FspLaunchStart(
    PWSTR ClassName, PWSTR InstanceName, ULONG Argc, PWSTR *Argv0,
    BOOLEAN HasSecret,
    PULONG PLauncherError);
/**
 * Stop a service instance.
 *
 * @param ClassName
 *     Class name of the service instance to stop.
 * @param InstanceName
 *     Instance name of the service instance to stop.
 * @param PLauncherError
 *     Receives the launcher error if any. This is always a Win32 error code. May not be NULL.
 * @return
 *     STATUS_SUCCESS if the command is sent successfully to the launcher, even if the launcher
 *     returns an error. Other status codes indicate a communication error. Launcher errors are
 *     reported through PLauncherError.
 */
FSP_API NTSTATUS FspLaunchStop(
    PWSTR ClassName, PWSTR InstanceName,
    PULONG PLauncherError);
/**
 * Get information about a service instance.
 *
 * The information is a list of NULL-terminated strings: the class name of the service instance,
 * the instance name of the service instance and the full command line used to start the service
 * instance.
 *
 * @param ClassName
 *     Class name of the service instance to stop.
 * @param InstanceName
 *     Instance name of the service instance to stop.
 * @param Buffer
 *     Buffer that receives the command response. May be NULL.
 * @param PSize
 *     Pointer to a ULONG. On input it contains the size of the Buffer. On output it
 *     contains the number of bytes transferred. May be NULL.
 * @param PLauncherError
 *     Receives the launcher error if any. This is always a Win32 error code. May not be NULL.
 * @return
 *     STATUS_SUCCESS if the command is sent successfully to the launcher, even if the launcher
 *     returns an error. Other status codes indicate a communication error. Launcher errors are
 *     reported through PLauncherError.
 */
FSP_API NTSTATUS FspLaunchGetInfo(
    PWSTR ClassName, PWSTR InstanceName,
    PWSTR Buffer, PULONG PSize,
    PULONG PLauncherError);
/**
 * List service instances.
 *
 * The information is a list of pairs of NULL-terminated strings. Each pair contains the class
 * name and instance name of a service instance. All currently running service instances are
 * listed.
 *
 * @param Buffer
 *     Buffer that receives the command response. May be NULL.
 * @param PSize
 *     Pointer to a ULONG. On input it contains the size of the Buffer. On output it
 *     contains the number of bytes transferred. May be NULL.
 * @param PLauncherError
 *     Receives the launcher error if any. This is always a Win32 error code. May not be NULL.
 * @return
 *     STATUS_SUCCESS if the command is sent successfully to the launcher, even if the launcher
 *     returns an error. Other status codes indicate a communication error. Launcher errors are
 *     reported through PLauncherError.
 */
FSP_API NTSTATUS FspLaunchGetNameList(
    PWSTR Buffer, PULONG PSize,
    PULONG PLauncherError);
```

**Comment by mhogomchungu** [comment]
I have a question about an API like ```FspLaunchGetNameList```

What happens when passed in buffer is not large enough to hold the API output? Will the API fail(with what error code?) or will it succeed with a truncated result?

**Comment by billziss-gh** [comment]
> I have a question about an API like `FspLaunchGetNameList`
>
> What happens when passed in buffer is not large enough to hold the API output? Will the API fail(with what error code?) or will it succeed with a truncated result?

The way it is done currently it will succeed with a truncated result.

The maximum limit of data that can be exchanged in a single request is `LAUNCHER_PIPE_BUFFER_SIZE`, which is currently 4096 bytes. We should probably raise this somewhat (e.g. to 16384), although 65536 is the maximum that the system can support.

**Comment by mhogomchungu** [comment]
I cant seem to get the API to work.

FsoVersion returns "65539" which corresponds to "0x10003" and this API appears to work correctly.

"FspLaunchGetInfo" and "FspLaunchGetNameList" do not appear to work.

""FspLaunchGetInfo"" fshows the following behaviors here:

1. The API returns 0 meaning success.
2. PLauncherError value returns zero meaning success,
3. I passed Psize value of 1024 and 184 is returned meaning the buffer was filled up with those many characters.
4. Buffer contents stays the same breaking the API.

Could you give an example of how to use "FspLaunchGetNameList" API? Reading the API documentation and it was not clear to me how the buffer containing "list of pairs of NULL terminated strings" should be parsed.

**Comment by billziss-gh** [comment]
My apologies. In my rush to release the first beta of v1.3, I did not properly test the return path of `FspLaunchCallLauncherPipe`. I will add some tests and fix any problems.

**Comment by billziss-gh** [comment]
@mhogomchungu please try the latest release [2018.1 B2](https://github.com/billziss-gh/winfsp/releases/tag/v1.3B2) where I believe I have fixed the problems with the FspLaunch API.

**Comment by mhogomchungu** [comment]
Just installed it and the include folder has only "fsctl.h" and "winfsp.h", your documentation[1] says the API i want is in "launch.h" but this header file is not present.

[1] https://github.com/billziss-gh/winfsp/wiki/WinFsp-API-launch.h

**Comment by billziss-gh** [comment]
Please get it from here: [`launch.h`](https://github.com/billziss-gh/winfsp/blob/master/inc/winfsp/launch.h). It has not been included in the installer yet.

**Comment by mhogomchungu** [comment]
The library seems to work now(it was probably working earlier too and i was just making a mistake)

My first attempt at using the API is here[1].

I must say, parsing a buffer with multiple NULLs in it is not something everybody should be doing.

If i was you, i would convert the results to more or less what i did, to a vector of structs with the struct filled with relevant fields.

In C,it will be something like

[1] https://github.com/mhogomchungu/sirikali/blob/2577907f9da4a1297d15b9a5bcfcdfa18b27303e/src/mountinfo.cpp#L132-289

**Comment by billziss-gh** [comment]
> The library seems to work now(it was probably working earlier too and i was just making a mistake)

I think there was a genuine problem that you identified and I had to fix. I now added tests so we should be able to maintain quality as we evolve the FspLaunch API.

> In my opinion, parsing a buffer with multiple NULLs in it is not something everybody should be doing.

I do not disagree in principle.

However I note that WinFsp is a low-level C API (its purpose is to write file systems) and in general I have chosen to keep abstractions simple. Furthermore the convention of returning null-terminated strings in sequence is actually common in C. See, for example, the Linux [`listxattr`](http://man7.org/linux/man-pages/man2/listxattr.2.html).
