### ISSUE TITLE
question: support for files over 2 GB on x86 Windows

### ISSUE THREAD

**Issue by cdarau** [billziss-gh/winfsp#125]
I noticed that I can't transfer files that are over 2GB in size, even when trying to set the corresponding option to allow that. Is this a limitation of the software or it can be workaround somehow? Thank you.

**Comment by billziss-gh** [comment]
Which file system?

On x86 an offset > 2GB would cross into "negative" territory, so this may be a feature or a bug :)

**Comment by cdarau** [comment]
For example, when I run this command:
`memfs-x86 -u \memfs32\share2 -m * -s 2147483648`
I get this message:
`memfs -t -1 -n 1024 -s 2147483647 -u \memfs32\share2 -m Z:`
From what I know, the x86 Windows limitation would stand at 4GB, not at 2GB, but even at 4GB it's still overpassable with address window extension, AWE.
The thing is that I need to be able to copy large files (even >4GB), that's why I'm asking.

**Comment by billziss-gh** [comment]
MEMFS uses a ULONG to store the MaxFileSize. Furthermore during command line parsing the size is restricted to 2^31 during command line parsing. The reason is that MEMFS stores everything in RAM and I wanted to have some "reasonable" limits for it.

WinFsp itself does not limit file sizes to 31 bits.

**Comment by billziss-gh** [comment]
@cdarau has your question been answered? If yes, I will close this.

**Comment by cdarau** [comment]
Yes, thank you.
