### ISSUE TITLE
Synchronous operations on WinFSP mounted file system (Question)

### ISSUE THREAD

**Issue by stanimirivanovde** [billziss-gh/winfsp#136]
My Question: are write operations on a mounted WinFSP file system asynchronous? My asserts in my unit tests are failing and after some experimentation it appears that writes are asynchronous.

Currently I have unit tests for a mounted file system. These include creating a file, adding some contents and then reading the file's size, contents etc from the file system. Currently it looks like the create and write operations are executed asynchronously and my unit tests fail because they see the file as empty (size 0) after a write(). If I add a sleep() between the write and the length check then the issue is fixed some of the times. And if I add 2 consecutive calls to get the size of the file before the actual testing assert, the file size is finally retrieved correctly and the test passes.

The unit tests run fine on Mac OS X so I wonder if this is something specific to Windows?

**Comment by billziss-gh** [comment]
> My Question: are write operations on a mounted WinFSP file system asynchronous?

Most I/O operations on Windows (and WinFsp) are asynchronous internally. However I am not sure this is relevant based on my understanding of what you are experiencing.

> Currently it looks like the create and write operations are executed asynchronously and my unit tests fail because they see the file as empty (size 0) after a write().

Windows file systems do not behave like POSIX ones. If you extend a file by writing to it, the file system makes a note of the new file size, but does not necessarily update the directory entry for the file. (For example, this is now NTFS behaves). You can then have the interesting situation where `FindFirstFile` reports a file size of 0, whereas `GetFileInformationByHandle` reports the correct file size.

On WinFsp both scenarios are supported. A couple of questions:

- Is your file system a FUSE file system?
- Are you certain that the file system updates its own file sizes correctly on `write`?

**Comment by fsgeek** [comment]
In addition to only updating directory entries when the file is closed,
NTFS only updates the size of the link that was used when the given file
was opened.  Thus, it is possible to have two (or more) hard links to a
file, each showing a different size.  Of course, any access to the file via
the name with stale directory information will cause the directory
information to be updated.

Traditionally, UNIX file systems did not store the size or attributes of
the file in the directory entry because directory enumeration merely
returned the file name.  To obtain those file attributes required opening
each individual file, which is an expensive operation. Caching this
information in the directory entry itself does lead to irregularities, but
any enumeration interface in this area is subject to returning the wrong
information under certain circumstances.

**Comment by stanimirivanovde** [comment]
@billziss-gh to answer your questions:

> Is your file system a FUSE file system? [UPDATE: just saw on other issue that you are using jnr-fuse.]

Yes it is FUSE. It is exposed through jnr-fuse as you already found out.

> Are you certain that the file system updates its own file sizes correctly on write?

Since this is written as a Java application I was going through the Java docs today trying to see all synchronous and asynchronous examples and explanations to see if there is anything I can do to control the data and metadata updates. It turns out there is a way to control the synchronicity of the writing operation (file system dependent of course). It is done using the StandardOpenOption.SYNC flag when writing the file.

Here is the relevant Java doc: https://docs.oracle.com/javase/7/docs/api/java/nio/file/StandardOpenOption.html

After using the flag I can correctly retrieve the file size out of the mounted FUSE file system. The last thing I am trying to figure out now is why my encrypted files, which I create as I put files into the FUSE mounted path, are coming with wrong size as well. This is probably an issue on my end, but it is interesting to see that Mac OS X doesn't have such problem.

**Comment by billziss-gh** [comment]
> The last thing I am trying to figure out now is why my encrypted files, which I create as I put files into the FUSE mounted path, are coming with wrong size as well. This is probably an issue on my end, but it is interesting to see that Mac OS X doesn't have such problem.

I do not quite understand the scenario you are outlining here. Can you please elaborate? It might also be beneficial to explain a bit more about how your file system works, so that we can pinpoint the issues.

Speculation: If your file system is somehow passing through the operations that it receives to an underlying file system, you have to consider many effects:

- How the underlying file system (presumably NTFS) behaves. The underlying file system stores data and metadata in a certain fashion and your own file system's behavior depends on how the underlying file system behaves.

- How the Java file I/O layer behaves. I have found that many cross-platform language frameworks often take a POSIX-centric view of the world and they may exhibit problems on Windows, at least when you use those frameworks to create a file system. (This was certainly the case in Go and even Microsoft's .NET, which I have used to create pass through file systems.)

- How your own file system behaves.

    - For example, if you simply forward a `write` (perhaps after encrypting data) to an underlying NTFS file, NTFS will update the file data, but not the file's directory entry (or entries as fsgeek says). If the size you report during `getattr` is somehow based on the size from the NTFS directory entry, you will report the wrong size.

**Comment by timofonic** [comment]
@billziss-gh Sorry to interrupt. I was reading this and got interested in the follwing:
* Is @SerCeMan's [jnr-fuse](https://github.com/SerCeMan/jnr-fuse) really necessary when dealing with a file system implementation written in Java? Does WinFSP provides language bindings for different programming languages?
* Do you mean Windows File Systems have limitations?

**Comment by stanimirivanovde** [comment]
@billziss-gh it turned out this is purely my fault. WinFSP was calling my Fuse wrapper in an asynchronous way and I had to implement manual locking to not allow a new request to start processing while a previous is in the work. The main issue was that as the files were being created a new request for the file size will come in and since the file is not fully written yet the size will be less than the expected size. This caused many of my unit tests to fail. Interestingly enough this is not the behaviour in osxfuse (Mac OS X).

So to answer my question more completely:

- I don't observe any misrepresentation of file metadata from WinFSP. The file size is reported as is in the instance of the request. I didn't see any buffering or delayed writes beyond the buffering done in Java.
- WinFSP calls asynchrounously the jnr-fuse callbacks without waiting for them to finish first. This is why a manual locking mechanism is needed in order to guarantee the right order of operations. This is important in complex operations where an operation can perform multiple state changes to a file and a call to getattr() in the middle of the state changes will return the wrong file attributes (for example). Another example is if a delete operation is requested followed immediately by a read operation. If both operations are allowed to be executed asynchronously then it would result in a problem. The first operation needs to be allowed to finish completely before the second is processed.

**Comment by billziss-gh** [comment]
@timofonic I answered your questions yesterday, but somehow my answers have vanished! I am not sure why this happened.

In a nutshell:

- Yes, jnr-fuse is necessary because WinFsp does not provide a Java API/binding. The default WinFsp installation: provides a native API, a FUSE compatible API and a .NET API that wraps the native API.

- Yes, Windows file systems have many limitations. These limitations are usually related to manipulating the file system name space (e.g. remove or rename files/directories).

**Comment by billziss-gh** [comment]
@stanimirivanovde 

> @billziss-gh it turned out this is purely my fault. WinFSP was calling my Fuse wrapper in an asynchronous way and I had to implement manual locking to not allow a new request to start processing while a previous is in the work. The main issue was that as the files were being created a new request for the file size will come in and since the file is not fully written yet the size will be less than the expected size. This caused many of my unit tests to fail. Interestingly enough this is not the behaviour in osxfuse (Mac OS X).

A FUSE file system is supposed to be multi-threaded by default. To change this you can pass the `-s` parameter, which asks for "single threaded" operation. In the WinFsp-FUSE implementation your operations will still be called on multiple threads, but you can be assured that your operations are serialized through a mutual-exclusion lock. (This also means that when using the `-s` switch you cannot use thread-local storage.)

An alternative is to protect your data structures with your own locks.

The FUSE implementations of WinFsp and OSXFUSE are completely unrelated for obvious reasons. The order that operations will be called, their timings, etc. will be completely different between the two FUSE implementations.

**Comment by stanimirivanovde** [comment]
> The FUSE implementations of WinFsp and OSXFUSE are completely unrelated for obvious reasons. The order that operations will be called, their timings, etc. will be completely different between the two FUSE implementations.

@billziss-gh, this makes working with FUSE in a completely cross platform way difficult. But it is the best we got so far. The POSIX standard on most Linux systems is fairly consistent. But then we have Mac OS X which is somewhat different and Windows which is very different.

**Comment by billziss-gh** [comment]
@stanimirivanovde

> this makes working with FUSE in a completely cross platform way difficult. But it is the best we got so far.

I agree. Using FUSE in a cross-platform way is non-trivial, but certainly feasible. There are quite a few FUSE file systems running on Windows as proof.

I would like to close this issue as it seems the original ask has been addressed. Please reopen if you think otherwise.
