### ISSUE TITLE
FUSE: create_umask option

### ISSUE THREAD

**Issue by billziss-gh** [billziss-gh/winfsp#138]
Add a FUSE `create_umask` option that applies a default `umask` when a file is created with a `NULL` (default) security descriptor.

See billziss-gh/sshfs-win#14.

**Comment by xelra** [comment]
Any progress on this? I need to ssh into my servers after every file I create and fix its permissions. It would be really great to have this option.

**Comment by billziss-gh** [comment]
I have been working non-stop on a new file system for the cloud and have not devoted much time on this. I am hoping to be able to look into it in a couple of weeks.

You may also want to consider adding a PR for this. It should not be hard to do. The relevant files are in [`fuse.c`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse.c) and [`fuse_intf.c`](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse_intf.c). You would have to roughly follow the code for the `umask` option, except that you would have to modify `Create` instead of `GetFileInfoFunnel`. The code at this [link](https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse_intf.c#L756) would probably have to be modified to read:

```C
    if (f->set_create_umask)
        Mode = 0777 & ~f->create_umask;
```

(Or something along these lines.)

**Comment by bjquinn** [comment]
Just chiming in on this as well -- without this, newly created files can't be seen by anyone other than the file creator and root, which isn't helpful when trying to allow access to a shared file storage repository across multiple users.  SSHFS so convenient to have on Windows, but this missing feature is limiting my usage.

**Comment by billziss-gh** [comment]
Commit 994e232fb306d4c0216ac8fe64e18822501dafe3 should fix this.

**Comment by billziss-gh** [comment]
This fix will be included in the next beta (2018.1 B3)

**Comment by bjquinn** [comment]
@billziss-gh excellent, thanks!

**Comment by bjquinn** [comment]
@billziss-gh just curious, when do you expect 2018.1 B3 to be released?  And will I just need the latest winfsp, or an updated sshfs-win as well?

**Comment by billziss-gh** [comment]
My timeframe is early to mid-May. I do not think that a new version of SSHFS-Win will be needed.

**Comment by billziss-gh** [comment]
[WinFsp 2018.1 B3](https://github.com/billziss-gh/winfsp/releases/tag/v1.3B3) is out and includes `create_umask`. Please try it out and report back.

**Comment by Shaddoh** [comment]
Apologies for what might seem like a rookie question
net use [drive_letter]: \\sshfs\%username%=[username_on_server]@[server_address]\..\..\opt [password]
As an example.
To add the create_umask: Is it a command line entry added to this? Or how would you actually pass it on?

**Comment by Shaddoh** [comment]
Open a command prompt.
cd C:\Program Files\SSHFS-Win\bin
set CYGFUSE=WinFsp
set PATH=C:\Program Files\SSHFS-Win\bin
sshfs.exe -f -o create_umask=000 user@server: z:

I tried the above but it gave only ability to create a folder and no items, also when you created a folder it created 4 of them.

**Comment by Shaddoh** [comment]
C:\Program Files\SSHFS-Win\bin>sshfs.exe -f -o uid=-1,gid=-1 user@server: z:
This cmd line does mount the drive, I can create folders and files on the original mount.
If I go into a folder I create I can not create anything inside of it. 
Also From a computer on network using smb share I can not access the folder I made .

Using -o idmap=user , I can only create a folder on the mount, and it creates 4 of them. Also not able to write to from another pc on the network using smb.

My main goal is to use these mounts off site but also have people on site be able to access the files and folders the others are creating. 

The main building is running centos file server using samba config to share to windows clients

In looking at ls -alFrt to see permissions I do see the file permissions changed from rwx------ to rwx r-x r-x. So it looks like somewhere it is not generating write permissions. and this is when using -o idmap=user

**Comment by Shaddoh** [comment]
Also Just more info when using sshfs.exe -f -o uid=-1,gid=-1 user@server: z the permissions it gives the folder are rwx r-x ---

**Comment by bjquinn** [comment]
Ok, I downloaded 2018.1 B3 and was going to try the create_umask option.  Is it only accessible through sshfs.exe?  Or can I set that somehow when doing net use?

**Comment by billziss-gh** [comment]
At this time it is only accessible when using sshfs.exe directly.

**Comment by bjquinn** [comment]
Ah ok.  I'm familiar with the net use syntax, but not the method for connecting via sshfs.exe.  Is there some documentation or an example for that?

**Comment by billziss-gh** [comment]
The easiest other option is to use @mhogomchungu's [SiriKali](https://mhogomchungu.github.io/sirikali/). He has some specific SSHFS instructions [here](https://github.com/mhogomchungu/sirikali/wiki/Frequently-Asked-Questions#90-how-do-i-add-options-to-connect-to-an-ssh-server).

**Comment by bjquinn** [comment]
Ok, by doing the following, I'm getting 755 permissions instead of 700 permissions, which is close, but not quite what I'm looking for.  If I'm not mistaken, create_umask=000 should create files with 666 permissions and directories with 777?  Instead I'm getting both files and directories as 755.

```
set PATH=C:\Program Files\SSHFS-Win\bin
"c:\Program Files\SSHFS-Win\bin\sshfs.exe" -f -o idmap=user,create_umask=000 root@mail.placs.net:/usr/src z:
```

**Comment by billziss-gh** [comment]
The `create_umask` is the umask that files will be created with on the SSHFS server. You will also need the regular `umask` option if you want files to have 666 or 777 permissions.

Like so: `-o idmap=user,create_umask=000,umask=000`

**Comment by bjquinn** [comment]
Yeah, I'd tried that already as well, but I'm still getting 755 on new files.

**Comment by billziss-gh** [comment]
Where do you see the 0755? On the server side or on the Windows side (e.g. with Cygwin).

**Comment by bjquinn** [comment]
On the server.  And if I log in as another user and try to write to one of the files, I can't do it.

I'm seeing rwxr-xr-x on both new files and directories from the server command line.

**Comment by billziss-gh** [comment]
Ok.  Your issue may be that the SSH server itself has its own umask and this has nothing to do with SSHFS is launched. This stackoverflow article describes a method to change the SSH server umask:

https://unix.stackexchange.com/questions/289277/set-umask-for-sshfs-mounted-filesystem

**Comment by bjquinn** [comment]
Ok, that's even closer.  On my test system, /etc/ssh/sshd_config already had an entry for "Subsystem sftp /usr/libexec/openssh/sftp-server" in it, so I simply added "-u 000" to the end of that, service sshd restart, disconnect/reconnect from my Windows client.

Now, newly created files are 777, owned by whichever the user was that created the file.  However, if I create a file logged in as root, then another user still can't modify the file via sshfs, even though it's 777.

Via the command line, the 2nd user can edit the files owned by root but with 777 perms.  Is there another umask setting I'm missing somewhere?  It must be sshfs (or sshd) related somehow, as it seems to have the correct perms on the file now, and it allows writing from the command line as that user.

**Comment by bjquinn** [comment]
I wondered if you had any additional thoughts on this.  I'm getting correct perms set on the file now, but I still can't write to a file unless it's owned by the user you're logged in as.

**Comment by billziss-gh** [comment]
Unfortunately I do not.

On the Windows side the options that control users/permissions are:

```
WinFsp-FUSE:
    -o uid=UID              will set the file owner as UID
    -o uid=-1               will set the file owner as the user that launched the file system
    -o gid=gid              will set the file group owner as GID
    -o gid=-1               will set the file group owner as the user that launched the file system
    -o umask=000            will enable 0777 permissions
    -o create_umask=000     will give 0777 permissions to newly created files

SSHFS-Win:
    -o idmap=user           will map local user names to remote user names
```

However these permissions are only checked/enforced on the client side. If the SSH server denies access for other reasons, these options will not help.

**Comment by bjquinn** [comment]
I don't think that's the problem though -- the permissions are correct, they're 777.  At that point the owner shouldn't matter (though it is root:root in this case).  I can successfully log in with the non-root user via ssh and modify the file, which makes sense -- if it's 777, it doesn't matter who you are.  But through sshfs-win, I get denied permission.

**Comment by billziss-gh** [comment]
Even though SSHFS-Win sees the `777` permissions and allows access, it then forwards the request to the remote computer, which may still deny it.

**Comment by bjquinn** [comment]
It's not the remote computer denying it though.  Apart from being able to ssh in directly and modify the files that are chmod 777 via command prompt, I went ahead and set up an sshfs mount from a remote linux client and connected via sshfs to the same folder on the same server using the same user and mount options, and I'm able to modify 777 files using the non-root user.  The only client configuration that has an issue is sshfs-win, where I get "You do not have permission to open this file" when trying to write (I can in fact open/read it, however).

**Comment by billziss-gh** [comment]
Can you please let me know:

- The full command line that you use to start `sshfs`.
- The output of `fsptool-x64 id` (found in `\Program Files (x86)\WinFsp\bin`).
- The remote user name and group name (e.g. by running `id` on the remote SSH server).
- Whether your account is on a Windows domain and if there is any cross-domain involved.

**Comment by xelra** [comment]
This is a shot in the dark, but are you using the `allow_other` option?

**Comment by bjquinn** [comment]
@billziss-gh here's my full command line:
set PATH=C:\Program Files\SSHFS-Win\bin
"c:\Program Files\SSHFS-Win\bin\sshfs.exe" -f -o idmap=user,create_umask=000,port=9010,allow_other bjquinn@server:/usr/src z:

fsptool-x64 id:
User=S-1-5-21-2239680543-2890104720-1015646997-1001(DESKTOP-LC039JI\bjquinn) (uid=197609)
Owner=S-1-5-21-2239680543-2890104720-1015646997-1001(DESKTOP-LC039JI\bjquinn) (uid=197609)
Group=S-1-5-21-2239680543-2890104720-1015646997-513(DESKTOP-LC039JI\None) (gid=197121)

id:
uid=500(bjquinn) gid=500(bjquinn) groups=500(bjquinn)

Account is not on a domain.

@xelra thanks for the suggestion.  I had not been using allow_other, but adding it did not change anything.

**Comment by billziss-gh** [comment]
The `allow_other` option is actually ignored on WinFsp, because the concept of `root` and `other` users makes little sense on Windows.

@bjquinn, based on the way you start the file system:

- The `bjquinn` user should be mapped to the SSH server `bjquinn` user (this is done by SSHFS when given the `idmap=user` option).
- Files should have their default permissions as there is no `umask` option on the command line.
- New files should be created with `rwxrwxrwx` permissions because of the `create_umask` option.

Please note that the `umask` and `create_umask` option are NOT the same. The `create_umask` option is only used when you create new files. I suspect that if you were to also use `umask=000` your problem might be resolved.

However I believe that the real problem is different:

- First, note that on UNIX the user and group namespaces are separate. So it is possible to have a UID of 500 and a GID of 500 and they identify different things (the UID a user and the GID a group). This is not the case on Windows where a "Security Identifier" (SID) can identify either a user or a group and for our purposes CAN ACT AS BOTH AT THE SAME TIME.

- Second, note that you are using `idmap=user` and that your user name and group name are the same on the SSH server! I suspect that SSHFS maps both of those to the same Windows SID, the SID of the Windows user `DESKTOP-LC039JI\bjquinn`.

- Suppose that you have a file that is owned by `uid=500,gid=500` and has permissions `rw-r--r--`. The `idmap=user` option will translate those options to the same Windows SID and WinFsp-FUSE will have to make a decision whether to apply the `rw-` permissions for the user or the `r--` permissions for the group. Unfortunately WinFsp-FUSE chooses the most restrictive option (which in this case is `r--`) and you will be denied write permission.

I think the best way to fix this problem is to start the file system with the options `uid=-1,gid=-1` instead of `idmap=user`.

**Comment by bjquinn** [comment]
create_umask=000 is intentional, the goal is to create new files with 777 permissions.  This means that existing permissions on folders would have the expected result of allowing or preventing access to other users, but new files in allowed folders would continue to be accessible to anyone who could already get to the folder in question (this is managed outside of sshfs-win, of course).

Changing to uid=-1,gid=-1 seems to work!  What exactly does setting uid and gid to -1 mean?  Does it basically just set the uid/gid for the connection to whatever the user you're logging in as, regardless of which Windows user uses it?  I suppose this is rather than trying to map specific Windows users to unix/linux users, in case the network drive was accessed by multiple Windows users?

Side note, the files I was having trouble writing to were already rwxrwxrwx, but I could only write to them if they were also OWNED by the non-root user I was logging in as.  Yes, my server user/group was the same, though that's simply because that's the default behavior of useradd, and I didn't think anything of it.  At any rate, I'd have suspected that wouldn't have been a problem anyway, since the file was already rwxrwxrwx, so in this case it wouldn't matter whether it tried to evaluate user or group permissions on the file.

**Comment by billziss-gh** [comment]
The `uid=-1,gid=-1` sets the UID, GID of the files to be the same as the user launching the file system (in your case user `DESKTOP-LC039JI\bjquinn` and group `DESKTOP-LC039JI\None`).

**Comment by bjquinn** [comment]
Excellent, thank you!  This is an extraordinarily useful tool, thanks for your work on it.

For reference, I created a file with uid=-1,gid=-1,create_umask=000 and I got rwxrwxrwx (expected) and the ownership of the file was bjquinn:testgroup, meaning it took the group of the unix user (which I added later after you mentioned the issue with the user and group being the same), not "None" (or "nobody", I suppose) from the Windows user.  Personally, that's exactly what I'd prefer, so this works for me.

**Comment by billziss-gh** [comment]
I am glad that it finally worked for you!

**Comment by Shaddoh** [comment]
Hey Guys, Though I would chime back in. These are the things that got me up and running.

/etc/ssh/sshd_config already had an entry for "Subsystem sftp /usr/libexec/openssh/sftp-server" in it, so I simply added "-u 000" to the end of that, service sshd restart, disconnect/reconnect from my Windows client.

best way to fix this problem is to start the file system with the options uid=-1,gid=-1 instead of idmap=user

create_umask=000

Piecing together all the conversation from above. These 3 things added to what I was doing solved all my permission issues. 

Thank you to Bill who wrote this amazing software and to bjquinn at working through the issue at a more technical level than I.

**Comment by Shaddoh** [comment]
Hey Bill, This is great. Is there a way to pass the parameters on to net use? 
The uid, gid, create umask?

**Comment by Shaddoh** [comment]
Ok, Thank you. Is there any plans on it being there in future? 

Also I am trying to do this through a script and it gets hung on asking for the password. Is there a way to  have that in the command line or a way to auto answer it?

**Comment by billziss-gh** [comment]
The UNC syntax is very limited so adding options would not be straightforward.

Try using the `-o password_stdin` option to pass the password through standard input. Passing passwords on the command line is considered a bad idea, because command lines for running processes can be retrieved easily on some systems.

**Comment by Shaddoh** [comment]
Not sure if you see comments once it is closed. But is the create umask option able to be passed through the winfsp or is it still only through the sshfs.exe commands?

cd C:\Program Files\SSHFS-Win\bin
set CYGFUSE=WinFsp
set PATH=C:\Program Files\SSHFS-Win\bin
sshfs.exe -f -o uid=-1,gid=-1,create_umask=000 username@server: z:

I am hoping I could use net use commands instead of the above. Then I wont be asked for password everytime. 

Thank you

**Comment by billziss-gh** [comment]
@Shaddoh unfortunately there is no way to pass this flag directly via `net use`.

**Comment by cyberhaus** [comment]
Hi i'm having trouble getting the create_umask and umask to take effect using any umask setting. 
when i create a new file i'm getting permissions 775 being set.

This is my bat script
set PATH=C:\Program Files\SSHFS-Win\bin
set CYGFUSE=WinFsp
sshfs.exe -f -o idmap=user,create_umask=002,umask=002 user@hostname: z:

**Comment by bjquinn** [comment]
Hey, I was wondering if there was any further development on this issue?  It would be really nice to be able to pass uid/gid/create_umask via net use.  That would allow me to use this in a lot of situations where it currently doesn't make sense.  Having to type the password in every time is a non starter for a lot of people.

**Comment by martok** [comment]
For posterity's sake (this issue is quite high up in Google results for sshfs-win umask confusion):

The option discussed here was extended/superseded for #227 as `create_file_umask` and `create_dir_umask`. Note that they're all _masks_, not _modes_, so specify the opposite of what you want.

**Comment by bjquinn** [comment]
Thanks!  For me the missing piece of this is to be able to set those options via net use.

**Comment by anttin2020** [comment]
Hi!
I have been trying to get my SSHFS-WIN/WinFSP to get proper permission on the remote Linux system and now I get the server permissions correct (664 for file, 755 for dirs) but I have weird problem:
When I create a new file in Windows on that mounted drive (say new/text document) and then refresh the window, I get FOUR of them (New Text Document.txt, New Text Document (2).txt etc.). :o

The files are editable and work normally but why four of them? :)

But worse and maybe even more weird problem is that if I create a new file say in Notepad++ and then try to save it to the mounted drive, I get error message:
```
N:\new 3.txt
You don’t have permission to save in this location. 
Contact the administrator to obtain permission.

Would you like to save in the Documents folder instead?
```
When I say No to that, the file is created but it is empty. After that I can open it and edit it and save it.

This is causing big problems with e.g. VSCode Local History which tries to create history files in the current folder and because of that problem fails.

I use Sirikali and I have discussed with the author and he has helped me a lot but this is something even he could not figure out. I even tried exactly same sshfs command line as he used and still got the same problem.

My current sshfs command is (from Sirikali debug):
`"C:\Program Files\SSHFS-Win\\bin\sshfs.exe" -f --VolumePrefix=\mysshfs\"username@username.com;/home/username" "username@mysite.com:/home/username" "N:"  -o rw,fsname=sshfs@"username@mysite.com:/home/username",subtype=sshfs,create_file_umask=0111,create_dir_umask=0000,uid=-1,gid=-1,StrictHostKeyChecking=no,IdentityFile=C:/Users/username/.ssh/id_rsa,volname="username"`

The server gives umask 0002 which to me seems suitable and as I said, the files there have correct permissions, the problem is at Windows side (but may still be caused by server settings, I am no Linux pro).

The Linux system is a webhotel that is using cPanel control system so I have very limited rights to configure it (no sudo and limited commands).

Has anyone any ideas how to fix this or at least what is causing this? :)
Or any comments?

Thank you very much!
