### ISSUE TITLE
Shared network path failed

### ISSUE THREAD

**Issue by yanrk** [billziss-gh/winfsp#148]
When I map a network path directly through CMD, I can map it successfully, but I can't share the mapped drive disk.

Then I open a new CMD through PsExec:   
( C:\WINDOWS\system32> C:\Users\admin\Desktop\winfsp\winfsp-installer\PSTools\PsExec exe - I - s CMD. Exe )
But it failed when mapping a network path:   
( C:\WINDOWS\system32> C:\Users\admin\Desktop/winfsp\passthrough\passthrough-x64. Exe -p \\10.60.196.141\munu_server\node_statistics -m X: )
The error message is as follows.
cannot create file system
The service passthrough has failed to start (Status=c0000022).

**Comment by billziss-gh** [comment]
Some general comments:

- If you are creating a "network" drive (e.g. by using the `-u VolumePrefix` switch), the network drive cannot also be shared using Windows networking. This is explicitly disallowed by Windows.

- If you are creating a "disk" drive (i.e. no `-u VolumePrefix` switch) then this drive can be shared provided it is a "global" drive. Drives are created by default in a local user name space, and only the SYSTEM (LocalSystem) account can create drives visible to everyone.

By using `psexec` or the WinFsp.Launcher you run your file system under the SYSTEM account and can therefore create global drives. This means that your drives can be shared, with [`NetShareAdd`](https://msdn.microsoft.com/en-us/library/windows/desktop/bb525384(v=vs.85).aspx) or `net share` from the command line, etc.

In your case you are also trying to use the passthrough file system over a file share `\\10.60.196.141\munu_server\node_statistics`. Passthrough is unable to access this location and responds with `STATUS_ACCESS_DENIED` (`Status=c0000022`).

The reason for this has nothing to do with passthrough or WinFsp. Passthrough simply tries to open the share and it fails because SYSTEM lacks permissions. Normally the SYSTEM account will try to access the file share using the local computer credentials. This may work if you are in a domain and you allow access to the share for the particular computer, but cannot work (I think) if you are not in a domain.

Another perhaps better method is possible with the latest beta of WinFsp. It is now possible to launch a file system using the WinFsp.Launcher under a specific user account. The launcher has now special [support](https://github.com/billziss-gh/winfsp/blob/v1.3B2/src/dll/fs.c#L226-L233) to help the file system create a global drive in this case. You would just have to make sure that the particular user has access to the share (which is possible whether you have a domain or not).

**Comment by yanrk** [comment]
I try it with newest winfsp still not work，but dokany work well，I know winfsp is faster，but support for the resharing of network paths is fundamental to our needs.

**Comment by billziss-gh** [comment]
Unless I misunderstand the problem, this has to do with the account that you are using to run passthrough. Any software that runs under the SYSTEM account is unable to access shares on other computers under normal circumstances.

In any case if you have solved your problem in a different way, perhaps we can close this?
