### ISSUE TITLE
WinFSP requires at least Windows 8

### ISSUE THREAD

**Issue by carlreinke** [billziss-gh/winfsp#15]
The launcher uses [`GetOverlappedResultEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/hh448542%28v=vs.85%29.aspx), which is not available before Windows 8.

**Comment by billziss-gh** [comment]
Great catch, thanks!

Two points here:

* The use of `GetOverlappedResultEx` was an oversight, especially because it could be replaced with `WaitForSingleObjectEx`. I am currently in the midst of implementing reparse points, but will look into this when I get time.

* The intent is to support Windows 7, but unfortunately the code is not tested on Windows 7 currently. This is primarily because I do not not know of a good CI solution that supports Windows 7. A CI solution that supports any MS-supported version of Windows would be ideal. [I should probably file an issue with AppVeyor on this.]

**Comment by billziss-gh** [comment]
Commits 0e2f46d - 35b9cb1 should resolve this issue. The installer installs correctly on Win7 32-bit and the WinFsp test suite passes. I will follow up with news of a public release soon.

**Comment by billziss-gh** [comment]
The latest WinFsp public release (v0.15) resolves this issue. Please test and let me know.

**Comment by carlreinke** [comment]
Testing on Windows 7 Enterprise (Build 7601, x64).  Launcher is working.  I am able to map `\\memfs64\share` and `\\memfs32\share`.
