### ISSUE TITLE
Symlinks to absolute path

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#153]
Hi,

Using the FUSE API for Cygwin v1.2POST1 / 2017.2 in [EncFS port](https://github.com/billziss-gh/winfsp/issues/152), I spent many hours trying to make Cygwin absolute symlinks to correctly show-up though FUSE EncFS.

Here is what I get :

![screen shot 2018-03-24 at 18 44 47](https://user-images.githubusercontent.com/6764151/37867106-25ba4744-2f94-11e8-95a9-7b47bca3925c.png)

Then I discovered and tested `-o rellinks` :

![screen shot 2018-03-24 at 18 44 47](https://user-images.githubusercontent.com/6764151/37867113-3803f1fc-2f94-11e8-998c-a141e53463ba.png)

And going through the code, [I found this, fuse_intf.c#L511](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/src/dll/fuse/fuse_intf.c#L511) :
`/* we do not support absolute paths without the rellinks option */`

Why can't we support absolute symlinks without `-o rellinks` ?

Many thanks 👍

**Comment by billziss-gh** [comment]
(I should have recorded more of my thoughts when I made that comment. It is hard to recall all the details.)

Symbolic links in Windows (the file system kind, not the NTOS object manager kind) come in 3 different flavors:

- Absolute cross-device symlinks (i.e. from one drive to another).
- Device-relative symlinks (i.e. symlinks that are absolute within the drive, but not across drives).
- Relative symlinks.

It is not obvious to what an absolute POSIX symlink should map when on Windows.

- It cannot map to a cross-device symlink, because that is a Windows-only concept.
- It cannot cleanly map to a device-relative symlink, b. Windows file systems are usually mounted as drives rather than on a directory, so the symlink would likely change meaning when the file system was mounted as a drive.

**Comment by billziss-gh** [comment]
(I should have recorded more of my thoughts when I made that comment. It is hard to recall all the details.)

Symbolic links in Windows (the file system kind, not the NTOS object manager kind) come in 3 different flavors:

- Absolute cross-device symlinks (i.e. from one drive to another).
- Device-relative symlinks (i.e. symlinks that are absolute within the drive, but not across drives).
- Relative symlinks.

It is not obvious to what an absolute POSIX symlink should map when on Windows.

- It cannot map to a cross-device symlink, because that is a Windows-only concept.
- It cannot cleanly map to a device-relative symlink, because this would make it relative to the root of the mounted file system rather than the overall file system root as it is the intent on POSIX.

Consider a file system mounted on `/mnt` in UNIX and a symlink in it that points to `/mnt/data`. Absolute symlinks in POSIX are interpreted from `/`, so this points to the `/data` subdirectory of our file system.

On Windows there is no overall file system root (no `\`). If we choose to encode `/mnt/data` as a device-relative symlink, we end up pointing to the `\mnt\data` directory in our file system. Even if we mount the file system at `C:\mnt` the directory this resolves to is `C:\mnt\mnt\data` and not the desired `C:\mnt\data`.

**Comment by billziss-gh** [comment]
I posted and half-written comment and closed this by accident. I deleted the half-written comment and reopened the issue.

**Comment by billziss-gh** [comment]
Let us consider your proposal of `-o rellinks=/cygdrive/x`.

Suppose that at some point there is a symbolic link `foo` -> `/cygdrive/x/bar` on the FUSE file system (`/cygdrive/x`). An application opens `foo`. Here is what happens next:

- `NtCreateFile("\foo")`. An internal NT API that the application calls (directly or indirectly).
- `IRP_MJ_CREATE`: The WinFsp FSD receives a request to "create" (open) a file object for `\foo`.
- `FspFileSystemCreate`: The WinFsp DLL receives the request in user-mode. It queries the FUSE file system using `getattr('/foo')` and finds out that this is a symlink. It reads the symlink using `readdir`. It converts the received symlink (`/cygdrive/x/bar`) to a Windows reparse point and returns it to the FSD together with a special status code `STATUS_REPARSE`. (This is currently disallowed without the `-o rellinks` option.)
- The FSD sees the `STATUS_REPARSE` and rewrites the file path from `\foo` to `\cygdrive\x\bar` and then resends the request to user mode. Inevitably this will fail, because `\cygdrive\x` is not a real directory in the file system.

The problem here is that the `/cygdrive` prefix does not mean anything outside Cygwin. The FSD does not know how to resolve it.

There are ways that some of this could be made to work, but it raises the question. Why is `-o rellinks` not good enough?

The `-o rellinks` option "promises" that absolute symlinks found in the file system really point inside the file system. So if you see a `/cygdrive/x` symlink in your file system, there is supposed to be a file called `/cygdrive/x` in that file system.

The switch works well for most purposes, except for programs that deeply care that they can retrieve using `readlink` what they put there using `symlink`. The only programs I have seen that really care are usually file system test suites. Do you have any other examples?

**Comment by benrubson** [comment]
Bill, thank you for your detailed comment once again :+1:

Note that I just "discovered" that `-o rellinks` is a FUSE option, not a specific WinFsp option. I never used it before. So of course my proposal above to modify this option is pointless... Sorry for this...

I have no other example of programs which would care about absolute symlink consistency, but perhaps some programs running in Cygwin only.

I made some further testing, as shown in the picture below :

![screen shot 2018-03-27 at 16 10 48](https://user-images.githubusercontent.com/6764151/37975504-c88aa99e-31df-11e8-92d3-dd6573ba3eb8.png)

So here we have a FUSE FS (EncFS) mounted on `X:` (`/cygdrive/x`) which gives a decrypted view of what is crypted on `C:` (`/cygdrive/c`).
`-o rellinks` is on.

We have a file `ben.txt` and `rellink.txt` pointing to `/ben.txt`, which has been translated to `/cygdrive/c/ben.txt`.
I'm still surprised it is not translated to `/cygdrive/x/ben.txt` instead, as we work on `x`, not on `c`.
I'm also surprised that Windows manages to correctly show (and open) `rellink.txt`, as `/cygdrive/c/ben.txt` itself does not exist (but its encrypted filename).
Cygwin however fails following / opening this link.

We also have `link.txt` pointing to `//ben.txt`.
Sounds like here `-o rellinks` does not translate this link, but at least allows WinFsp to display it, this is what I was trying to do.
And here, Windows also correctly displays (and opens) this link.

So tu sum-up these "findings" :
- I would say `-o rellinks` does not point to the correct drive ?
- what about allowing absolute links without `-o rellinks` (through a new option for example) ? Sounds like [this condition](https://github.com/billziss-gh/winfsp/blob/v1.2POST1/src/dll/fuse/fuse_intf.c#L511) would just have to be relaxed ?

Thank you again, sounds like this is quite a tricky subject !

**Comment by billziss-gh** [comment]
@benrubson can you please let me know how you create those symlinks? What command did you use? (`ln -s`, `mklink`, etc.)

**Comment by benrubson** [comment]
Sorry, I should have began with this... I'm more a UNIX user than a Windows one, so certainly forgot some basis things...
So links are created with `ln -s` on Cygwin.
FUSE FS (EncFS in this example) sees them as links (`S_ISLNK(stat->st_mode)`), and then shows them as links. If their target is absolute, the links will not show-up if `-o rellinks` is not used.
So I think they could, showing their original/raw target.
And sounds like (but I may be wrong as I don't master everything here), that `-o rellinks`, when used, does not point to the correct device (for instance it points to `/cygdrive/c` instead of `/cygdrive/x`).

**Comment by billziss-gh** [comment]
Ok, I suspect that some of what you are seeing has to do with the mismatch of Cygwin symlinks (which are POSIX compatible) and Windows symlinks (which are not).

Suppose that you create a Cygwin symlink with `ln -s /cygdrive/x/foo bar`. Cygwin knows how to interpret this, but Windows and WinFsp do not. They simply assume that `/cygdrive/x/foo` means a file `foo` inside a directory `x` inside a directory `cygdrive` under the mounted file system root; they do not give any special interpretation to `/cygdrive/x`.

I do not think that EncFS can be used with absolute Cygwin symlinks currently. The `-o rellinks` switch cannot help, **because it includes the promise that all absolute symlinks point inside the file system** (i.e. the file system acts as the overall system root) and that is not the case with `/cygdrive/x`.

It could be argued that we should change WinFsp-FUSE to allow some limited absolute symlinks and allow paths such as `/cygdrive/x` and `/proc/cygdrive/x` when on Cygwin. I believe it is possible to use Cygwin API's to determine the correct `cygdrive` prefix and strip if it is there. But this is a non-trivial change and IMO rather low priority.

**Comment by benrubson** [comment]
Thank you Bill.
I agree this is clearly not a priority.
Goal was also to understand how it work / where the "issue" comes from.
Thanks for all, closing this for now until this is really needed.
Thx 👍

**Comment by benrubson** [comment]
For completeness, I discovered that Cygwin may handle symlinks in different ways thanks to the `winsymlinks` value of the [CYGWIN environment variable](https://cygwin.com/cygwin-ug-net/using-cygwinenv.html).
And I also found that the absolute dir pointed by `-o rellinks` depends on the active/current directory.
