### ISSUE TITLE
unlink return code not checked ?

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#157]
Hi,

Using the FUSE API for Cygwin v1.2POST1 / 2017.2 in [EncFS port](https://github.com/billziss-gh/winfsp/issues/152), I encountered the following issue.

If the filesystem is mounted in a "read-only" state, then when a file is renamed, then `EROFS` is returned, and the calling program (Windows, or Cygwin `mv`) correctly shows the error. Perfect.

However, when a file is deleted, `EROFS` is properly returned, but the file is deleted from the FUSE FS (at least Windows shows it as deleted), and the calling program (Windows, or Cygwin `rm`) returns 0.
The file is however not deleted from the underlying FS, and it shows-up again when the explorer-window is refreshed (or with a `ls` on Cygwin).
Sounds like the `unlink` return code is ignored somewhere ?

Same thing when the FS is read-write, but the underlying file is opened. As above, deleting the FUSE file seems to work, however the underlying file is not removed as it is in use. Here `EBUSY` is returned, but seems to be ignored.

Seems that we are also able to delete the underlying file if FUSE file is in use, but here I'm not sure we can do something.

Thank you 👍 

Ben

**Comment by billziss-gh** [comment]
I think there may be two issues here.

1. WinFsp does not currently properly support read-only file systems (eee issue #84). A file system can be marked read-only on Windows, but that does not stop the OS from sending it it read-write requests. The FSD (File System Driver) is supposed to filter those requests out, but WinFsp does not currently do so.

2. The `unlink`/`rmdir` operations are complicated on Windows. Simplifying a bit, they consist of the following operations:
    - `Open`
    - `CanDelete`
    - `Cleanup`
    - `Close`

The file system is supposed to check whether file deletion is possible in `CanDelete`. If the file system says yes (does not return an error) during `CanDelete`, then it is **committed** to delete the file during `Cleanup`. This is because the `Cleanup` operation cannot return an error to the OS.

The WinFsp-FUSE layer does a delete access check during `Open`, checks whether a directory is empty during `CanDelete` and actually removes the file or directory during `Cleanup`. But recall that it is not possible to report an error code from `Cleanup`.

**Comment by fsgeek** [comment]
Bill: not to directly hijack your thread here, but I would note that they
added an alternative deletion sequence at some point (Windows 8?  8.1?  I
don't recall exactly which version.)   They now do an Open with
*FILE_DELETE_ON_CLOSE* and then close the file.

The semantics of *FILE_DELETE_ON_CLOSE *are truly ugly.  I found that NTFS
and FAT at one point didn't even agree on them; I logged the bug against
FAT, Microsoft chose to change the semantics of NTFS.  You can see the
effect of this in the FastFat source code.

*FILE_DELETE_ON_CLOSE *sets a bit in the Cache Control Block (CCB which is
normally FileObject->FsContext).  When the file is closed (IRP_MJ_CLEANUP)
that bit is promoted to the File Control Block.   I mention that because
the IRP_MJ_SET_INFORMATION (DispositionInformation) allows clearing this
bit (the FCB bit) but does not know about all the CCB bits. This leads to
very peculiar Windows semantics where you can delete a file, but if I have
a handle to it still I can clear that intent bit.

It likely isn't directly related to the extant situation, but I did want to
mention the open option technique they seem to be using these days (it is
one less call into the file system, so apparently it mattered to someone's
performance.)

**Comment by billziss-gh** [comment]
Tony, thanks for your always useful insights.

I am aware of the `FILE_DELETE_ON_CLOSE` bit and handle it in WinFsp (I believe in a way that is more or less equivalent to how FastFat does it).

I have also observed that primary Windows apps like Explorer almost always use `FILE_DELETE_ON_CLOSE` when deleting files  (not directories) in recent versions of the OS. I did not mention it above as to keep the discussion simpler.

Unfortunately in both the `FILE_DELETE_ON_CLOSE` case and in the `DispositionInformation` case it is not possible to fail the deletion **and** report the error in `IRP_MJ_CLEANUP`. I believe the following is (or was) possible in NTFS: open a directory with `FILE_DELETE_ON_CLOSE` and have the directory remain after cleanup (if the directory is not empty) without any errors reported.

**Comment by fsgeek** [comment]
I agree - this is one of the murky areas of semantics.  You _can_ fail
*IRP_MJ_CLOSE
*but of course it is pointless, since the error gets ignored.  Even if it
propagated back to *ZwClose*, how many programmers do you know that look at
the return status of close?

The key to reporting the failure is to look for Delete access.  if they
don't request that, they can't delete the file.  Of course the ugliest of
deletions is the side-effect from a rename or hard link operation, which
can specify the target should be deleted if it exists.  Ironically, this is
why the SMB server impersonates in *IRP_MJ_CREATE* (open) and
*IRP_MJ_SET_INFORMATION*, since the file system may need to make a security
decision down this peculiar path.

Interesting trick on NTFS, I don't recall having ever tried that approach.

One benefit to the Windows model here is that it doesn't leave you with
dangling file references. In UNIX file systems, the crash semantics around
"unlinked but still-in-use files" can be quite challenging.  This is even
moreso when you involve network clients, because such clients haven't
crashed.   In prior work I've done, we actually provided a recovery window
in which those files could be reclaimed.  If not reclaimed within the lease
window, we could garbage collect them and maintain consistency.

**Comment by benrubson** [comment]
Thank you Bill & Tony :+1:

> WinFsp does not currently properly support read-only file systems (eee issue #84).

Well, the FS (EncFS in my example) is not specifically set read-only (by `FSP_FUSE_CAP_READ_ONLY`), but as proposed in #15, write requests (write, unlink, rename...) are rejected with `EROFS`.

> The WinFsp-FUSE layer does a delete access check during `Open`, checks whether a directory is empty during `CanDelete` and actually removes the file or directory during `Cleanup`. But recall that it is not possible to report an error code from `Cleanup`.

The check during `Open` is certainly based on a file's attributes check ?
So sounds like there's no possibility for the FUSE FS to return `EROFS` here.
Or perhaps `Open` is done with `O_WRONLY` or `O_RDWR`,  however here it should then receive `EROFS`.

> The key to reporting the failure is to look for Delete access.

Where would you do this ?

**Comment by billziss-gh** [comment]
In order to have a file deleted it must be opened with `DELETE` access during the `CreateFileW` or `NtCreateFile` call. Unfortunately WinFsp and WinFsp-FUSE do not currently check this flag for the purpose of implementing a read-only file system (again see #84).

They do however check it for the purpose of generic access control. I suppose then one way around this problem would be to always report files as read-only during `getattr` (`st_mode &= ~0444`).

**Comment by benrubson** [comment]
Thank you Bill for the workaround proposal 👍 
> `st_mode &= ~0444`

You probably meant `st_mode &= ~0222` :)

I then did further testing, and unfortunately, it did not help.
Files are correctly seen without write permission, but behavior is still the one described in the first post.

However, as per #84, I went through the code to see how to set `ReadOnlyVolume` to give it try.
I ended up with :
`conn->want |= (conn->capable & FSP_FUSE_CAP_READ_ONLY);`

And this helped a little :
Cygwin `rm` does properly return _Read-only file system_.
No change however with Windows explorer.

Here are the rights seen by Win explorer with both `st_mode &= ~0222` and `FSP_FUSE_CAP_READ_ONLY` :

![screen shot 2018-04-05 at 23 50 52](https://user-images.githubusercontent.com/6764151/38394144-9e1fa7fe-392d-11e8-9316-aa0306edc0e1.png)

![screen shot 2018-04-05 at 23 50 09](https://user-images.githubusercontent.com/6764151/38394149-a2257fa4-392d-11e8-9ac5-a7f51a8e6fa4.png)

Maybe the culprit could be the `Delete` bit.

Anyway, closing this in favour of #84.

Many thanks 👍
