### ISSUE TITLE
Some performance tests

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#160]
Hi,

I did some performance tests, and found it could perhaps be interesting to share the results.
Here they are then. They use WinFsp 2017.2 / v1.2POST1.

I focused on `readdir()`, to give an idea about the overhead produced while browsing files.

I used Cygwin environment to run the tests.
I simply created a huge directory containing 10.000 (sub)directories and 1.000.000 files.
And then rsynced this huge directory to an empty one, in dry test mode (so that only read IOs are done).

First, let's add the 2 following Cygwin mount options to `/etc/fstab` :
[`noacl,notexec`](https://cygwin.com/cygwin-ug-net/using.html#mount-table)
Which by default gives :
`none /cygdrive cygdrive binary,posix=0,user,noacl,notexec 0 0`
And let's restart Cygwin.
_Without `exec`/ `notexec`, Cygwin reads the first bytes of every file._
_With `acl`, there is an additional `open()` of every file._
_There may still be a remaining `open()` to every file (see my second post below)._

Let's then create the huge directory once for all :
```
for j in $(seq 1 200)
do
  mkdir -p /cygdrive/c/my_huge_dir/1/$j
  for k in $(seq 1 50)
  do
    touch /cygdrive/c/my_huge_dir/1/$j/$k
  done
done
echo 1 done
for i in $(seq 2 100)
do
  cp -a /cygdrive/c/my_huge_dir/1 /cygdrive/c/my_huge_dir/$i
  echo $i done
done
```

Then, here is the rsync command launched to browse all files :
`time rsync -an /cygdrive/x/my_huge_dir .`
Of course test has to be done several times to be sure to get consistent results (they were).
Fuse tests use `-oattr_timeout=0.1 -oFileInfoTimeout=100`, thus subsequent `getattr` go to cache.

And here are the results :

Configuration | Duration
--------------|---------
Raw filesystem (`cygdrive/c/my_huge_dir`) | 0'55''
passthrough-fuse using Cygwin GCC + WinFsp DLL | 4'39''
passthrough-fuse using Cygwin GCC + CYGFUSE | 4'39''
passthrough-fuse using Visual Studio | 4'58''
passthrough (.c) using Visual Studio | 4'05''

I am a little bit surprised by the results, perhaps I would have expected the overhead to be less important, but I may be wrong.
What seems even more strange is the _passthrough-fuse using Visual Studio_ test, which is supposed to use `READDIR_PLUS`, but which is slower than the other _passthrough-fuse_ tests without.

I just noted that there is also another performance ongoing discussion on [WinFsp Google Group](https://groups.google.com/forum/#!topic/winfsp/9KZUd7Eq3n0).

Hope this could help,  thanks !

Ben

**Comment by benrubson** [comment]
Bill, thank you very much for your answer (even during vacation !) 👍
Really glad :)

`-oattr_timeout=0.1 -oFileInfoTimeout=100` is just here to make sure a burst of related `getattr` calls on the same file will come from the cache, but a later one will get refreshed. In my tests, a 1 second cache did not improve performance, even a 10ms one was enough. Of course no cache made it worst.

Here, no IO is done, only `readdir` and `getattr` calls (`FileInfoTimeout=-1` would then not help).
This is the kind of workload done while browsing a files' tree. For example rsync does this comparing local and remote files' list to decide what should be synced.

Following is what `rsync -an /cygdrive/x/smalldir .` produces on FUSE FS side, for instance EncFS.
Note that `ls -l /cygdrive/x/smalldir` produces exactly the same output.
This should help us to accurately understand their IO pattern.

```
getattr : /cygdrive/c/
getattr : /cygdrive/c/
statfs  : /cygdrive/c
getattr : /cygdrive/c/
getattr : /cygdrive/c/
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir

readdir : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir/file2
getattr : /cygdrive/c/smalldir/file1
getattr : /cygdrive/c/
getattr : /cygdrive/c/smalldir

getattr : /cygdrive/c/smalldir/file1
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir/file1
open    : /cygdrive/c/smalldir/file1, flags 0
flush   : /cygdrive/c/smalldir/file1

getattr : /cygdrive/c/smalldir/file2
getattr : /cygdrive/c/smalldir
getattr : /cygdrive/c/smalldir/file2
open    : /cygdrive/c/smalldir/file2, flags 0
flush   : /cygdrive/c/smalldir/file2
```

There are many `getattr` calls made on every item, and of course cache helps here.
As stated in my first post, there is an aditional `open` call (and thus a `flush / close` call) for every file.
I asked why [here](https://cygwin.com/ml/cygwin-developers/2018-04/msg00017.html) and sounds like [it could be avoided](https://cygwin.com/ml/cygwin-developers/2018-04/msg00020.html), as of course it has a clear performance impact.

Many thanks again !

**Comment by billziss-gh** [comment]
I read the relevant Cygwin thread. I agree with your assessment that the extraneous `NtCreateFile` could be avoided.

From the Cygwin list:

>>>Corinna, thank you very much for your answer.
>>>What info would be missing without opening the file ?
>>
>>uid, gid, number of links.
>
>If we use "noacl" mount option, I think uid and gid do not really make sense and could be forced to some default value ?
>Number of links should not be critical too.
>Thus gathering files' information without opening them could be possible.

On the issue of `nlink` it is easy to `NtQueryVolumeInformationFile` for `FileFsAttributeInformation` and find out that `FILE_SUPPORTS_HARD_LINKS` is missing. Thus it can be safely assumed that `nlink==1` for files and many file systems do not support a correct value for directories (e.g. see the `-noleaf` option for `find`).

>The answer here is that your FS should handle the open call differently
depending on the access mask.  The NtCreateFile call in symlink_info::check
opens the file with READ_CONTROL | FILE_READ_ATTRIBUTES | FILE_READ_EA
only.  All these access flags only request *meta* info, not actual data
from the data stream of the file.  In other words, a Windows open call
without FILE_READ_DATA/FILE_WRITE_DATA and related flags does not
actually have to open the file at all in the FS driver.   It only has to
provide metadata subsequently, an operation which you usally can have at
much lower cost if the remote FS is running on a POSIX OS:
>
>- NtCreateFile called with only metadata access flags does not have to
  open the file.
>
>- Make sure to ignore the EaBuffer and EaLength parameter, rather than
  to return a failure (this avoids YA NtOpenFile call).
>
>- Just call stat/statvfs on the remote file as required to fulfill
  subsequent NtQueryVolumeInformationFile and NtQueryInformationFile
  calls.

I do not fully agree with what Corinna is saying here. An `NtCreateFile` that succeeds will **always** open the file, regardless of the access mask. Consider, for example, a network file system; at the very least it will have to "stat" the file which may mean a network request to discover its metadata.

What Corinna is hinting at here, is that often an `NtCreateFile` can be satisfied from cache. Unfortunately this is not the case in WinFsp. Although there is a "FileInfo" cache and a "DirInfo" cache, an `Open` operation is **always** forwarded to user mode. This is because in the WinFsp design access checks are always performed in user mode. This is non-trivial to change (and would be a dangerous change to make IMO).
