### ISSUE TITLE
install Winfsp toghether with other system using WIX TOOLSET

### ISSUE THREAD

**Issue by ricardo-s-mendes** [billziss-gh/winfsp#172]
Hello,

I want to fully install Winfsp together with my software. I created the installer using WiX toolset.

Any ideas on how can i do that?

Is it just add the .dll files of Winfsp? I guess it should be more complicated.

Thanks in advance

**Comment by billziss-gh** [comment]
My recommendation would be to bundle the WinFsp installer into your installation and install it during your product's installation process. You can probably use [this process](http://wixtoolset.org/documentation/manual/v3/bundle/). (Disclaimer: I have not used this process myself.)

What you want to do is possible to do under the commercial license. However it is technically hard to get right, because you would also have to make sure that "the modified binary images do not interfere in any way with the WinFsp binary images as released by the Licensor, when both are installed on the same machine". For this reason I would not recommend it.

**Comment by billziss-gh** [comment]
I am closing this as it looks like the question has been answered. Please reopen if you believe otherwise.
