### ISSUE TITLE
FUSE rename call out of order

### ISSUE THREAD

**Issue by earonesty** [billziss-gh/winfsp#175]
## Bug Report

With the latest release, it is currently possible to receive a rename() call for a parent directory in fuse while a file is currently open.   

### How to Reproduce

Write a fuse program, open a file, close it then rename it's parent directory.   

Make sure multithreading is turned on.   Run the program many times.... sometimes the "rename" will occur well before the "release".  (We used the fusepy passthrough example).   

         name = Path(mount_dir) / "foo"
         with open(name / "file", "w") as f:
             f.write("yo")
             f.close()
         os.rename(name, name.with_suffix(".new"))

### Behaviors

Expected behavior... close() call is fully "blocking"... doesn't return until "release" is complete.... even when multithreaded.

### Environment

- Windows 10 
- WinFSP 1.3.18160

**Comment by billziss-gh** [comment]
@earonesty this is indeed possible and legal in Windows in general.

However there are some file systems that cannot handle this situation well. For this reason, the latest version of WinFsp includes the flag `FlushAndPurgeOnCleanup`, which instructs the WinFsp FSD to ask the OS to close files as soon as possible. This flag is on by default when using FUSE, unless the command line option `-o KeepFileCache=1` flag is used. Assuming that you do not have the option `KeepFileCache` I am surprised to see you having problems here.

The only other reason that I can think of for this problem, is that WinFsp posts the `Close` / `release` call asynchronously for performance reasons, so it is perhaps conceivable to receive the `rename` before the `release`...

**Comment by earonesty** [comment]
Indeed, it is the asynchronous post call that is the problem.   I can demonstrate that this is a race condition that only rarely occurs.   It will cause exceptions in applications that quickly write/close and assume that a rename can happen right afte that.   

The horrible workaround, right now, is to catch the failure in rename, sleep, and hope that the async post happens... and then try again.

It should probably be an option that close is *not* async.   The responsibility for an efficient close should be the caller's job (i could make it async safely, for example, by allowing the rename function to query the queue).

**Comment by billziss-gh** [comment]
Are you certain that the problem is the `release` call from the previous `open`, `read`, `close` operation on the child file and not the `release` call on the parent directory from the `rename` itself?

The Windows file system works differently than POSIX. In POSIX, `rename` is a single operation that acts on the file system namespace. On Windows however `rename` is really the following operations:

- `IRP_MJ_CREATE`: Open the file.
- `IRP_MJ_SET_INFORMATION` / `FileRenameInformation`: the actual `rename` operation.
- `IRP_MJ_CLEANUP`: "Cleanup" the file.
- `IRP_MJ_CLOSE`: Close the file.

So for a `rename` that the application does, you will really receive: `open`, `rename`, `release`.

If we find that the problem is the still open child file, we may have to introduce an option to make `Close` synchronous. I note that `release` is asynchronous in other FUSE implementations, but POSIX file systems do not usually suffer from limitations with `rename` and `unlink` when files are open, which is why you may not have observed it before.

----

On Windows open files are represented internally using a `FILE_OBJECT` and are tracked using both a handle count and a reference count. When a file gets opened (`CreateFile`), the `FILE_OBJECT` is created, an `IRP_MJ_CREATE` is sent to the FSD and both the handle count and the reference count get incremented. When the handle count goes to 0 (`CloseHandle`) an `IRP_MJ_CLEANUP` is sent to the FSD, but the reference count remains. It is only when the reference count goes to 0 that the FSD receives an`IRP_MJ_CLOSE`, which signals to the FSD that the `FILE_OBJECT` is no longer in use; Windows then destroys the `FILE_OBJECT`.

WinFsp forwards most file system calls to the user mode file system, but attempts to eliminate or otherwise optimize away many of those calls; the reason is that every one of these calls may need up to 2 context switches in order to be serviced.

- WinFsp eliminates the `IRP_MJ_CLEANUP` call in many cases when the `PostCleanupWhenModifiedOnly` optimization is on. WinFsp-FUSE file systems always have this flag on.

- WinFsp posts the `IRP_MJ_CLOSE` asynchronously. In general most file system can cope with this.

Finally note that Windows may itself delay the delivery of `IRP_MJ_CLOSE` indefinitely. One of the primary reasons that it does this is caching.

**Comment by billziss-gh** [comment]
BTW, sorry for my late replies. I am on vacation and may not always be able to respond timely.

**Comment by earonesty** [comment]
Note: I'm 100% certain a) this is because of the fuse close coming after the actual close and also that b) NTFS will reportan error if you attempt to rename a file that is "in use".    Simply trying again a few times fixes the error (polling).

**Comment by earonesty** [comment]
To solve this without polling I wrote a pyntfs plugin that doesn't use FUSE and handles all the calls natively in python.   It wasn't that hard (boost python + passthrough example code), and the result is that we never have the issue.   As soon as it's stable and after some refactoring to make it pretty, I'm going to open source it.
