### ISSUE TITLE
Erroneous insufficient space error using MEMFS

### ISSUE THREAD

**Issue by carlreinke** [billziss-gh/winfsp#18]
Testing on Windows 7 Enterprise (Build 7601, x64).

Attempting to copy a large (but not unreasonably large) file to MEMFS produces an error that there is not enough space, though the error dialog shows that there should be enough space.

![screeshot](https://cloud.githubusercontent.com/assets/11667451/17259571/62676fbe-5589-11e6-97fe-b1bb2b5a99a9.png)

**Comment by billziss-gh** [comment]
This is due to how MEMFS works and not a problem with WinFsp. Basically MEMFS is a very simple example file system that stores all files in a std::map. There is a maximum size per file and a maximum number of files that can be stored on it. MEMFS reports the product of maxfiles by maxfilesize as the maximum volume size and the product of freefiles by maxfilesize as the volume free size.

Try running MEMFS from the command line and adjust sizes.

**Comment by carlreinke** [comment]
Oh, okay.  It would be handy if it were more functional for general use, but I realize it's mostly available as an example.
