### ISSUE TITLE
Add SetDispositionInfo in FSP_FILE_SYSTEM_INTERFACE

### ISSUE THREAD

**Issue by thinkport** [billziss-gh/winfsp#185]
## Question

_Please consider asking questions in the [WinFsp Google Group](https://groups.google.com/forum/#!forum/winfsp) instead. Before asking a question please also consult the [WinFsp Frequently Asked Questions](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions)._

I am using passthrough example, when I delete file on the explorer, the explorer will delete file, not move to recycle bin. How can I change that?

**Comment by thinkport** [comment]
explorer delete behavor:

1. CreateFile
2. SetDispositionInformationFile(Delete:true)
3. SetDispositionInformationFile(Delete:false)
4. CloseFile
5. CreateFile
6. SetRenameInformationFile
7. CloseFile

Step 3 have problem, WinFSP direct return success. 


change:

`    case 13/*FileDispositionInformation*/:
        if (0 != FileSystem->Interface->GetFileInfo)
        {
            Result = FileSystem->Interface->GetFileInfo(FileSystem,
                (PVOID)ValOfFileContext(Request->Req.SetInformation), &FileInfo);
            if (NT_SUCCESS(Result) && 0 != (FileInfo.FileAttributes & FILE_ATTRIBUTE_READONLY))
            {
                Result = STATUS_CANNOT_DELETE;
                break;
            }
        }

        Result = FileSystem->Interface->CanDelete(FileSystem,
            (PVOID)ValOfFileContext(Request->Req.SetInformation),
            (PWSTR)Request->Buffer,
			Request->Req.SetInformation.Info.Disposition.Delete);
        break;`

`static NTSTATUS CanDelete(FSP_FILE_SYSTEM *FileSystem,
    PVOID FileContext, PWSTR FileName, UCHAR DeleteOnClose)
{
    HANDLE Handle = HandleFromContext(FileContext);
    FILE_DISPOSITION_INFO DispositionInfo;

    DispositionInfo.DeleteFile = DeleteOnClose;

    if (!SetFileInformationByHandle(Handle,
        FileDispositionInfo, &DispositionInfo, sizeof DispositionInfo))
        return FspNtStatusFromWin32(GetLastError());

    return STATUS_SUCCESS;
}`

**Comment by billziss-gh** [comment]
> **explorer delete behavior:**
> 
> 1. CreateFile
> 2. SetDispositionInformationFile(Delete:true)
> 3. SetDispositionInformationFile(Delete:false)
> 4. CloseFile
> 5. CreateFile
> 6. SetRenameInformationFile
> 7. CloseFile

It is true that the user mode portion of WinFsp ignores the "SetDispositionInformationFile(Delete:false)" step and returns success. However I believe that the kernel mode portion of WinFsp properly resets the file disposition flag and the Explorer recycle bin protocol that you presented above should work.

Does Explorer even attempts the behavior you described on a WinFsp drive?

- Kernel mode SetDisposition: https://github.com/billziss-gh/winfsp/blob/master/src/sys/fileinfo.c#L1174-L1175
- Kernel mode check of DeletePending flag during Cleanup: https://github.com/billziss-gh/winfsp/blob/master/src/sys/file.c#L765

**Comment by thinkport** [comment]
Yes, I mount a disk drive, but I does't delete file in the mount volume.

I have a Minifilter driver that redirect orginal file to WinFSP volume. 
**Flow: Explorer(CreateFile) -> Minfilter(Reparse) -> WinFSP -> Passthrough(Open)**
Passthrough will delete file and Explorer will alert 'file is missing'. I change that, it's work well now.

**If I delete file in the mount volume, the explorer will delete file, not move to recycle bin, and explorer don't alert 'file is missing'. Explorer doesn't perform step 3, 5, 6 ,7 **

**Comment by billziss-gh** [comment]
Am I correct in understanding that Explorer does not even attempt the `SetDisposition(false)` call?

Does the mounted drive have a `\$Recycle.Bin` directory?

**Comment by thinkport** [comment]
command look like: passthrough-x86.exe -p c:\ -m m:

![image](https://user-images.githubusercontent.com/12952910/44380197-89018880-a53c-11e8-81aa-d413b1d56181.png)

**Comment by billziss-gh** [comment]
I understand now. This is not a general WinFsp problem, but a problem with passthrough.

However the problem in passthrough happens because the WinFsp `FSP_FILE_SYSTEM_INTERFACE` only calls `CanDelete` when the disposition flag is true and does not forward the request to the file system when it is false. Because passthrough sets the disposition flag in its [`CanDelete`](https://github.com/billziss-gh/winfsp/blob/master/tst/passthrough/passthrough.c#L447-L460) implementation, the file gets deleted when it is closed even when the deletion is canceled by Explorer.

I will mark this issue as an enhancement request to add a `SetDispositionInfo` operation that overrides the existing `CanDelete` operation (i.e. if both are implemented `SetDispositionInfo` takes precedence).

In the meantime you may have some luck using the following workaround:

- Use `FspFileSystemSetOperation` to replace `FspFileSystemOpSetInformation` with your own operation.
- In the implementation of your own operation handle `case 13/*FileDispositionInformation*/` as you see fit.
- Call the original `FspFileSystemOpSetInformation` for other cases.

**Comment by billziss-gh** [comment]
@thinkport I am reopening this as I think it is a good idea to add `SetDispositionInfo` for WinFsp.

**Comment by thinkport** [comment]
My mistake. I am new here.

**Comment by billziss-gh** [comment]
Commit 24b96e7e1b91312a826d2c7a0cde88b300f7464c adds `FSP_FILE_SYSTEM_INTERFACE::SetDelete` as an alternative to `CanDelete`.

**Comment by billziss-gh** [comment]
Closing this as the changes have been merged into master.
