### ISSUE TITLE
Add information "comparing" WinFsp and Dokany

### ISSUE THREAD

**Issue by dumblob** [billziss-gh/winfsp#19]
Please add some information (e.g. to README) to understand the **technical situation** about WinFsp in comparison with Dokany.

E.g. on https://www.reddit.com/r/programming/comments/4tnaoo/winfsp_fuse_for_windows/d5irclf there is something (do not forget about the WinFsp test suite being used also by Dokany) and in the discussion https://groups.google.com/forum/#!msg/dokan/BoLxl5p_fQQ/KwsnjdiiBQAJ there is also plenty of interesting information.

**Comment by billziss-gh** [comment]
Thanks for the suggestion. I agree that such an addition would be difficult. I have avoided doing so until this moment to avoid unnecessary friction between the projects.

**Comment by billziss-gh** [comment]
I now have some performance tests, which show that WinFsp performs exceptionally well and it is 1.5x to 9-10x times faster than Dokany. WinFsp/MEMFS is also faster than NTFS (although this is an unfair comparison as NTFS is a disk file system and WinFsp/MEMFS is an in memory file system).

https://github.com/billziss-gh/winfsp/blob/master/doc/WinFsp-Performance-Testing.asciidoc

![](https://raw.githubusercontent.com/billziss-gh/winfsp/master/doc/WinFsp-Performance-Testing/file_tests.png)

![](https://raw.githubusercontent.com/billziss-gh/winfsp/master/doc/WinFsp-Performance-Testing/rdwr_tests.png)

**Comment by dumblob** [comment]
Thanks @billziss-gh, it looks promising. What are the scale units in the charts?

**Comment by dumblob** [comment]
By the way if you're into testing, a comparison bit closer to real-world usage might be worth it (e.g. running some well-known database with that database test suite).

**Comment by billziss-gh** [comment]
The x-axis represents seconds.

For the File Tests it is the time to create, open, overwrite (`CreateFile(CREATE_ALWAYS)`), list (100 times) and delete 5000 files.

For the Read/Write tests it is the time to read/write a 4MB file in 4K increments 500 times.

More details in the Performance Testing document.

Re: database testing. My intent at this point is to measure the performance of WinFsp in specific scenarios and verify that there are no gross inefficiencies, etc. I agree that in the long term it would benefit from some real world performance testing. Do you have any specific database benchmarks that you would like to see?

**Comment by dumblob** [comment]
>My intent at this point is to measure the performance of WinFsp in specific scenarios and verify that there are no gross inefficiencies, etc.

Understood.

>Do you have any specific database benchmarks that you would like to see?

At the time of writing not. But now when I'm thinking about it, I would probably try the [DBT2](https://dev.mysql.com/downloads/benchmarks.html ) MySQL benchmark and if it would get too difficult to set up (e.g. through Cygwin on the FUSE compatibility layer), then at least SQLite3 (https://github.com/JoshuaWise/sqlite-comparison might be useful).

**Comment by billziss-gh** [comment]
Thanks for the pointers, I will look into them.

**Comment by billziss-gh** [comment]
I am doing a bit of an issue cleanup and looking into this again, I think that there is now sufficient information for those wishing to make a comparison between WinFsp and Dokany.

So I am closing this, but please let me know if you think otherwise and you would like to see more information.

**Comment by samkelly** [comment]
@billziss-gh looks like some great performance -- what does t0 / t1 / tinf mean for the different winfsp versions? Also, does this mean that winfsp is faster than native NTFS!?!?

**Comment by billziss-gh** [comment]
> what does t0 / t1 / tinf mean for the different winfsp versions?

- **t0** - `FileInfoTimeout==0`
- **t1** - `FileInfoTimeout==1000` (1 second)
- **tinf** - `FileInfoTimeout=1` (no timeout, caches remain active until expired by the kernel because of memory pressure, etc.)

> does this mean that winfsp is faster than native NTFS!?!?

As I say in the document: NTFS which is a disk file system is compared against WinFsp/MEMFS which is an in-memory file system. The reason that NTFS is slower than WinFsp/MEMFS in many tests, is because disk accesses are much slower than process context switches + memcpy.

NTFS is a disk file system, but it also extensively uses caching. It caches both data and metadata and is of course highly optimized over the years. The reason that NTFS appears so fast is because of this caching and not because disk accesses are very fast.

WinFsp also uses caching and caches both data and metadata, but is of course not as highly optimized as NTFS because it has not been around that long. [In particular: WinFsp does not implement "FastIo" yet, which is a very fast path into the NTOS cache, one that does not use IRP's to satisfy I/O.]

So here are my expectations for a WinFsp file system:

- If the file system enables caching fully (`FileInfoTimeout==-1`) it will appear to have similar (but because of lack of "FastIo" slightly slower) speeds to NTFS in common (cached) Read/Write scenarios. It may even appear faster than NTFS in open/close/delete/etc. scenarios, if it is a fast file system (like MEMFS).
- If the file system enables caching of metadata only (e.g. `FileInfoTimeout==1000`) it will always be slower than NTFS in common (cached) Read/Write scenarios. It may still appear to be faster than NTFS in open/close/delete/etc. scenarios, if it is a fast file system.
- If the file system does not enable caching of metadata (e.g. `FileInfoTimeout==0`) it will most certainly be slower than NTFS in almost all scenarios. The only exceptions are non-cached Read/Writes on a fast file system, because NTFS (non-cached) disk accesses may be slower than process context switches + file system I/O.

Perhaps I should try to somehow graph these expectations. The variables would be:

- `FileInfoTimeout`: one of `0`, `-1`, `other`.
- Whether `disk-access-cost` is greater or not than `process-context-switch-cost + file-system-io-cost`.

**Comment by samkelly** [comment]
@billziss-gh thanks for the background info!
