### ISSUE TITLE
Bugcheck on "pointer" dereference that returned by IoGetTopLevelIrp()

### ISSUE THREAD

**Issue by Alex010101** [billziss-gh/winfsp#192]
MSDN writes that ETHREAD->TopLevelIrp contain pointer to IRP or FSRTL flags like FSRTL_FSP_TOP_LEVEL_IRP. But in real world it may contain any value. Most common routines analyze that IoGetTopLevelIrp() != NULL, and this say that some one in kernel mode issue request and deadlock is possible (holding locks and so on). FastFat in WDK samples dereference IoGetTopLevelIrp() only on IRP_SYNCHRONOUS_PAGING_IO. No one normal filter will set TopLevelIrp on paging IO path.
Simple solution is checking return value  of IoGetTopLevelIrp() for kernel mode space before dereference. This will work in 90% of cases, but some crazy developer can choose magic like 0xF0F0F0F0F0F0F0F0.
To reproduce this problem you can download Doctor Web Security Space 11 Antivirus https://download.drweb.ru/win/security_space/11 and run process from WinFsp volume

**Comment by billziss-gh** [comment]
@Alex010101 thanks for the bug report.

I am aware of this problem as I have seen and analyzed a crash from one of my commercial licensees. In this particular crash the problem happened because the [`IoGetTopLevelIrp`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-iogettoplevelirp) DDI returned a bogus value of `0x0000000000a5a5a5`. The crash happened in [`FspPropagateTopFlags`](https://github.com/billziss-gh/winfsp/blob/v1.2/src/sys/callbacks.c#L297).

Unfortunately a driver has to "trust" the pointers that it receives in kernel mode. I did think of putting a check to see whether the pointer is a kernel mode address, but what if next time they send `0xffffffff00a5a5a5` (as you say)? Still this may be a practical work around.

I believe that DrWeb should not be touching the `TopLevelIrp`, which is reserved for use by file systems. See [`IoSetTopLevelIrp`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-iosettoplevelirp):

> Only file systems can call IoSetTopLevelIrp. File system filters and minifilters cannot safely call this routine, because doing so can cause deadlocks.

**Comment by billziss-gh** [comment]
I have added commit c9f1c1c60d15b5a521d057e36560e269c0d2de2d in a private branch as a workaround for this problem. If it passes tests I will merge it into master.

But I still believe that WinFsp should not be receiving bogus `TopLevelIrp`'s.

**Comment by Alex010101** [comment]
Hi Bill,
Thank you! We also added workaround in Security Space 12. Now valid kernel mode address passed to IoSetTopLevelIrp instead of 0x0000000000a5a5a5. We use IoSetTopLevelIrp to signal that deadlock is possible. Filters bellow us should don't stop our requests to FS. But Security Space 11 still not fixed.

**Comment by billziss-gh** [comment]
@Alex010101 great to hear about your workaround in Security Space 12.

Am I to understand that WinFsp commit c9f1c1c60d15b5a521d057e36560e269c0d2de2d should resolve the issue with Security Space 11?

BTW, the latest commit has passed all tests and I will merge into master. I will probably be releasing a beta with the fix included later today or tomorrow.

**Comment by Alex010101** [comment]
Fix looks like that
static ULONG_PTR Magic = 0xa5a5a5a5;
IoSetTopLevelIrp(&Magic);

**Comment by billziss-gh** [comment]
This should work because `IO_TYPE_IRP == 0x00000006` and the `TopLevelIrp->Type` is a `CSHORT`.

**Comment by Alex010101** [comment]
Yep. We look at your code before it. One of Microsoft virtualization drivers also use approach with system range check.

**Comment by billziss-gh** [comment]
Fantastic. thank you Alex. Closing this as I will be releasing a beta that includes this fix shortly.

**Comment by billziss-gh** [comment]
The latest [beta](https://github.com/billziss-gh/winfsp/releases) includes the discussed fix.
