### ISSUE TITLE
Can FileContext be NULL?

### ISSUE THREAD

**Issue by alfaunits** [billziss-gh/winfsp#200]
We got a few crash dumps where FileContext is NULL during Read and Close, so just checking, before I dive into memory corruption.

P.S. We might have a stale build of the WinFSP DLL on the test machines, if that makes a difference?

**Comment by billziss-gh** [comment]
`FileContext` will never be `NULL` (unless you set it to `NULL`). It is a value that is first set in `Create`/`Open`, maintained in the kernel and sent to user mode on every access. The FSD/DLL do not change `FileContext` in any way.

One possibility is that you have changed the `UmFileContextIsUserContext2` or `UmFileContextIsFullContext` flags (in `FSP_FSCTL_VOLUME_PARAMS`), without updating your file system.

> P.S. We might have a stale build of the WinFSP DLL on the test machines, if that makes a difference?

WinFsp only supports scenarios where the FSD and DLL match versions exactly. (This is not currently enforced, but it might be in the future.)

The reason is that kernel-user mode protocol backwards compatibility is not a goal for WinFsp. In general I try to extend the kernel-user mode protocol in a backwards compatible manner, but I had to break this in a couple of occasions. (For example, you could not safely use a v1.4 DLL against a v1.0 FSD.)

**Comment by alfaunits** [comment]
Excellent catch! We "set" it to NULL (by inadvertently returning a success code, instead of an error code). Thanks!
