### ISSUE TITLE
Adobe Reader DC "Save as" Fails on Reparse Point

### ISSUE THREAD

**Issue by earonesty** [billziss-gh/winfsp#212]
## Issue "saving as" when using Adobe Reader DC

When in Adobe Reader DC (and some other adobe products), the "Save As" feature cannot save to a WinFSP mounted "passthrough" system.

This is a known and oft-reported bug in Adobe software: 

https://forums.adobe.com/thread/2312306

An analysis of the system calls seems to show that Adobe is incorrectly adding "C:\" to UNC paths.   

If that's the case, then clearly this is not WinFSP's issue, but given the popularity of Adobe, and their reluctance to fix it (reported off an on since 2003) ... it might be a good idea to add a hack.... or at least add a workaround to the documentation (if it can be handled... i'm not sure it can.).   

I'm not sure if there's anything while operating at the WinFSP level that can be done to fix this.   If not, we will just disable directory mounts and only use drive mounts.

**Comment by billziss-gh** [comment]
Can you post a complete example of what Adobe Reader does with such paths?

Although if this is not a problem specific to WinFsp I am not certain how it could it be fixed (or even if it should).

**Comment by earonesty** [comment]
Box is just telling users to "turn off" reader's "enhanced protection".  https://community.box.com/t5/Web-App-Forum/Box-Drive-Acrobat-Reader-DC-Access-Denied/td-p/37622

Maybe we'll do the same.

**Comment by earonesty** [comment]
For example:
[adobe-error-procmon.txt](https://github.com/billziss-gh/winfsp/files/2846690/adobe-error-procmon.txt)

**Comment by vxgmichel** [comment]
Hi all, I just ran into a related issue recently. 

The difference is that it also happens when trying to open and read a pdf file:

- `memfs-x64.exe -m C:\Users\User\memfs-mountpoint`
- Copy a pdf file to `C:\Users\User\memfs-mountpoint`
- Open `C:\Users\User\memfs-mountpoint\pdf.pdf` with Adobe Reader DC
- Observe the dialogue: `There was an error opening this document. Access denied`

This problem does not occur if:
- `memfsx64.exe -m R:` is used instead
- or, if the `Enable protected mode at startup` setting is unchecked

The logs also seem a bit different:

![acrobat-reader-logs](https://user-images.githubusercontent.com/7490006/70926222-05bb4e80-202d-11ea-9386-c5bdaeb0a683.png)
