### ISSUE TITLE
Add information about `-o uid=-1,gid=-1` in the FAQ

### ISSUE THREAD

**Issue by Bob590** [billziss-gh/winfsp#234]
Strange behavior using passthrough file system when creating a folder with Windows File Explorer

I have compiled the FUSE passthrough file system example and I'm mounting it to C:\disk replicating a folder always in C:
When I use Windows 10 (1809) File Explorer to create a new folder I get 4 folders created:
New Folder
New Folder(2)
New Folder(3)
New Folder(4)

If I repeat the same operation using an alternate shell (like Total Commander) or by program then the folder get created normally.

Is this my fault or I'm missing something?

I have installed winfsp-1.4.19016.msi

**Comment by billziss-gh** [comment]
Which account are you using to launch the file system? I have seen this before and it is usually a permission problem. Specifically when Explorer does not have proper permissions to create a directory, it keeps retrying a few times before it quits, which results in the `New Folder (x)` directories.

**Comment by Bob590** [comment]
I user an Admin account but UAC is enabled.
I have tried with UAC disabled. Same thing.
I have run the passthrough file system as Administrator. Same thing.
What do you suggest next?

**Comment by billziss-gh** [comment]
Do not run the pass through file system under an Administrator account. Run it under the user account that has access to the directory that you are passing through. Usually this is just your normal user account (non-elevated).

Most of these problems are because the pass through file system itself is running under an account that has no access in the underlying directories.

**Comment by Bob590** [comment]
Following your suggestion I run as normal user. No luck!
I have mounted the FS to another disk D:\disk in order to see if anything changes. No luck!
![Security](https://user-images.githubusercontent.com/46998395/58003187-87bbb700-7ae0-11e9-8511-08b3eea6e78d.png)
These are the security properties of D:\disk. As you see access is for everyone!
I don't think it is a security problem.
The odd is that if I use another method (as creating a small program that just call mkdir or using a different shell) to create a folder I have no problems.
I need however that my application allows users to create folders using File Explorer and thus I need to solve this problem.
BTW: I have placed some tracings on the file system code and I see that getattr is called a lot of times for the same path.
Thank you very much for your assistance.

**Comment by Bob590** [comment]
I have found a solution myself here:
https://github.com/billziss-gh/winfsp/issues/40

Practically I was getting that same S-1-5-0 owner of the root folder of my file system.
I was also experiencing problems on saving files in my File System.
I have also solved this problem by using command line parameters: -ouid=65792,gid=65792,umask=0

I think that this should be the default if nothing is specified on the command line. But this is of course my opinion in my application. :-)

**Comment by billziss-gh** [comment]
> I have compiled the FUSE passthrough file system example and I'm mounting it to C:\disk replicating a folder always in C:

My apologies. I missed in your original message that you were referring to the FUSE passthrough file system. I mistakenly assumed that you were referring to the native passthrough file system, which does not normally exhibit this problem (unless run under the wrong account). My answers were therefore incorrect.

FUSE file systems do indeed need a `-o uid=-1,gid=-1` or a careful implementation of `getattr`. The reason is that this is not the default is compatibility with existing FUSE file systems, many of which set `uid` and `gid` in `getattr` and do not expect the underlying FUSE layer to change their choices.

**Comment by Bob590** [comment]
Now the problem is clear. Thank you for your kindly answer.
Maybe you should mention this on the documentation (Tutorial for FUSE compatibility) so that other users will not get stuck here.
Now all is working as I expect and I can proceed with my project.

**Comment by billziss-gh** [comment]
I will leave this open with the intent to add some documentation, likely in the [FAQ](https://github.com/billziss-gh/winfsp/wiki/Frequently-Asked-Questions).

**Comment by billziss-gh** [comment]
I have now added some information about this in the FAQ. See bc03af3b2a61d9232bbbc6b9495ac1ce54f4264f.
