### ISSUE TITLE
Iozone and postmark benchmarks do not pass in Memfs

### ISSUE THREAD

**Issue by ricardo-s-mendes** [billziss-gh/winfsp#252]
Hello,

I am testing winfsp through memfs, and both iozone and postmark do not work well. In the case of iozone I never managed to get it working, while in the case of postmark it happens when I set the number of files to more than 1023.
Do you have any idea of what is happening?

iozone output:
```
$ iozone -a  
(...)
 kB  reclen    write (...)
64       4
Can not open temp file: iozone.tmp
open: No such file or directory
```

postmark output:
$ postmark
```
PostMark v1.5 : 3/27/01
pm>set number 1024
pm>run
Creating files... Error: cannot open '1024' for writing (...)
```

### Environment
- OS version and build: Windows 10 (10.0.18362 Build 18362)
- WinFsp version: 2019.2 (v1.4.19049)
- iozone (version 3.483)
- postmark (v1.5)

**Comment by billziss-gh** [comment]
Re: the postmark failure. Memfs has a [1024](https://github.com/billziss-gh/winfsp/blob/v1.5B2/tst/memfs/memfs-main.c#L49) file limit by default. Try increasing it with the `-n` switch.

**Comment by ricardo-s-mendes** [comment]
> Re: the postmark failure. Memfs has a [1024](https://github.com/billziss-gh/winfsp/blob/v1.5B2/tst/memfs/memfs-main.c#L49) file limit by default. Try increasing it with the `-n` switch.
>
The -n solved the problem. Thanks.

> Re: iozone. What command line do you use to launch memfs? I will try to reproduce.

I use: 
`memfs-x64.exe -i -n 10000 -m "C:\Users\user\memfsWinfsp"`

**Comment by billziss-gh** [comment]
According to [`man iozone`](https://linux.die.net/man/1/iozone) the `-a` switch will create files of size 512M. The MEMFS file system limits files to [16M](https://github.com/billziss-gh/winfsp/blob/v1.5B2/tst/memfs/memfs-main.c#L50) by default. Try using the `-s` switch.

**Comment by ricardo-s-mendes** [comment]
No, it goes from 64kb to 512mb files. The memfs fails right away in the beginning in the 64kb files test, and in the "write" workload.

Given this, I am pretty sure that is not the problem.

**Comment by billziss-gh** [comment]
I can confirm that this problem is happening, but only when trying to execute `iozone -a` inside an memfs mounted directory. It works correctly when memfs is mounted as a drive. I will investigate further.

**Comment by billziss-gh** [comment]
Ok, I believe that the problem lies with iozone and specifically the Cygwin version that is included in its installer. WinFsp uses junction reparse points when mounting as a directory, which old versions of Cygwin cannot understand.

![Capture](https://user-images.githubusercontent.com/15330948/65822779-f92e1380-e1fe-11e9-9355-ef736ff26219.PNG)

As can be seen the included version of Cygwin is very old (from 2012) . Old versions of Cygwin did not correctly handle junction reparse points. For example, see this message from 2017:

https://cygwin.com/ml/cygwin-developers/2017-04/msg00000.html

I believe your best bet if you want to use iozone for testing is to compile from scratch on a modern Cygwin.

**Comment by billziss-gh** [comment]
I am closing this as I believe it is resolved. Please reopen if you find otherwise.
