### ISSUE TITLE
support file on demand

### ISSUE THREAD

**Issue by landall** [billziss-gh/winfsp#259]
## Enhancement Request

if I want to support the new windows file attribure pinned and unpinned, is there a documented api to support it? I think there should be an event to trigger downloading a file or releasing disk space. And how the file api callers handle the timeout when downloading?

**Comment by billziss-gh** [comment]
These attributes are used by OneDrive and do not appear to be documented by Microsoft.

Some people have done some work to decipher their usage. The best article I could find on the subject appears to be this [German article](https://hansbrender.com/tag/unpinned/) translated to [English via Google](https://translate.google.com/translate?sl=de&tl=en&u=https%3A%2F%2Fhansbrender.com%2Ftag%2Funpinned%2F).

Because file attributes are used, I do not believe that there are any "download triggers" or similar. Likely the OneDrive client notices the file attribute change and triggers file downloads and/or evictions.

In a WinFsp user mode file system you would likely setup your [`SetBasicInfo`](https://github.com/billziss-gh/winfsp/blob/master/inc/winfsp/winfsp.h#L532) handler to handle these file attributes (e.g. by scheduling the download or eviction of the related file in accordance to the attribute change).

**Comment by landall** [comment]
thanks for your help! let me give summary.
if a file not locally(with attribure OU) set pinned(attribute P), start downloading asynchronously, triggered by SetBasicInfo.
if a file not locally(with attribure OU) is opened, Windows will remove the attrib U, keep O there, start downloading with blocking the api's return, triggered by SetBasicInfo.

**Comment by landall** [comment]
After it is downloaded, attribute O is removed, I don't know if it is done by Onedrive or Windows. I guess it is done by Onedrive.

**Comment by billziss-gh** [comment]
I am closing this as I do not find anything actionable on the WinFsp side. Please reopen if you disagree.
