### ISSUE TITLE
Trojan:Win32/Detplock found in Windows Defender scan for chocolaty nuget package

### ISSUE THREAD

**Issue by Arcyne** [billziss-gh/winfsp#281]
## Bug Report

Trojan:Win32/Detplock
Windows defender was irritated and quarantined your nuget package when I tried to do a choco update.
\winfsp.1.6.20027.nupkg.tmp was the file it scanned but I have deen the non *.tmp nupkg marked as well.

**Comment by Arcyne** [comment]
Note: I also submitted the latest winfsp-1.7.20038.msi to the windows defender malware-no-malware submission endpoint so that hopefully you don't get marked as malware with every new release.

winfsp-1.7.20038.msi
Submission ID: 594ae7d3-f7e0-40da-bd44-f8793427aec0

**Comment by billziss-gh** [comment]
This was reported in #277 and fixed by Microsoft. Is this still an issue?

Please make sure you have the latest "threat definitions" installed and try again.

> Note: I also submitted the latest winfsp-1.7.20038.msi to the windows defender malware-no-malware submission endpoint so that hopefully you don't get marked as malware with every new release.

Thank you.

I had to submit the same file myself yesterday and Microsoft fixed it in #278.

**Comment by billziss-gh** [comment]
Every time an AntiVirus product flags the WinFsp software as containing malware, it negatively affects the user base of the software and erodes user trust in it. I think it could be argued that it is a form of defamation and that it harms the reputation of the software as well as my own.

The worst part about this is that I cannot be proactive and must be reactive about the problem. In all cases so far, VirusTotal gave the software a clean bill of health at the time of release, only for an AntiVirus product to flag the software as malware a few days after release. My only recourse at that point is to submit the software as a false positive when a user reports the problem.

To make matters worse some AntiVirus products seem to be wrappers of others or otherwise share malware information. The result is that once one product flags WinFsp as malware, others begin to flag it as well. It is practically impossible to follow up with all these AntiVirus vendors and have the software removed.

I am not sure what needs to be done here, but this is now an annoying enough problem that I will have to eventually address it somehow.

**Comment by billziss-gh** [comment]
@Arcyne I can confirm that with latest Windows Defender "threat definition version" (`1.309.1130.0`) neither the `winfsp-1.6.20027.msi` nor the `winfsp-1.7.20038.msi` files are flagged as malware.

Please confirm.

**Comment by billziss-gh** [comment]
@Arcyne I am closing this as I believe that the latest Windows Defender "threat definitions" no longer identify winfsp as malware. Please reopen if you find otherwise.
