### ISSUE TITLE
Missing initializer for member ‘sigaction::sa_mask’

### ISSUE THREAD

**Issue by benrubson** [billziss-gh/winfsp#287]
Hi Bill,

With WinFsp 2020 / 1.6, with FUSE Cygwin API, I get the following warning :
```
/usr/include/fuse/winfsp_fuse.h: In function ‘int fsp_fuse_set_signal_handlers(void*)’:
/usr/include/fuse/winfsp_fuse.h:363:41: warning: missing initializer for member ‘sigaction::sa_mask’ [-Wmissing-field-initializers]
  363 |     struct sigaction oldsa, newsa = { 0 };
      |        
```

Could it be possible to mute it ?

Many thanks 👍 

Ben

**Comment by billziss-gh** [comment]
- Which compiler and version?
- Which language (C or C++)?
- The initialization looks correct to me. What am I missing here?
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61489
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36750

**Comment by benrubson** [comment]
Sorry for my late answer, I took time to perform further testing.
So language in C++.
Compiler is GNU CPP, I tested versions 9.2.0, 7.4.0 and 7.3.0.
Same warning triggering on all.

Perhaps we could workaround this assigning every concerned element individually ?

Many thanks 👍

**Comment by billziss-gh** [comment]
IMO this is a spurious compiler warning.

The code is valid and the alternative of listing all fields is worse because `struct sigaction` does not have the same fields on all platforms (granted we are only targeting Cygwin here, but the principle stands).

If am inclined to use [`#pragma GCC`](https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html) to disable the warning. We might have to put this in a GCC-only conditional to avoid other compilers complaining about [unknown pragmas](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4068) (in the unlikely event they will be ever ported to Cygwin).

(We could also `memset` the variable to `0`, but I think I prefer the `#pragma`.)

As you probably can guess by now I am not a big fan of modern compiler warnings. 😃

**Comment by benrubson** [comment]
I just tested the following `#pragma`, and yes, it works as intended :
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
struct sigaction oldsa, newsa = { 0 };
#pragma GCC diagnostic pop
```
`memset` is rather nice too, as you then don't have a specific case / an exception, but a global solution*, but up to you, both will be perfect 👍

(*) if we can call this a solution, as the issue I agree seems to be a compiler issue.

**Comment by billziss-gh** [comment]
Do you want to send either this or the `memset` method as PR? Your choice.

**Comment by billziss-gh** [comment]
Actually `memset` is probably preferred to avoid checking for GCC using `#ifdef`, etc.

**Comment by benrubson** [comment]
I think so too yes.
```
struct sigaction oldsa, newsa;
memset(oldsa, 0, sizeof(sigaction));
memset(newsa, 0, sizeof(sigaction));
```
As simple as that ?

**Comment by billziss-gh** [comment]
```C
memset(&newsa, 0, sizeof newsa);
```

- `&` required for address-of `newsa`
- `sizeof(sigaction)` would only work for C++. C needs `sizeof(struct sigaction)`. Or `sizeof newsa` is even easier.
- `oldsa` does not need to be initialized (it was not before).

**Comment by benrubson** [comment]
See #288. Many thanks Bill 👍

**Comment by billziss-gh** [comment]
Actually thank you for the PR :)

**Comment by benrubson** [comment]
You're welcome, many thanks for your time !
