### ISSUE TITLE
Support cygwin mount point paths (at least) in cygfuse layer 

### ISSUE THREAD

**Issue by riedel** [billziss-gh/winfsp#29]
It would be great if cygwin_conv_path was called if the path is unsupported by winfsp and then a check is done again.  

This would be a great compatibility feature as it seems a common thing e.g. for all the python fuse stuff to call sth like:  `self.fuse_args.mountpoint = os.path.realpath(a.pop())`. Otherwise a lot of patching is needed (e.g. in python-fuse or py9p)

I am not sure if it actually makes sense or breaks anything to put that into the cygfuse shim.

**Comment by billziss-gh** [comment]
I agree. This is something that should be added/fixed in cygfuse.

I have concentrated all my recent energy in releasing WinFsp RC1 (which should become available Real Soon Now), but once I am done I will look into this some more.

BTW, this will be probably be fixed at the [cygfuse](https://github.com/mgeisert/cygfuse) project rather than here as I no longer maintain cygfuse with WinFsp.

**Comment by billziss-gh** [comment]
Commit 86025aa30b6505235e259ac8ce9c2fc756ac1b91 resolves this.

This fix is within WinFsp and its FUSE headers, so it will apply to all Cygwin programs that use WinFsp directly or through the cygfuse package that is part of WinFsp ([opt/cygfuse](https://github.com/billziss-gh/winfsp/tree/master/opt/cygfuse)). It is not currently part of the separate [cygfuse](https://github.com/mgeisert/cygfuse) project.
