### ISSUE TITLE
The local device name is already in use

### ISSUE THREAD

**Issue by sdimovv** [billziss-gh/winfsp#293]
This happens quite often when I am browsing directories/accessing files in my SFTP share.
Not sure what the reason is. My internet connection is stable and fast. I also have a WebDAV share which does not experience such problems. Furthermore, I have a linux machine connected to the same network as my windows one and accessing the same SFTP share which also does not experience such problems.

Is that a bug or am I not setting up something correctly?

EDIT: I am using the latest versions of WinFsp and sshfs-Win.

![image](https://user-images.githubusercontent.com/36302090/76998753-800dae80-694d-11ea-8e14-16d03b3612b5.png)

**Comment by billziss-gh** [comment]
I have never seen this problem so it is hard to say what causes it.

We can speculate however that the problem happens because for some reason the system attempts to reconnect your Z: drive to your SSHFS server.

- Is there something unusual about your setup?
- Do you have the "Reconnect at sign-in" option enabled?

**Comment by SlavDimov** [comment]
Hello,
the sshfs talks to the built in SFTP service of a Synology NAS. That said:

* Is there something unusual about your setup?
The only extra thing in my setup is a VPN subscription. However, I tried without using it and I still get the same error. Furthermore, I have Linux machine (Fedora 31) using the same network and VPN subscription and talking to the same SFTP and it does not experience this issues.

* Do you have the "Reconnect at sign-in" option enabled?
Yes

I played with it a bit more and got this error as well:
![image](https://user-images.githubusercontent.com/36302090/77122122-ba05b000-6a34-11ea-925a-b5306082087f.png)

**Comment by billziss-gh** [comment]
> - Do you have the "Reconnect at sign-in" option enabled?
> Yes

Can you try removing this option for a while to test whether it is the one that is causing the "reconnect" problem?

**Comment by SlavDimov** [comment]
Without the reconnect option, once an error occurs the connection is not restored until I disconnect and reconnect the network drive (Tested both with and without VPN active). Errors keep getting more and more diverse in the meantime. For example:
![image](https://user-images.githubusercontent.com/36302090/77458332-ef741a00-6df5-11ea-8516-f51cb1300f17.png)

**Comment by SlavDimov** [comment]
Any updates on this? Do you need me to provide more info?

**Comment by billziss-gh** [comment]
It is hard to troubleshoot a problem that I cannot reproduce.

Here is what I gather from your original message:

- The SSHFS-Win file system is mapped to drive Z:.
- The SSHFS-Win file system does not crash and continues to work fine after the error message you are seeing. I base this on the fact that SSHFS-Win does not have the capability to restart itself after a crash and if it continues working after the error message, it is because it never stopped working.
- The error message is not displayed by the file system (file systems are "background" programs and cannot display messages to the user like this).

My conclusion is that while the file system is running normally _something else_ tries to start another file system mapped to Z: drive, which fails with "local device in use". I have no idea what that _something else_ is.

(You would not happen to have any task scheduler tasks trying to start a file system periodically or anything similar, would you?)

Here are a couple of things to do:

- Run `fsdiag.bat` (found in `C:\Program Files (x86)\WinFsp\bin` and post the output here.
- Check the Event Viewer > Windows Logs > Application for log messages with source "WinFsp" around the time that you see the reconnection failure and post them.

**Comment by SlavDimov** [comment]
Hello,
sorry for the late response. For some reason I did not get (or missed) the email notification. Only found out about your post when I came back to check the issue.

I only have `diag.bat` file in `C:\Program Files (x86)\WinFsp\bin ` here is its output:
```C:\Program Files (x86)\WinFsp\bin>diag.bat
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp
    InstallDir    REG_SZ    C:\Program Files (x86)\WinFsp\

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\sshfs
    Executable    REG_SZ    C:\Program Files\SSHFS-Win\bin\sshfs-win.exe
    CommandLine    REG_SZ    svc %1 %2 %U
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1
    Credentials    REG_DWORD    0x1

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\sshfs.k
    Executable    REG_SZ    C:\Program Files\SSHFS-Win\bin\sshfs-win.exe
    CommandLine    REG_SZ    svc %1 %2 %U
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1
    Credentials    REG_DWORD    0x0

HKEY_LOCAL_MACHINE\SOFTWARE\WinFsp\Services\sshfs.r
    Executable    REG_SZ    C:\Program Files\SSHFS-Win\bin\sshfs-win.exe
    CommandLine    REG_SZ    svc %1 %2 %U
    Security    REG_SZ    D:P(A;;RPWPLC;;;WD)
    JobControl    REG_DWORD    0x1
    Credentials    REG_DWORD    0x1


WINFSP DLL REGISTRATIONS

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    cbfsconnect2017,WinFsp.Np,RDPNP,LanmanWorkstation,webclient


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    DeviceName    REG_SZ    \Device\WinFsp.Mup


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll
    TypesSupported    REG_DWORD    0x7


WINFSP FSD CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\Program Files (x86)\WinFsp\bin\winfsp-x64.sys
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       :
        SERVICE_START_NAME :

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp.Launcher
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 0   IGNORE
        BINARY_PATH_NAME   : "C:\Program Files (x86)\WinFsp\bin\launcher-x64.exe"
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : WinFsp.Launcher
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)

OS INFORMATION

Host Name:                 DESKTOP-56JG2AG
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Slav
Registered Organization:
Original Install Date:     9/27/2019, 10:36:34 AM
System Boot Time:          5/2/2020, 7:17:10 PM
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 Mhz
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Total Physical Memory:     16,274 MB
Available Physical Memory: 1,482 MB
Virtual Memory: Max Size:  25,909 MB
Virtual Memory: Available: 4,174 MB
Virtual Memory: In Use:    21,735 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-56JG2AG
Hotfix(s):                 8 Hotfix(s) Installed.
                           [01]: KB4534131
                           [02]: KB4465065
                           [03]: KB4480056
                           [04]: KB4486153
                           [05]: KB4512577
                           [06]: KB4516115
                           [07]: KB4523204
                           [08]: KB4534273
Network Card(s):           7 NIC(s) Installed.
                           [01]: Generic Mobile Broadband Adapter
                                 Connection Name: Cellular
                                 Status:          Media disconnected
                           [02]: Intel(R) Dual Band Wireless-AC 8265
                                 Connection Name: Wi-Fi
                                 <bunch of IP info>
                           [03]: Intel(R) Ethernet Connection (4) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [05]: VPN TAP Adapter
                                 <bunch of IP info>
                           [06]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [07]: Microsoft KM-TEST Loopback Adapter
                                 Connection Name: Npcap Loopback Adapter
                                 DHCP Enabled:    Yes
                                 DHCP Server:     255.255.255.255
                                 IP address(es)
                                 [01]: 169.254.209.208
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

> (You would not happen to have any task scheduler tasks trying to start a file system periodically or anything similar, would you?)

Not to my knowledge. I usually mount the same share as WebDAV but under a different letter and it does not have such problems. 
I only used Z to test the sshfs. Plus like I said in my previous post - when I tried the other tool no such errors appeared (however, the speed was terrible), otherwise I mounted it with the same letter - Z.

Event Viewer:
A bunch of repeating information messages are available:
`launcher-x64: terminated sshfs\me@my.server.com`
`launcher-x64: create sshfs\me@my.server.com = c0000035`
`launcher-x64: create sshfs\me@my.server.com = 0`
`launcher-x64: create sshfs\me@my.server.com = c0000035`
...
Otherwise no error messages.

**Comment by billziss-gh** [comment]
WinFsp did not include any functionality to automatically restart file systems; this changed just this weekend when I released a [new beta version](https://github.com/billziss-gh/winfsp/releases/tag/v1.7B2) that supports automatic restarts. However you cannot have used this version prior to 2 days ago.

The Event Viewer shows continuous attempts to start the file system `\\sshfs\me@my.server.com`. Some of them succeed and some fail with a `c0000035` status code, which stands for `STATUS_OBJECT_NAME_COLLISION`. This error is returned when the drive created already exists (likely because the file system is already running).

It really looks like something is continuously trying to start the file system. This cannot be a WinFsp component because as said WinFsp did not have this functionality prior to 2 days ago. So it must be something other than WinFsp that is causing the restarts.

I note that you have a CBFS Connect Network Provider prior to the WinFsp.Np Network Provider. Perhaps this is what is causing the problems.

Please try changing the order in the registry key `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order` so that `WinFsp.Np` is first.

**Comment by SlavDimov** [comment]
Okay switched the order so that it looks like this:
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order                                                                                                                                                                        ProviderOrder    REG_SZ    WinFsp.Np,cbfsconnect2017,RDPNP,LanmanWorkstation,webclient                      
```
Restarted the PC and tried again with the letter Z - after a few minutes got a slightly different message  "resource is not connected or not found" something like this (forgot to screenshot it).

Disconnected the share and tried again with a different Drive letter - same result.

Checked windows even viewer - same error.

P.S. What is cbfsconnect2017 anyway?

**Comment by billziss-gh** [comment]
Cbfsconnect is commercial software similar to WinFsp (but unrelated to it). You probably installed it when trying other software similar to SSHFS-Win and/or WinFsp (perhaps indirectly via the other software) .

BTW, you do need to reboot (or at least restart Windows Explorer) after making this change. You may also try removing cbfsconnect completely and see if the problem goes away.

If you try with a new VM I suspect that it should work. I have not had any other reports similar to this.

**Comment by SlavDimov** [comment]
I did restart the PC after I mage the registry change.

> Cbfsconnect is commercial software similar to WinFsp (but unrelated to it). You probably installed it when trying other software similar to SSHFS-Win 

In that case it probably got installed when I tried that other tool. However, that tool is gone now, and did not exist when I first tried the WinFsp. 

I will try the VM when I get some free time and report back.

Thank you for your support.
