### ISSUE TITLE
Add this as a chocolatey package

### ISSUE THREAD

**Issue by CMCDragonkai** [billziss-gh/winfsp#30]
Would make it easier to install.

**Comment by CMCDragonkai** [comment]
Here's an example I wrote for the microsoft visual C++ build tools: https://github.com/MatrixAI/Chocolatey-Microsoft-Visual-Cpp-Build-Tools So it's pretty easy to submit chocolatey packages.

**Comment by billziss-gh** [comment]
@CMCDragonkai this is a good suggestion. I am not familiar with Chocolatey and I am currently working on something else, so I may not be able to look into this for a while. Would you consider helping with this?

**Comment by CMCDragonkai** [comment]
Yea I can do it, if you saw my example, it's actually quite easy. The first step is to have a stable location where each release version will be placed (so not a generic download URI, but a URI for every release). The next step is the installation flags. Most windows installers have flags like `/s` or `/norestart` or things like that, that allow unattended installation. Also parameters to specify installation location, or system vs user installation. What are those for fsp. Then uninstallation, what are the requirements for this? If it's a a simple delete a bunch of stuff, that should be easy, but some packages have registry records and other stuff to do. Finally there's upgrading, is there special instructions for this? Or is it just uninstall then reinstall, we may have to be mindful of currently running mounts and do these mounts get interrupted or can they be remounted?

**Comment by billziss-gh** [comment]
> The first step is to have a stable location where each release version will be placed (so not a generic download URI, but a URI for every release).

This one is easy. I make the releases available on github (and elsewhere). So it is always easy to find the download URI's from https://github.com/billziss-gh/winfsp/releases

For example, the URI for the RC1 is this:

https://github.com/billziss-gh/winfsp/releases/download/v1.0RC1/winfsp-1.0.17009.msi

> The next step is the installation flags. Most windows installers have flags like /s or /norestart or things like that, that allow unattended installation.

WinFsp is delivered as an MSI. The MSI currently installs 2 "features":

- The "Core" feature, which contains the WinFsp binaries and associated registry entries.
- The (optional) "Developer" feature, which contains the WinFsp header/library files, some samples and the WinFsp public symbols.

For an unattended installation that installs both features the following should suffice:

    msiexec /i winfsp-1.0.17009.msi /qn INSTALLLEVEL=1000

This will install both the Core and Developer features. [I do not know if chocolatey supports installation variants like some other package managers do.]

> Also parameters to specify installation location, or system vs user installation.

Although I have tested installing in a different directory I have not done so during an unattended installation. Installation internally is controlled by an `INSTALLDIR` property. I am not certain if this can be easily overwritten or not.

WinFsp always does system installation. There is no way to load a kernel driver for a single user.

> Then uninstallation, what are the requirements for this? If it's a a simple delete a bunch of stuff, that should be easy, but some packages have registry records and other stuff to do.

Uninstallation should be done using the MSI. I do not have a command line for you, but can research it.

> Finally there's upgrading, is there special instructions for this? Or is it just uninstall then reinstall, we may have to be mindful of currently running mounts and do these mounts get interrupted or can they be remounted?

The WinFsp MSI does not support upgrading. I recall I tried to make it happen a few months ago, but it was not possible. The primary reason for this is that once an FSD (File System Driver) is loaded it is impossible to unload without a reboot for a number of reasons.

To upgrade one must do uninstall and then reinstall. If the FSD has been loaded (there was at least one user mode file system running currently or in the past) a reboot is required before reinstalling (the MSI will abort the installation if it detects that the FSD is already loaded).

Regarding current mounts. The installer does not currently check if there are any. This is not behavior I have considered before, but I expect the following:

- The installer should be able to delete the FSD even if it is loaded, because it is actually possible to delete a loaded driver on Windows!
- The installer should not be able to delete the WinFsp DLL if it is in use, because it is not normally possible to delete mapped executable images on Windows.

Perhaps the right thing to do here is to have the installer check if there are mounts and either kill them (which is safe as the FSD will clean up nicely) or disallow uninstallation (my preferred option).

> do these mounts get interrupted or can they be remounted?

Remounting is practically impossible. While the FSD has knowledge of all the file systems that are currently mounted on it, it cannot simply recreate the mounts on its own. For this to happen it would have to somehow restart user mode file system processes in the state that they were in prior to the forced dismount.

BTW, the MSI is produced using WIX. The source code for this file is here:

https://github.com/billziss-gh/winfsp/blob/master/build/VStudio/installer/Product.wxs

**Comment by billziss-gh** [comment]
Hi, @CMCDragonkai. Just wondering if you are still interested in this. Thanks.

**Comment by CMCDragonkai** [comment]
Yes, I'm still interested, just been quite busy.

**Comment by billziss-gh** [comment]
Understood. Thank you!

**Comment by tstordyallison** [comment]
+1 this (well, actually just a well trodden path for automated installation and upgrades).

Will be pushing this out to machines via something very similar to chocolatey - having the msi manage the upgrade process (even if that means waiting for a restart but leaving everything else running on the old image) would be perfect.

**Comment by riedel** [comment]
it is rather easy to build a package. I just autobuild a package by pulling all the info from github.
 
In case someone cares:
See: https://gist.github.com/riedel/181e375e7ee89e317b85d9cfd12b9c54

the ps1 script needs to go into a "tools" directory. You the just need to call choco pack.

The template files are just there to illustrate how to initialize the stuff from the github API via ketarin (quite a hack and you need to fix the version number for the prereleases)

Best way to build this would be via github webhook and some nuget ci if someone needs an official release. Otherwise I suggest everyone can build it themselves if they need it for deployment. Nothing is worse than outdated chocolatey packages.

**Comment by billziss-gh** [comment]
@riedel apologies for the late response. I am on vacation and with little knowledge of chocolatey.

> In case someone cares:
See: https://gist.github.com/riedel/181e375e7ee89e317b85d9cfd12b9c54

Some random thoughts below:

- Wouldn't we need both `chocolateyInstall.ps1` and `chocolateyUninstall.ps1` to support both installation and uninstallation?
- I do not understand what Ketarin does.
- Version numbers in WinFsp can be deduced from the MSI name. If `winfsp-mm.nn.bbbbb.msi` is the name, then `mm.nn.bbbbb` is the full version number.

Regarding building the chocolatey package: I am very happy to incorporate the chocolatey package build into the overall WinFsp build, so that when an "official" WinFsp release is done, a chocolatey release is also done. We can perhaps start from your gist if you are willing to resubmit as a Pull Request incorporated into the build process. Keep in mind because of Microsoft driver signing requirements in Windows 10 and Server 2016, this process currently requires a few manual steps. [I can explain this process further if we decide to go this route.]

An alternative might be to setup a project that somehow listens to the "release" web hook and automatically builds the chocolatey package whenever I make a WinFsp release. I am not sure if this is easy to do.

**Comment by riedel** [comment]
@billziss-gh thanks for replying and I wasn't actually expecting that you would follow up on this. My comments were mostly directed towards ppl that really need such a package...

It was rather dumping my PoC in the issue that I somehow found via google.

> Wouldn't we need both chocolateyInstall.ps1 and chocolateyUninstall.ps1 to support both installation and uninstallation?

I checked and the auto-uninstall seems to work just fine if you simply omit the chocolateyUninstall.ps1 

>I do not understand what Ketarin does.

Don't care, this is the suggested way for automatic package building: https://chocolatey.org/docs/automatic-packages

It sucks ;)  It actually does web-scraping to get all package information. Not needed if one incorporates it into a build.

>  so that when an "official" WinFsp release is done, a chocolatey release is also done

makes most sense (actually the hook seems to complicated as manual steps are required for a release anyways). 

> if you are willing to resubmit as a Pull Request incorporated into the build process

Won't promise that it will be me :), but if I will get the build running I can try.  In the end the only thing that is needed is to adapt the version number each time and call `choco pack ` in the folder (which simply incorporates some nu-get stuff)

**Comment by billziss-gh** [comment]
>> if you are willing to resubmit as a Pull Request incorporated into the build process
>
> Won't promise that it will be me :), but if I will get the build running I can try. In the end the only thing that is needed is to adapt the version number each time and call choco pack in the folder (which simply incorporates some nu-get stuff)

Understood. Did not mean to pressure you :)

Here are some notes on the build process in case anyone decides to take on this.

To fully build WinFsp including the MSI one runs:

    tools\build.bat Release

This will build the `Release` configuration, but the resulting driver and MSI will not be signed. It can only be used on a system with `testsigning` turned on.

To prepare a release one must have an EV certificate (and its private key). I have a little hardware token, which contains my EV certificate and I always attach it to the build machine prior to building WinFsp for release. If the hardware token is attached during `tools\build.bat` time, the resulting driver and MSI is signed with my EV certificate. This is good enough to run WinFsp on Win7 to Win10 (prior to the Anniversary Update).

Since the Anniversary Update we have to do more: the signed drivers must also be submitted to Microsoft for attestation signing. [In fact things are even more complicated because of Server 2016 requirements, but I will omit those details from this discussion.]

So now a full release requires multiple steps:

- Run `tools\build.bat Release` with the hardware token attached to create a signed driver, MSI and a CAB file for submission to Microsoft.
- Submit the CAB file to Microsoft and wait 10-20 minutes for it to be signed. This step is currently manual.
- Download a zip file from Microsoft containing the newly signed drivers (this time by Microsoft). Extract to a directory (e.g. `signed-drivers`). This step is also manual.
- Rerun the build process like this: `tools\build.bat Release path-to\signed-drivers`. This will rebuild the MSI to now contain the Microsoft signed drivers.

It looks to me like the chocolate package creation should only be done during the last step, i.e. when we are creating the final MSI for distribution. The `tools\build.bat` file could detect this condition and create the necessary `winfsp.nuspec` and `chocolateyInstall.ps1` files and then run the necessary commands to create the chocolatey package. Deducing WinFsp version could be done from the MSI name. If we also need the MSI crypto hash (not sure), this can perhaps be accomplished with some Powershell.

**Comment by samkelly** [comment]
out of curiosity @billziss-gh where did you buy your code signing cert? I am in the process of evaluating different providers for my software and am hoping to find an affordable, no-bs EV solution

**Comment by billziss-gh** [comment]
I use DigiCert. They used to run a good discount on EV certificates for code signing.

I think this was the Microsoft link I originally followed to get to the DigiCert discount. https://msdn.microsoft.com/windows/hardware/drivers/dashboard/get-a-code-signing-certificate

**Comment by samkelly** [comment]
@billziss-gh thanks!

**Comment by billziss-gh** [comment]
I am looking into adding this into the winfsp build process, so that a chocolatey package release happens whenever a winfsp release happens. I am basing this work on the chocolatey [MSI template](https://chocolatey.org/packages/msi.template/1.0.0) and the ChocolateyGUI [package](https://github.com/chocolatey/ChocolateyGUI/tree/develop/nuspec/chocolatey).

Since I am very new to chocolatey, I am wondering if someone has an answer to this: how does chocolatey handle uninstalls/upgrades that require a restart?

The problem is that the WinFsp MSI potentially requires a restart during uninstall (because it cannot unload the FSD if it has been loaded). This also makes upgrades impossible (without a restart).

Any guidance here much appreciated.

**Comment by CMCDragonkai** [comment]
You can't restart (at least you're not meant to). The right solution would be tell the user that the they may need to restart to complete installation. If you have some tasks to perform, then a scheduled task can be done. I've done this in powershell before, setting up scheduled task for executing a multistage powershell script. Each stage schedules another task that executes the same script, but passes a parameter telling the script which stage to execute. Makes it easy to test specific stages too! Alternatively you could separate each stage into a different script, but there may be more functionality you will need copy from one file to another file.

**Comment by billziss-gh** [comment]
Commits 709ead9e0630d0a5b50f7c8dd603dfc0d74a788f through 2def18e2710f9d8760734f718ca3750c8dc9d78e add chocolatey support to the build process.

I have created a chocolatey account and will be submitting chocolatey packages at the same time as "official" WinFsp releases. I will keep this issue open until the first such chocolatey release.

**Comment by billziss-gh** [comment]
BTW, the package is now available, although it has not passed moderator review yet.

https://chocolatey.org/packages/winfsp

**Comment by riedel** [comment]
Wow thanks! That was quick! I can confirm a working install via the official chocolatey repo. 

On a side note: I noted that it is very difficult for a new user to try out (I had problems because I am always using the cygwin command line to verify the install).

Maybe you could add a short note that one can type in simply type in `\\memfs64\test` to verify that it is working.

Anyways: thx, you are awesome.

**Comment by CMCDragonkai** [comment]
@riedel Type `\\memfs54\test` on Windows explorer?

**Comment by CMCDragonkai** [comment]
Cool, so I think this can be closed now!

**Comment by billziss-gh** [comment]
@riedel wrote:
> Maybe you could add a short note that one can type in simply type in \\memfs64\test to verify that it is working

Good idea. For a quick test one can do:

    net use X: \\memfs64\share

On Cygwin one must do:

    net use X: '\\memfs64\share'

This is because bash understands the backslash `\` as an escape character.

I will see if I can add these instructions to the chocolatey package description.

Here is a little anecdote: Cygwin is actually my main programming environment and shell when on Windows, so I would often use the `net use` command to verify a change or something. I would often forget the single quotes and then get 1-2 seconds of cold sweat, because "I broke WinFsp again" :)

**Comment by billziss-gh** [comment]
Just to let everyone on this thread know that the WinFsp chocolatey package has now been approved:

https://chocolatey.org/packages/winfsp

**Comment by rob-scheepens** [comment]
Thanks for adding this to choco! How can I ensure both Core and Developer features are installed, similar to using /INSTALLLEVEL=1000 for msi?

**Comment by billziss-gh** [comment]
I believe the chocolatey package installs with INSTALLLEVEL=1000 already.

https://github.com/billziss-gh/winfsp/blob/master/build/choco/chocolateyInstall.ps1#L10
