### ISSUE TITLE
Problem stop service WinFsp

### ISSUE THREAD

**Issue by marisogsg** [billziss-gh/winfsp#347]
Good Afternoon,

I have a problem when I am trying stop WinFsp service without reboot:

- I am execute "sc start WinFsp" and obtaine state RUNNING (STOPPABLE...)
- I am execute "sc stop WinFsp" and obtained "Error 1052".
- I can executed "sc delete WinFsp" without errors.
- This service not exists in the services application of Windows 10.

Please, is possible stop without reboot?

Regards,

**Comment by marisogsg** [comment]
![1](https://user-images.githubusercontent.com/11742261/105734031-78864100-5f32-11eb-8e4e-b397d04bbbf2.png)

**Comment by billziss-gh** [comment]
Early on during the FSD (File System Driver) development I tried to make it unloadable. Unfortunately I found out that it was not possible because filter drivers tend to keep extra references to the FSD and make it impossible to unload.

This is the case even when no file systems are created (and no files are opened).

So unfortunately this is by design and unlikely to change.
