### ISSUE TITLE
Can't get Operation Process ID for Rename operations

### ISSUE THREAD

**Issue by SergioLuis** [billziss-gh/winfsp#349]
## Bug Report

According to the [documentation](https://github.com/billziss-gh/winfsp/wiki/WinFsp-API-winfsp.h) it is possible to access the PID of the process originating the operation using `FspFileSystemOperationProcessId` / `GetOperationProcessId` (.NET layer, which is what I'm using).

This should be valid for `Create`, `Open`, and `Rename`. In my testing, however, this is not true. For `Rename` operations, regardless of the process originating the move, the result is always `0`.

Debugging [the code](https://github.com/billziss-gh/winfsp/blob/9d5efe5f988e92d63564bbbec1aadaa38d5e0275/inc/winfsp/winfsp.h#L1385), for this line, the `AccessToken` is always `0`:

```cpp
// winfsp.h : 1385
return FSP_FSCTL_TRANSACT_REQ_TOKEN_PID(Request->Req.SetInformation.Info.Rename.AccessToken);
```

### How to Reproduce

1. Override `Rename` method of `FileSystemBase` class on the .NET layer of WinFSP.
2. Obtain the `id` of the process initiating the operation by calling:

```csharp
int id = GetOperationProcessId();
```

3. Check that `id` is always `0`.

### Behaviors

* Expected behavior: calling `GetOperationProcessId()` inside the `FileSystemBase.Rename` method override returns the PID of the process that originated the rename,
* Actual behavior: calling `GetOperationProcessId()` inside the `FileSystemBase.Rename` method always returns `0`.

### Environment

- OS version and build: Windows 10 (19041.746)
- WinFsp version and build: 2021 Beta1 (1.9.20314)

------

Any help is pretty much appreciated. Thank you!

**Comment by billziss-gh** [comment]
During a `Rename`, the `AccessToken` and associated process ID may be zero or non-zero:

- It is zero when the `MOVEFILE_REPLACE_EXISTING` flag is not set in the `MoveFileExW` API.
- It is non-zero when the `MOVEFILE_REPLACE_EXISTING` flag is set in the `MoveFileExW` API.

The reason is that the `AccessToken` is needed to check for `DELETE` access when renaming over an existing file; this is only possible when the `MOVEFILE_REPLACE_EXISTING` flag is set.

So the behavior you are seeing is by design (unless you are seeing a zero `AccessToken`/`PID` in a case where `MOVEFILE_REPLACE_EXISTING` was specified).

**Comment by billziss-gh** [comment]
@SergioLuis did you have the chance to confirm that `Rename` works as explained above with respect to `AccessToken` / `PID`?

**Comment by SergioLuis** [comment]
Yes! We can close this issue now. Thank you!
