### ISSUE TITLE
Mounting file system fails with result STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by Lnd-stoL** [billziss-gh/winfsp#352]
## Bug Report
Winfsp user mode dll functions (FspFileSystemPreflight, FspFileSystemCreate) return error status STATUS_INSUFFICIENT_RESOURCES.

### How to Reproduce
Just try to mount a disk (for example with memfs).
Unfortunately the bug is not easy reproducible. We use WinFSP in our project and some of our users experience the issue (we have roughly tens of reports). We are unable to reproduce the issue ourselves but can supply the users who faced the issue with debug builds, etc.
The issue arose about a week ago with no obvious cause (no changes in our code, might be a windows update I suppose).

### Environment
Unfortunately no specific environment can be set. From the user reports we see
Different Windows 10 builds (can list on request),
Different WinFSP versions (included the latest).
Different antivirus software.

### What I have investigated
By now I have spotted the error coming from FspFsctlStartService() function, the  STATUS_INSUFFICIENT_RESOURCES (which is ERROR_NO_SYSTEM_RESOURCES from GetLastError()) error is actually returned by OpenServiceW(...) call. Quick googling yielded no results for the possible reasons of such a error code when starting a service.
I can give more details but I need an advice of what sort of diagnostic information is useful in this case.

**Comment by Lnd-stoL** [comment]
Just some thoughts: is running a windows service really required for WinFSP to mount a drive even when launcher infrastructure is not used? I noticed that on my machine stopping the WinFSP.Launcher service doesn't break disk mounting, moreover the service is not started when the disk get mounted. 
As far as I understand, the issue is in starting some WinFSP service, so if I just omit service related code will it work?

**Comment by billziss-gh** [comment]
> By now I have spotted the error coming from FspFsctlStartService() function, the STATUS_INSUFFICIENT_RESOURCES (which is ERROR_NO_SYSTEM_RESOURCES from GetLastError()) error is actually returned by OpenServiceW(...) call. Quick googling yielded no results for the possible reasons of such a error code when starting a service.

This is indeed a weird one and something I have not seen before either.

The `FspFsctlStartService` call is needed to start the file system driver (in case it is not running). To do this it must call `OpenServiceW`. It then goes ahead and calls `StartService`: - if the driver is not running it is started at this point; - if it is already running the call fails with `ERROR_SERVICE_ALREADY_RUNNING`, which is benign in this case.

I cannot imagine why `OpenServiceW` would fail with `ERROR_NO_SYSTEM_RESOURCES`. For users that have experienced this:

- Is the problem persistent, intermittent or one-off?
- When the problem happens can they perhaps run commands like `sc.exe query winfsp` and `sc.exe start winfsp` from a command prompt to see whether the `sc.exe` utility can work around the problem (I do not know for sure, but I would expect that the `sc.exe` utility also uses `OpenServiceW` internally.
- Are the bug reports publicly available? If yes, please share a link.

> Just some thoughts: is running a windows service really required for WinFSP to mount a drive even when launcher infrastructure is not used? I noticed that on my machine stopping the WinFSP.Launcher service doesn't break disk mounting, moreover the service is not started when the disk get mounted.

The Launcher functionality is optional for WinFsp file systems. It is used in order to start file systems on demand in the Windows service context (e.g. for when making a file system available via the `net use` command).

However the Launcher is not related to the `FspFsctlStartService` call that you mentioned earlier. Disabling the Launcher will not fix your problem (and it might break WinFsp file systems other than yours that are running on the same computer and need the Launcher functionality).

**Comment by Lnd-stoL** [comment]
> The FspFsctlStartService call is needed to start the file system driver (in case it is not running). To do this it must call OpenServiceW. It then goes ahead and calls StartService:

Thank you for the explanation. Didn't expect that service stuff is somehow related to starting drivers in windows.

> I cannot imagine why OpenServiceW would fail with ERROR_NO_SYSTEM_RESOURCES

Sure this seems pretty weird for me too. But there are a lot of such reports from our users.

>  Is the problem persistent, intermittent or one-off?

The problem is persistent after it comes up suddenly (users report that everything worked fine before some unlucky day with the same WinFSP and our app's version).

> Are the bug reports publicly available? If yes, please share a link.

Unfortunately the reports are not available publicly mainly because of Russian language and lack of proper formatting.
But I can request and share any kind of information from these reports including logs, system configuration, etc.

> When the problem happens can they perhaps run commands like sc.exe query winfsp and sc.exe start winfsp from a command prompt to see whether the sc.exe utility can work around the problem

Thanks for the suggestion.

**Comment by billziss-gh** [comment]
> > I cannot imagine why OpenServiceW would fail with ERROR_NO_SYSTEM_RESOURCES
>
> Sure this seems pretty weird for me too. But there are a lot of such reports from our users.

Do you know if the FSD is already running when this happens?

> > Is the problem persistent, intermittent or one-off?
>
> The problem is persistent after it comes up suddenly (users report that everything worked fine before some unlucky day with the same WinFSP and our app's version).

When you say persistent, do you also mean that the problem also persists across reboots?

For either definition of persistent the `sc.exe` utility that I mentioned earlier should exhibit the same problem when issuing commands such as `sc.exe query winfsp` and `sc.exe start winfsp`.

I am also wondering if the registry entries for the driver get corrupted somehow. Perhaps your users can try running the `diag.bat` program that is included with WinFsp (in the `bin` directory) and send us the output.

**Comment by Lnd-stoL** [comment]
> Do you know if the FSD is already running when this happens?

Here is the output of **sc.exe query winfsp**:

```
SERVICE_NAME: winfsp 
        TYPE               : 2  FILE_SYSTEM_DRIVER  
        STATE              : 1  STOPPED 
        WIN32_EXIT_CODE    : 5  (0x5)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```

And of **sc.exe start winfsp**:

```
[SC] StartService: error : 1450:
Недостаточно системных ресурсов для завершения операции (Insufficient system resources to complete the operation).
```


> When you say persistent, do you also mean that the problem also persists across reboots?

Yes

> I am also wondering if the registry entries for the driver get corrupted somehow. Perhaps your users can try running the diag.bat program that is included with WinFsp (in the bin directory) and send us the output.

Will ask them

**Comment by billziss-gh** [comment]
> Here is the output of sc.exe query winfsp:
> ...
> And of sc.exe start winfsp:

Thanks for these. It is very interesting that `sc.exe` fails with the `STATUS_INSUFFICIENT_RESOURCES` error only when trying to start the driver.

Are we sure that the problem happens in `OpenServiceW` and not in `StartService`? Is your error code logging precise enough to identify between a failure [here](https://github.com/billziss-gh/winfsp/blob/v1.8/src/dll/fsctl.c#L268) and a failure [here](https://github.com/billziss-gh/winfsp/blob/v1.8/src/dll/fsctl.c#L279)?

I am asking because the first `sc.exe` run presumably executed `OpenServiceW` with at least `SERVICE_QUERY_STATUS` access right, whereas the second `sc.exe` run presumably executed `OpenServiceW` with at least `SERVICE_START` access right. I find it unlikely that this difference would be enough for `OpenServiceW` to fail with `ERROR_NO_SYSTEM_RESOURCES`.

It is perhaps more likely that it is `StartService` that fails with this error code, perhaps because the driver itself fails to load for some reason.

Can you confirm for me whether `OpenServiceW` or `StartService` fails?

> Will ask them

Thank you. This will be helpful in this investigation.

----

If we find out that it is `StartService` that fails, a step towards resolving this problem would be to build a special version of the driver that does additional logging during initialization.

**Comment by Lnd-stoL** [comment]
> Are we sure that the problem happens in OpenServiceW and not in StartService? Is your error code logging precise enough to identify between a failure here and a failure here?

After careful investigation I see that error is actually returned by StartService as expected, not OpenService as I said before. Sorry for this misinformation.

> If we find out that it is StartService that fails, a step towards resolving this problem would be to build a special version of the driver that does additional logging during initialization.

Will this diagnostic driver build require some additional effort from the users? Some signature issue or so.
Anyway I will definitely try it as there are no other options.

**Comment by billziss-gh** [comment]
> After careful investigation I see that error is actually returned by StartService as expected, not OpenService as I said before. Sorry for this misinformation.

Ok, this makes more sense.

I find it likely that if [`DriverEntry`](https://github.com/billziss-gh/winfsp/blob/v1.8/src/sys/driver.c#L36) (i.e. the driver's entry point) returns `STATUS_INSUFFICIENT_RESOURCES` for some reason, then `StartService` will fail with the equivalent Win32 error `ERROR_NO_SYSTEM_RESOURCES`.

> Will this diagnostic driver build require some additional effort from the users? Some signature issue or so.
Anyway I will definitely try it as there are no other options.

Likely unless you are able to sign the driver yourself. Otherwise users will have to enable testsigning. Use the command `bcdedit.exe -set testsigning on` from an Administrator prompt for this.

You must be able to build the driver from source. The latest driver has a simple tracing framework enabled by the macro [`FSP_TRACE_ENABLED`](https://github.com/billziss-gh/winfsp/blob/master/src/sys/driver.h#L151). Perhaps you can use this to trace all exits from `DriverEntry` so that we can pinpoint the problem.

Trace output appears in [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview):

- Start DebugView as Administrator.
- In DebugView, select Capture > Capture Kernel and Enable Verbose Kernel Output. You can disable Capture Win32 and Capture Global Win32 to avoid getting too many unrelated messages.

**Comment by Lnd-stoL** [comment]
> I find it likely that if DriverEntry (i.e. the driver's entry point) returns STATUS_INSUFFICIENT_RESOURCES for some reason, then StartService will fail with the equivalent Win32 error ERROR_NO_SYSTEM_RESOURCES.

Sounds reasonable.

> Otherwise users will have to enable testsigning. Use the command bcdedit.exe -set testsigning on from an Administrator prompt for this.

Seems not to be a blocker.

> You must be able to build the driver from source. 

So it's not needed to add some more verbose logging to the driver code, just define the macro?
How can I install the tracing driver build to the user's PC? Just copy the .sys file in place of the original one is enough? What about signing? When testing mode is enabled signing is not required at all?

**Comment by billziss-gh** [comment]
> So it's not needed to add some more verbose logging to the driver code, just define the macro?

You may want to add some more `FSP_TRACE` statements in places like [here](https://github.com/billziss-gh/winfsp/blob/master/src/sys/driver.c#L136). This would let us determine which initialization function is failing and investigate further.

> How can I install the tracing driver build to the user's PC? Just copy the .sys file in place of the original one is enough?

This should be adequate.

> What about signing? When testing mode is enabled signing is not required at all?

Correct. If your users enable testsigning then the driver file does not need to be signed.

**Comment by Lnd-stoL** [comment]
Just an update, there is the output of diag.bat

```
WINFSP INSTALLATION DIRECTORY AND LAUNCHER REGISTRATIONS  
  
WINFSP DLL REGISTRATIONS  

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\NetworkProvider\Order
    ProviderOrder    REG_SZ    WinFsp.Np,P9NP,RDPNP,LanmanWorkstation,webclient


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinFsp.Np\NetworkProvider
    Name    REG_SZ    Windows File System Proxy
    ProviderPath    REG_SZ    C:\WINDOWS\system32\disko\winfsp_x64.dll
    DeviceName    REG_SZ    \Device\WinFsp.Mup


HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\WinFsp
    EventMessageFile    REG_SZ    C:\WINDOWS\system32\disko\winfsp_x64.dll
    TypesSupported    REG_DWORD    0x7

 
WINFSP FSD CONFIGURATION AND STATUS 

SERVICE_NAME: WinFsp 
        TYPE               : 2  FILE_SYSTEM_DRIVER  
        STATE              : 1  STOPPED 
        WIN32_EXIT_CODE    : 5  (0x5)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: WinFsp
        TYPE               : 2  FILE_SYSTEM_DRIVER 
        START_TYPE         : 3   DEMAND_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : \??\C:\WINDOWS\system32\disko\winfsp_x64.sys
        LOAD_ORDER_GROUP   : 
        TAG                : 0
        DISPLAY_NAME       : WinFsp
        DEPENDENCIES       : 
        SERVICE_START_NAME : 

D:(A;;LCRP;;;WD)(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)
 
WINFSP LAUNCHER SERVICE CONFIGURATION AND STATUS 
[SC] EnumQueryServicesStatus:OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

[SC] OpenService FAILED 1060:

The specified service does not exist as an installed service.

 
OS INFORMATION 

Host Name:                 DESKTOP-VVNLLSQ
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19041 N/A Build 19041
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Pavel
Registered Organization:   
Product ID:                00331-10000-00001-AA437
Original Install Date:     9/1/2020, 6:50:12 AM
System Boot Time:          2/24/2021, 3:13:13 PM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 8 Stepping 2 AuthenticAMD ~3400 Mhz
BIOS Version:              American Megatrends Inc. 2801, 9/18/2019
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             ru;Russian
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
Total Physical Memory:     16,310 MB
Available Physical Memory: 5,551 MB
Virtual Memory: Max Size:  24,246 MB
Virtual Memory: Available: 9,163 MB
Virtual Memory: In Use:    15,083 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-VVNLLSQ
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4561600
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4580325
                           [07]: KB4586864
                           [08]: KB4598481
                           [09]: KB4601319
Network Card(s):           2 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: outline-tap0
                                 Status:          Hardware not present
                           [02]: Intel(R) I211 Gigabit Network Connection
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.8.1
                                 IP address(es)
                                 [01]: 192.168.8.105
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
 
```

**Comment by billziss-gh** [comment]
> Just an update, here is the output of diag.bat

The installation looks rather broken to me, but I believe this is explained below.

> Note here that we use custom driver installation path (??\C:\WINDOWS\system32\disko\winfsp_x64.sys), this shouldn't be an issue though.

I have sent you a private mail about this.

**Comment by billziss-gh** [comment]
@Lnd-stoL do you have any more information regarding the `STATUS_INSUFFICIENT_RESOURCES` problem?

**Comment by Lnd-stoL** [comment]
It's quite strange but the issue seems to disappear suddenly. More and more of our users who faced the issue keep reporting that it is solved eventually. I suppose that's related to a windows or some other software update.

It was rather difficult to collect kernel logs from the user's PC without remote access so there are no much details. Though, one of the users who was able to try tracing driver build reported that there were no logs from winfsp in DebugView, just like the driver didn't even load (I inserted a trace point just into the beginning of driver initialisation function and can see it in DebugView locally on my pc).

**Comment by billziss-gh** [comment]
This is strange indeed.

I believe [`StartService`](https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicew) and the SCM (Service Control Manager) calls [`NtLoadDriver`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-zwloaddriver) fairly quickly when starting a driver. If we are certain that the driver does not even load in these cases (I would want to make sure that your users were using DebugView correctly, because kernel messages are not seen by default), there is not much of an opportunity for things to go wrong in this fashion (`STATUS_INSUFFICIENT_RESOURCES`).

In any case if the problem suddenly disappeared it is impossible to investigate. But please let me know if you get any additional information.

**Comment by billziss-gh** [comment]
I am closing this, but please let me know if you have more information.
