### ISSUE TITLE
Writes delivered by WinFSP out of order

### ISSUE THREAD

**Issue by lemourin** [billziss-gh/winfsp#353]
Is it possible to force WinFSP to deliver requests in the same order as the client application is issuing them?

I noticed that e.g when copying files through explorer.exe or `copy` in cmd.exe my filesystem does not receive writes in strictly increasing order. My usecase is to be able to upload files to cloud storage (e.g Google Drive) with no buffering. It is possible on Linux with FUSE (tested with cp, rsync, copying using UI and all writes are received in correct order); was wondering if that could be possible on Windows.

**Comment by billziss-gh** [comment]
Unfortunately this is not possible in WinFsp. There are many reasons for this, some by design, some because of the Windows environment and some because of the WinFsp implementation. I include an incomplete list below:

- [DESIGN] The file operations interface is random access by design. This means that the file system must be ready to receive I/O in any order.

- [ENVIRONMENT] Different software components may be performing I/O on the same file, even when it appears that a single process is accessing it. For example, on Windows it is quite common for a file system filter (e.g. AntiVirus) to perform its own I/O on a file when the file is opened.

- [ENVIRONMENT] The OS itself may reorder I/O. For example, this will almost always be the case when a file is cached. Even when a file is not cached, memory mapped I/O is not sensibly ordered. (It is of course possible if one knows many details of the OS, to guess the order that the OS will use in these circumstances. However this order is affected by many factors, including OS version, current OS workload, previous patterns used by a particular process, etc. It is best to treat the OS order as non-deterministic.)

- [WINFSP] Assuming that one is careful to use an application that always use sequential non-buffered I/O, turns off extraneous file system filters, etc. it is unfortunately still not possible to guarantee ordered delivery of I/O. This is due to WinFsp design: I/O requests are posted into an internal queue and multiple threads pull I/O from that queue; it is conceivable that a thread that pulls a Write for offset 0 gets suspended while a second thread that pulls a Write for offset 4096 progresses. Furthermore due to issues with file system filters in Windows it is not safe to run a file system with less than 2 threads.

So what you want is unfortunately not possible. Your best approach is to buffer contents on disk or in memory. I routinely have to do this with my own cloud file systems.
