### ISSUE TITLE
Is there any possibility to run WinFsp on windows on arm?

### ISSUE THREAD

**Issue by I-Rinka** [billziss-gh/winfsp#372]
## Question

I tried to run this under the x86 emulation of Woa but failed. So, I wonder if there any possibility to cross-compile this software to port to windows on arm?

Is there any problem such as library dependency or unsupported tool chain to port this software to arm64 platform? It works really fine on my x64 laptop, but I felt pity for it isn't workable my Woa system.

**Comment by billziss-gh** [comment]
I believe this should be doable.

- WinFsp has no external dependencies (other than the OS).
- I expect that porting would be more or less a straight rebuild with ARM tools and perhaps addressing any changes between the x64 and arm64 OS.
- There may be some gotchas with atomics and memory barriers. There are a few places where WinFsp uses memory barriers directly (because `stdatomic.h` was not available) and the assumption is that the CPU provides strong consistency guarantees a-la x86/x64. These would have to be identified and rectified.

Having said that I have had no plans to port as it was never requested before. I also do not currently have access to a Windows on ARM machine.

**Comment by sidd-kishan** [comment]
We can help you test We have Windows on Rasberry Pi setup. Please pursue it we at Windows on Rasberry Pi community will be glad to extend support in testing your drivers and tools for ARM64.

**Comment by Jerry8538** [comment]
I am willing to test it as well, since I too have a Raspberry Pi running Windows on ARM.

**Comment by billziss-gh** [comment]
I have familiarity with Raspberry Pi, but not on Windows.

How is Windows on Raspberry Pi?

- Is it useable as a dev/test platform?
- Is any virtualization software available?
- Is it possible to attach a kernel debugger for solving issues that may crop up in a port?

**Comment by Jerry8538** [comment]
> How is Windows on Raspberry Pi?

1. It's a bit slow, but I would say it is useable.
2. I don't think it's possible, since the Pi has a slow CPU, and no hardware acceleration. It is possible to run VMs through QEMU on Raspbian, but that's slow, and it's Linux.
3. Sorry if I am misunderstanding your question, but since it wouldn't really be possible to run a VM on the Pi, I don't think this would be possible either.

It does seem as though it would be very hard testing on the Pi, since it seems to be a bit too slow for VMs, but it might be possible to test it on another ARM computer, one of the Surface devices maybe?
Again, I may be misunderstanding some of these questions, maybe you don't intend to run a VM on the Pi, in which case, it might be possible.

**Comment by unintended-consequences** [comment]
Another request here, but for the Microsoft Surface Pro X community - we run Windows 11 on Microsoft's proprietary SQ1 ARM chip. Happy to volunteer to test as well. Thanks!

**Comment by billziss-gh** [comment]
I have no firm plans for this yet, but I may start working on it some time in the next couple of months.

Dev/test would be done on M1 Mac via Parallels. The workflow should be familiar as I originally developed Intel WinFsp on an Intel Mac via a similar workflow.

**Comment by billziss-gh** [comment]
I have no firm plans for this yet, but I may start working on it some time in the next couple of months.

**Comment by billziss-gh** [comment]
Work on ARM64 is underway in private branch [pvt-arm64](https://github.com/billziss-gh/winfsp/tree/pvt-arm64).

**Comment by billziss-gh** [comment]
WinFsp 2022+ARM64 Beta1 has been released.

Please test and let me know of any problems you experience.

**Comment by unintended-consequences** [comment]
Installer defaults to Program Files (x86) directory.

**Comment by billziss-gh** [comment]
@unintended-consequences 

Yes, this is by design.

WinFsp on ARM64 supports ARM64, x64 and x86 file systems and is backwards compatible with previous versions. This is the reason for the (default) installation in the `Program Files (x86)` directory.

WinFsp on ARM64 includes an ARM64 driver (`winfsp-a64.sys`) and an ARM64 file system will only use ARM64 code.
