### ISSUE TITLE
Are symlinks to files outside of the mounted fuse-winfsp filesystem possible?

### ISSUE THREAD

**Issue by gf-db** [billziss-gh/winfsp#378]
## Question

I'm prototyping a lightweight crossplatform fuse filesystem, which would present its contents as some directory tree, but files in it are supposed to be mere symlinks to their content outside the FS to avoid read call passthrough. On Linux with FUSE this works as expected - for example, if I mount my FS into "/mnt/myfs/" and want some link to point to "/home/user/file" then I can either make it an absolute symlink to "/home/user/file" or a relative one to "../../home/user/file". On Windows with WinFSP-FUSE neither approach seems to work. I understand that absolute symlinks are probably not viable at all, because windows deals with drive letters instead of a single filesystem root, but is there anything preventing relative symlinks from working? If I mount winfsp-fuse filesystem as a directory, is there any way for a symlink to refer to content higher up than the mountpoint in the directory tree? If there isn't one currently, are there any conceptual issues that would not allow this?

**Comment by billziss-gh** [comment]
WinFsp-FUSE only allows symbolic links to point inside the file system.

The primary reason is that Windows does not present a single unified file tree to the user (although such a tree does exist at the OS level). Rather it presents a "forest of trees" (drives) which unfortunately POSIX symbolic links do not support directly, because they assume a single file tree.

We could perhaps work around this by allowing a "special" symbolic link to point across drives, by using special syntax like `/??/c/Program Files (x86)/WinFsp` to mean a symbolic link that targets the file/directory `C:\Program Files (x86)/WinFsp`. But this is not something that is currently supported.
