### ISSUE TITLE
Support fuse option -s

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#38]
Not all fuse systems are written with multithreading in mind, and not all work better multithreaded (I/O is inherently a serialized operation). Please support option -s so that a single thread is used.

**Comment by billziss-gh** [comment]
The `-s` option is supported. See here: https://github.com/billziss-gh/winfsp/blob/master/src/dll/fuse/fuse_main.c#L41

However it does not restrict WinFsp to a single thread. It guarantees that all file system operations will be called within an exclusive lock and be serialized. This should work for most FUSE file systems, but if a file system has thread affinity needs (e.g. it uses thread local storage and expects that values be preserved from operation to operation), it will not work.

The reason that WinFsp cannot be restricted to a single thread is that it is possible for the Windows kernel to make a reentrant file system call during the completion of a file system operation (when the thread is blocked). Therefore there is a need for a second thread to service such reentrant file system operations. [This happens very rarely and I have only observed it during IRP completion of Rename. I am suspecting that the culprit is actually a filter driver rather than the kernel. Nevertheless the file system must be able to cope and not deadlock.]
