### ISSUE TITLE
Why isn't the dll installed into the system directory?

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#39]
I installed WinFsp and had to copy the dll files to my working directory in order for my fuse executable to find it on load. Why isn't it installed to a system directory?

**Comment by billziss-gh** [comment]
It is my opinion that applications that do not ship with the OS should not be installing components in the system directories. I understand that this creates an inconvenience, because of the way DLL loading works on Windows.

There are many solutions to this problem. My preferred one is to delay load the WinFsp DLL and then load it from the correct directory at run time. I have a tutorial which explains.

https://github.com/billziss-gh/winfsp/wiki/WinFsp-Tutorial#create-the-project-skeleton

**Comment by netheril96** [comment]
Another solution is to add the installed bin dir to system path.

Usually I think DLLs should not be injected into the system directory, and should come bundled with the executable that uses it. *However*, WinFsp is a driver that has to install many files into the system anyway, so a few more userspace DLLs should not be a problem.

Anyway, if you insist, how can I do the lazy loading with CMake as my build system?

**Comment by billziss-gh** [comment]
> Anyway, if you insist, how can I do the lazy loading with CMake as my build system?

Unfortunately I cannot provide any direct guidance there as I am unfamiliar with CMake. I believe what is required for VS tools is to set the `/DELAYLOAD:"winfsp-x64.dll"` option and link with `delayimp.lib`.

Google turns up some links re: CMake and delay loading, but I cannot assess how good they are, because I lack the necessary CMake knowledge.

**Comment by netheril96** [comment]
How does this magic delayed loading work? How does it find the DLLs since they may be installed anywhere? And I haven't found the declaration of `FspLoad`.

**Comment by billziss-gh** [comment]
My apologies, this is not in RC1. It will be included as a `static inline` in RC2.

For now see this [public gist](https://gist.github.com/billziss-gh/4385c783c56ef1c52e44940099d44d6b) for `FspLoad`. You can remove it from your project when RC2 is released.
