### ISSUE TITLE
why no support hard links?

### ISSUE THREAD

**Issue by A253F12** [billziss-gh/winfsp#390]
Sorry, this requirement seems to have been discussed a long time ago. I don't know why winfsp still doesn't support hard links

**Comment by billziss-gh** [comment]
There are two reasons why I decided not to support hard links in WinFsp:

- Sane user mode API. Without hard links it is reasonable to use the file name as a means of uniquely identifying a file (even in the presence of `Rename`). With hard links you cannot use the file name as unique identifier, because files named `\a` and `\b` may actually be the same file. Thus a separate unique identifier would have to be used (a-la UNIX inode number) to identify files; this is important for a number of reasons, for example, `\a` and `\b` should share cache.

    - I did have a version that mapped "inode numbers" to "file nodes" for a while, but writing file systems for it felt unnecessarily difficult.

- Hard links seemed like an unnecessary complication at a time when I was trying to bootstrap the original FSD. Opening a file in Windows is already a very complex task and hard links would complicate matters further.

I may have to revisit this decision in the future. There are alternative designs for hard links that are not based on the "inode number" concept and I may be able to retrofit one into the WinFsp API.
