### ISSUE TITLE
Write access denied (fuse compat layer)

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#40]
I ported my fuse system to Windows with WinFsp. However, none of the files in the mounted drive can be opened for writing. New files can be created without problems. The error is always "Access denied". I am sure that my code does not return the error code since I inspect the logs for all the return values.

The `getattr` calls returns `mode` in `0666` so that everyone should have read/write/execute access.

Inspecting the security setting reveals the following attributes:

![1](https://cloud.githubusercontent.com/assets/836839/22549153/eabb826c-e984-11e6-8e93-7b65e4cf0a8c.PNG)
![2](https://cloud.githubusercontent.com/assets/836839/22549161/f0fb2178-e984-11e6-8e9f-2470956cc03e.PNG)

I do not recognize the user name `S-1-5-0`.

**Comment by billziss-gh** [comment]
@netheril96 Thank you for porting your file system to WinFsp-FUSE.

Looking into your profile I see a file system [securefs](https://github.com/netheril96/securefs). Is this the file system that exhibits the problem? If yes, I can try it myself and help you resolve the issue.

The "access denied" error likely comes from the `GetSecurityByName` file system operation. This is implemented for you in WinFsp-FUSE by calling `getattr` and converting the POSIX uid, gid, mode to a Windows security descriptor. This security descriptor contains an Access Control List (ACL) that has Allow/Deny entries that attempt to emulate the POSIX behavior.

See here for further discussion: https://github.com/billziss-gh/winfsp/wiki/SSHFS-Port-Case-Study#step-3-mapping-windows-to-posix

> The getattr calls returns mode in 0666 so that everyone should have read/write/execute access.

I recommend 0777 or 0755 if you want everything to have all accesses (0666 misses execute access). You may also have to correctly set uid, gid using the `-ouid`, `-ogid` options, depending on how your file system does things.

**Comment by netheril96** [comment]
Yes, I am trying to port `securefs`.

So, should I convert the Windows SID with `FspPosixMapSidToUid` and return that as the `st_uid` field in the `getattr` call? What about `st_gid`?

Frankly, the permission mapping between Unix and Windows style is very complicated. There should be an easy way to just set all security descriptors to "allowing whoever mounts the filesystem full access and denying everyone else all access".

**Comment by billziss-gh** [comment]
> Yes, I am trying to port securefs.

I will take a look at it.

> So, should I convert the Windows SID with FspPosixMapSidToUid and return that as the st_uid field in the getattr call? What about st_gid?

In general you must return correct `uid`/`gid` from `getattr` or things will not work, unless you force them using the `-ouid`, `-ogid` switches.

In you case, I looked into [`fstat`](https://github.com/netheril96/securefs/blob/master/sources/win.cpp#L492) and I see that you return `uid` and `gid` as 0.

> Frankly, the permission mapping between Unix and Windows style is very complicated. There should be an easy way to just set all security descriptors to "allowing whoever mounts the filesystem full access and denying everyone else all access".

I agree that it is complicated but it is also a complicated problem to map the Windows security model to POSIX and vice-versa. It may be a good idea to introduce `-o default_uid` and `-o default_gid` switches where the WinFsp-FUSE layer does the translation for you.

BTW, I am currently actively testing the FUSE layer for RC2 (due some time next week hopefully), so I may just add that.

**Comment by billziss-gh** [comment]
Commit 0c945b67f3d248ccc24fe4eb15ed688118fbf135 adds the ability to do `-ouid=-1,gid=-1` on the command line. In this case the WinFsp-FUSE layer will force the `uid` and `gid` to match those of the user who mounted the file system.

**Comment by billziss-gh** [comment]
The Windows security model is a complicated (and frustrating) subject. It is one of my favorite gripes on that OS.

If you want to just make things work, one way is to specify `-ouid=65792,gid=65792,umask=0` on the command line. This should enable Full Control access to "Everyone". [This being Windows "Everyone" is not really everyone, but for practical purposes it is.]

What this does is it forces the `uid` and `gid` to be the Everyone (World) SID and the file mode to be 0777. This is what I currently do for a sample FUSE file system that I will include with RC2 (although I intend to eventually properly implement security for it, which is what you are trying to do):

https://github.com/billziss-gh/winfsp/tree/pvt-v1.0-fixes/tst/passthrough-fuse

Let us now talk about what access checks are done in a WinFsp file system and what access checks (I think) are done for your file system.

WinFsp (and every properly implemented Windows file system) does access checks primarily during processing of the `CREATE` IRP (the equivalent of the `CreateFileW` API). In order to do so it fetches the file attributes and security descriptor of a file using the `GetSecurityByName` operation, which gets converted into `getattr` by the WinFsp-FUSE layer. WinFsp checks to see whether the process that is issuing the `CreateFileW` has the right to do so according to the security descriptor returned by `GetSecurityByName`.

However in your case that is not the end of the story. Your file system uses the underlying file system (NTFS) as a storage medium. NTFS applies its own file access checks against your file system process credentials (**not** those of the process that issued the original `CreateFileW`). Therefore while WinFsp and your file system think it's ok to access a file based on the values you return from `getattr`, NTFS may think otherwise and it may still return `ERROR_ACCESS_DENIED`.

I am looking into your [win.cpp](https://github.com/netheril96/securefs/blob/master/sources/win.cpp) file and I have a few observations.

You use `CreateFileW` and `CreateDirectoryW` to create files and directories and you pass a `NULL` security descriptor. This tells the underlying file system (NTFS) to create the file with default credentials; in this case those of the file system process. Additionally and as mentioned above `CreateFileW` and `CreateDirectoryW` will perform their own access checks against your file system process credentials.

Your `fstat` (`stat_file_handle`) implementation reports `uid==getuid()` and `mode=0777`. Again observe that the `uid` reported here is that of the file system, not that contained in the file's security descriptor. [They could be the same if your file system created the file].

Finally a tip: a command that I often use on Windows to examine the actual security descriptor of a file/directory is this: `cacls FILENAME /S`. This prints out the security descriptor in SDDL syntax, which while cryptic, accurately shows what the security descriptor looks like. It helps greatly with troubleshooting.

**Comment by billziss-gh** [comment]
BTW, I have here an implementation of a minimal POSIX layer:

https://github.com/billziss-gh/winfsp/blob/pvt-v1.0-fixes/tst/passthrough-fuse/winposix.c

It currently has the same issues with security as yours, because it does not properly implement security for NTFS. Since it looks like others may benefit from it, I may flesh it out.

**Comment by netheril96** [comment]
Some issues regarding your winposix.c

* `HANDLE` is declared as `void *`. Won't casting it to and from `int` truncate its higher bits?
* On POSIX systems, `ftrunctate` must zero out any new space, which is usually very fast due to sparse file support. Does `SetFileInformationByHandle` do that too? `SetEndOfFile` says the intervening data is uninitialized. Frankly, the manual zeroing operation has proved to be another performance bottleneck for my application.
* `utime` should handle NULL utimebuf, in which case it means current time for both access and modification time.

Now, back to my original question. The files are always created and opened and modified by my filesystem process, so the NULL descriptor should not be a problem. In fact, I log every failure on `CreateFileW`, `ReadFile` or `WriteFile`, but I see none when opening file in the mounted virtual filesystem gets permission denied. So the problem most probably resides in how WinFsp translates the permission bits.

**Comment by billziss-gh** [comment]
> `HANDLE` is declared as `void *`. Won't casting it to and from int truncate its higher bits?

Yes. But these bits are 0. User mode handles are restricted to 32-bits even on Windows 64-bit:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa384203%28v=vs.85%29.aspx

If you want to be on the safe side, change all the `int`'s to `intptr_t`'s. That is what I have done in other places.

> `SetEndOfFile` says the intervening data is uninitialized.

Doh! Actually you are right. A better alternative may be `SetFileValidData` then.

> `utime` should handle NULL utimebuf, in which case it means current time for both access and modification time.

`man 3 utime` says you are right on my OSX box.

Thanks for the good suggestions.

> Now, back to my original question. The files are always created and opened and modified by my filesystem process, so the NULL descriptor should not be a problem. In fact, I log every failure on CreateFileW, ReadFile or WriteFile, but I see none when opening file in the mounted virtual filesystem gets permission denied. So the problem most probably resides in how WinFsp translates the permission bits.

Try the `cacls FILENAME /S` command and let me know what security descriptor is reported back.

**Comment by netheril96** [comment]
`Z:\01. believe.aac "D:P(A;;0x1f01b9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1200a9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1200a9;;;WD)"` for a permission bits of 0755.

`Z:\01. believe.aac "D:P(A;;0x1f01bf;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1201af;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1201af;;;WD)"` for 0777.

I cannot comprehend them at all.

**Comment by billziss-gh** [comment]
Ok, let's dissect the first one:

`Z:\01. believe.aac "D:P(A;;0x1f01b9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1200a9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)(A;;0x1200a9;;;WD)"`

- `D:P`: this is a protected DACL
- `(A;;0x1f01b9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)`: this is an Access Control Entry (ACE) **allowing** access to the SID S-1-5-21-... (presumably your account's SID, since you do `getuid()` in your `fstat`). The allowed access is `0x1f01b9`.
- `(A;;0x1200a9;;;S-1-5-21-1466929317-1573708390-3470831944-1001)`: this ACE also allows access to the same SID. The allowed access is `0x1200a9`.
- `(A;;0x1200a9;;;WD)`: this ACE allows access to `WD`, the "World" or "Everyone" SID. The allowed access is `0x1200a9`.

Now let's dissect those bits:

- `0x1f01b9`: `SYNCHRONIZE | DELETE | READ_CONTROL | WRITE_DAC | WRITE_OWNER | FILE_WRITE_ATTRIBUTES | FILE_READ_ATTRIBUTES | FILE_EXECUTE | FILE_WRITE_EA | FILE_READ_DATA`

So this one actually lacks Write access (`FILE_WRITE_DATA`, `FILE_APPEND_DATA`)! Looking into the source code (https://github.com/billziss-gh/winfsp/blob/master/src/dll/posix.c#L464):

    /* [PERMS]
     * What about the case where both owner and group are the same SID and
     * a chmod(1) request is made where the owner and the group permission
     * bits are different?. In this case, the most restrictive permissions
     * are chosen and assigned to both ACEs.
     */
    if (EqualSid(OwnerSid, GroupSid))
        OwnerPerm = GroupPerm = OwnerPerm & GroupPerm;

[BTW, I did not make these rules up, they come from the Microsoft Services for UNIX document: https://technet.microsoft.com/en-us/library/bb463216.aspx]

Solution: use `0777` mode, or use a different `gid` than your `uid` (e.g. `TokenPrimaryGroup`).

A final comment on this: in the second SDDL, the access rights for `WD` are `0x1201af` which looks to me that they allow `FILE_WRITE_DATA` and `FILE_APPEND_DATA` (i.e. Write access).

----

PS: I forgot that `cacls` omits owner and group information when printing SDDL. I use `winfstest` with this command line to get a full and accurate security descriptor:

    C:\...> winfstest.exe GetFileSecurity .git OWNER_SECURITY_INFORMATION+GROUP_SECURITY_INFORMATION+DACL_SECURITY_INFORMATION
    0
    Sddl="O:S-1-5-0G:S-1-5-0D:P(A;;FA;;;S-1-5-0)(A;;0x1201ef;;;S-1-5-0)(A;;0x1201ef;;;WD)"

`Winfstest` can be found in this repository: https://github.com/billziss-gh/secfs.test

This was run on passthrough-fuse using `uid` and `gid` of `0`, which gets translated to `S-1-5-0`.

**Comment by billziss-gh** [comment]
I wanted to add some comments about this:

You wrote:
> > `SetEndOfFile` says the intervening data is uninitialized.

I responded:
> Doh! Actually you are right. A better alternative may be `SetFileValidData` then.

I answered late at night (for me) but this kept bothering me so I had to investigate further.

`SetEndOfFile` (not `SetFileValidData`) is the right API. It is true that the `SetEndOfFile` documentation states:

> If the file is extended, the contents of the file between the old end of the file and the new end of the file are not defined.

OTOH, NTFS will fill the extended portion with zeroes: https://blogs.msdn.microsoft.com/oldnewthing/20150710-00/?p=45171

I am not certain of this but I believe that FastFat will also do so (this is because it maintains `ValidDataLength`). See also the source code for FastFat at this location:

https://github.com/Microsoft/Windows-driver-samples/blob/master/filesys/fastfat/read.c#L1155

**Comment by netheril96** [comment]
OK, I implement a `getgid()` based on `TOKEN_GROUPS` and then return 0755 and it works. It also matches the results from cygwin.

It is best, however, if you can provide utility functions for `getuid()` and `getgid()` in the future so that other people porting FUSE programs do not have to sift through MSDN documentation to assemble the cryptic incantations. The Windows API is really a complicated mess. I don't know how it does not fall apart on its weight.
