### ISSUE TITLE
Unable to pass tests of passthrough example

### ISSUE THREAD

**Issue by kice** [billziss-gh/winfsp#407]
I would like make something that base on passthrough, but it looks there are too many tests will just failed. I would like to update the example myself, but it looks like there are too many tests to fix and a lot of them is not possible for me to fix.

Is it any change passthrough example will get an update? Alought it looks like nobody has fixed it for the last few years.

**Comment by billziss-gh** [comment]
Please do not use `passthrough` in production. It was built for a tutorial and was never intended to be used for production purposes.

Because I have realized that a lot of people are looking for a robust passthrough-like file system, I am building an alternative called [`ntpfs`](https://github.com/billziss-gh/winfsp/tree/master/tst/ntptfs). This is not currently fully tested, but it is already passing most tests in `winfsp-tests`. I also plan to have it pass (most of) Microsoft's `ifstest`.

----

The tests in `winfsp-tests` that currently fail are: 

- `create_allocation_test`: This tests an obscure NTFS feature called "allocation size" that is not accessible via the regular Win32 API. The `ntpfs` file system supports allocation size in a manner that is mostly compatible with NTFS, but there is a small incompatibility on how allocation size is handled when a handle is closed. This test detects this small incompatibility. Fixing it is possible, but it may incur a performance penalty and is likely not worth it.

- `wsl_stat_test`: This tests whether the file system allows use by WSL1. This can be made to pass by simply enabling `WslFeatures` for `ntptfs`. This test is far less important now that Microsoft has effectively deprecated WSL1.

- `rename_flipflop_test`, `rename_mmap_test`, `exec_rename_dir_test`, `stream_rename_flipflop_test`:  These test the ability to rename directories that contain memory mapped files or streams (that have been closed). These test cannot be fixed within a passthrough architecture that uses `HANDLE` to identify files. I note that Microsoft's own network redirector fails this.
