### ISSUE TITLE
`readdir` is not preceded by `opendir` call

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#41]
Sometimes `readdir` is called without an associated `opendir` call, so the handle in `fuse_info` is `NULL` and that crashed my filesystem. I add a workaround for this, but in the long run, WinFsp should always conform to the official fuse API where reading a directory is issued as `opendir` then `readdir` and finally `releasedir`.

**Comment by billziss-gh** [comment]
I agree. If this is indeed the case, this is clearly a bug.

I have never seen this. Any chance of a reproducible test?

BTW, I am assuming you are experiencing this problem with RC1. There have been a few changes recently to how `ReadDirectory` works (which is the native WinFsp `readdir`), but they should not affect the `opendir`, `readdir`, `releasedir` sequence.

**Comment by billziss-gh** [comment]
Hi, @netheril96. It seems I responded without fully thinking.

Does this problem happen when you try to remove a directory?

There was indeed a problem with the FUSE `CanDelete` implementation which has been fixed in RC2: a964ab1b7358e80151e4287ccd0c3b863295e8b0

**Comment by netheril96** [comment]
Yes，rmdir is the culprit.

**Comment by billziss-gh** [comment]
Thanks for confirming.

**Comment by netheril96** [comment]
I tested on macOS and Linux and found that the FUSE on those systems (which should be the reference) just directly call the `rmdir` callback. In other words, in a correct FUSE program, it should check whether the directory is empty inside the `rmdir` call, instead of relying on the fuse layer to do the check. For stricter conformance, WinFsp should not do the check either.

**Comment by billziss-gh** [comment]
I agree with you about `rmdir` semantics on other systems. [I am actually quite familiar with the internals of FUSE on both Linux and OSX.]

However things are not so simple on Windows. On Windows there is no simple `rmdir` or `unlink` equivalent. Instead the `RemoveDirectoryW` and `DeleteFileW` API's are really the sequence of the following file system IRP's:

- `CREATE`: open the file/directory to be deleted
- `SET_INFORMATION [FileDispositionInformation]`: set the "disposition" flag on the file/directory
- `CLEANUP`: if the file has the "disposition" flag set, delete the file/directory
- `CLOSE`: close the file/directory

Windows expects that the "directory empty/not-empty" test will be done during `SET_INFORMATION [FileDispositionInformation]` time. If the test succeeds it expects to see `STATUS_SUCCESS`, if the test fails it expects to see `STATUS_DIRECTORY_NOT_EMPTY` (or other error code). If the file system returns `STATUS_SUCCESS` it must also set the "disposition" flag, so that when Windows finally sends `CLEANUP` the file system can finally remove the file/directory. [In fact at this point the file system cannot communicate failure to the rest of the kernel, which is somewhat interesting!]

The WinFsp-FUSE layer must adhere to Windows file system standards. For this reason it implements the `CanDelete` operation (which is the user mode equivalent of `SET_INFORMATION [FileDispositionInformation]`) as a `readdir` call to verify that a directory is not empty. And you actually get the `rmdir` and `unlink` calls during `Cleanup`.

**Comment by billziss-gh** [comment]
@netheril96 I am closing this as I the fix is already in RC2, which should be out soon. Please reopen if you find that the problem persists after release of RC2.

**Comment by billziss-gh** [comment]
Hi, @netheril96. This is another problem that the RC2 should have fixed. Please let me know if the problem persists.

https://github.com/billziss-gh/winfsp/releases/download/v1.0RC2/winfsp-1.0.17039.msi
