### ISSUE TITLE
GetFinalPathNameByHandle with VOLUME_NAME_DOS doesn't work on MemFS but works on SSHFS

### ISSUE THREAD

**Issue by viktor-prutyanov** [billziss-gh/winfsp#410]
## Bug Report

According to [MSDN](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew) `GetFinalPathNameByHandle` retrieves the final path for the specified file. Call with `VOLUME_NAME_DOS` flag should return the path with the drive letter.

`GetFinalPathNameByHandle` with `VOLUME_NAME_DOS` doesn't work on MemFS but works on SSHFS.

### How to Reproduce

Here is small sample with `GetFinalPathNameByHandle` with `VOLUME_NAME_DOS` invocation:
https://gist.github.com/viktor-prutyanov/1d8680f19e200d0079cb47bf8057bf4a

MemFS:
1. `C:\Program Files (x86)\WinFsp\bin>memfs-x64.exe -m M:`
2. `touch M:\testfile.txt`
3. `GetPath.exe M:\testfile.txt`

SSHFS:
1. `net use S: \\sshfs\user@192.168.1.8`
2. `touch S:\testfile.txt`
3. ` GetPath.exe S:\testfile.txt`

### Behaviors

MemFS:
```
GetPath.exe M:\testfile.txt
GetFinalPathNameByHandle (error 1005)
```
Error 1005 means
> ERROR_UNRECOGNIZED_VOLUME (1005):
> The volume does not contain a recognized file system. Please make sure that all required file system drivers are loaded and that the volume is not corrupted.

SSHFS:
```
GetPath.exe S:\testfile.txt
The final path: \\?\UNC\sshfs\vp@192.168.1.8\testfile.txt
```

NTFS:
```
GetPath.exe C:\Windows\System32\notepad.exe
The final path is: \\?\C:\Windows\System32\notepad.exe
```

### Environment

- OS version and build: 10.0.17763
- WinFsp version and build: 1.9.21096.0

**Comment by billziss-gh** [comment]
The [`GetFinalPathNameByHandleW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew) API (unfortunately) does not recognize drives created by [`DefineDosDeviceW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-definedosdevicew). It only works for drives created via the Mount Manager or network drives.

The problem you are seeing is because you mount MEMFS as a drive M: using the option `-m M:`. This results in a local drive M: created via `DefineDosDeviceW`, which `GetFinalPathNameByHandleW` does not recognize.

WinFsp also provides the ability to mount a file system as a drive via the Mount Manager. If you use the syntax `\\.\M:` for the mount point (so `-m \\.\M:` for the MEMFS mount option), you instruct WinFsp to create a global drive M: using the Mount Manager. Such a drive is recognized by `GetFinalPathNameByHandleW`; the drawback is that the created drive is global (i.e. visible to everyone) and it requires Administrator privileges to be created.

I hope this explains what you are seeing.

**Comment by viktor-prutyanov** [comment]
Thank you!
