### ISSUE TITLE
Generic way to unmount WinFsp file systems

### ISSUE THREAD

**Issue by netheril96** [billziss-gh/winfsp#47]
Currently the only way I know for unmounting is to send CtrL-C to my application, but is there any other way? I cannot simply terminate the process because it may have its own cleanup to do. Best if it can be on a command line so that I can automate some testing tasks.

**Comment by billziss-gh** [comment]
The proper way to unmount a file system that uses WinFsp-FUSE is by sending it a Ctrl-C. On Windows this is done by calling [`GenerateConsoleCtrlEvent`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683155(v=vs.85).aspx). On Cygwin you can also use `kill` or `pkill` to send it a `SIGTERM`, especially if you run it as a Cygwin daemon.

An even better way is to consider running your file system under the WinFsp.Launcher service. The launcher runs your file system as a service (under the credentials of the SYSTEM account) and knows how to start/stop it. You would use commands like `net use Z: \\securefs\...` to mount your file system and `net use Z: /delete` to unmount it (or you could do it from Explorer's map/disconnect drive).

One extra benefit of going this route is that volume drives created this way are visible to all accounts/processes in the system. Drives created by a file system running under your account are only visible to your account. They are not even available to you if you momentarily become Administrator (e.g. by starting an Administrator prompt). This is because by default Windows creates drives in a local account namespace. See [`DefineDosDeviceW`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa363904(v=vs.85).aspx).

The only gotcha with this approach is that you would have to implement proper security descriptors for your file system, because it would now run under the SYSTEM account and it would no longer create/access files under your account credentials. You would also need backup/restore privileges enabled. Despite the short-term pain, this is my preferred approach because it really makes a user mode file system behave like a system component.

**Comment by netheril96** [comment]
The problem is sometimes I lose the console window and I don't know how to send it the CtrL-C break event.

**Comment by billziss-gh** [comment]
> The problem is sometimes I lose the console window and I don't know how to send it the CtrL-C break event.

By "lose" do you mean the console window is closed? How does the console app survive then (unless you do `FreeConsole` somewhere)? In any case `GenerateConsoleCtrlEvent` is not the most reliable method, because it cannot be used by an arbitrary process to send the signal.

I do not have a good answer for you. When designing the file system control mechanism I assumed one of the following scenarios:

- A developer that is developing/debugging their file system: killing the process from the debugger should clean up all associated resources.

- Someone who runs the file system from the command line, primarily for testing purposes. Ctrl-C should be available in this case.

- Someone who runs the file system as a Cygwin daemon. Cygwin has its own signal mechanism (independent from `GenerateConsoleCtrlEvent`). The FUSE layer has explicit support for this and `kill`, `pkill` just work.

- The file system running under the control of the WinFsp.Launcher service. Because all file systems started under the launcher share a console, the launcher can send them Ctrl-Break events using `GenerateConsoleCtrlEvent`.

It seems you are looking for a method to orderly shutdown a file system just by knowing its process ID. I can think of a couple of ways that this could be implemented:

1. There is an internal event called `FspServiceConsoleModeEvent` which stops the file system if it gets signaled. The event is currently unnamed and inaccessible from processes outside the file system. We could instead give it a well known name in the NTOS namespace (e.g. `"FspServiceConsoleModeEvent.<PID>"`) and an appropriate security descriptor, so that other processes can open it and signal it. While this sounds like an elegant approach I am worried about any security implications.

2. Use `CreateRemoteThread` to invoke some code within the file system process that signals the event (this is actually how `GenerateConsoleCtrlEvent` works, it starts a remote thread into a process executing an internal Windows API called `CtrlRoutine`). In fact using `CreateRemoteThread` to invoke `CtrlRoutine` without `GenerateConsoleCtrlEvent` may be all that is required. See this interesting project: http://latenighthacking.com/projects/2003/sendSignal/.

Perhaps we can adapt one of these (or other) ideas to build an `fskill` program.

**Comment by netheril96** [comment]
What is the security implications of the first approach? Anyone who can forcible terminate the process should be able to ask it to quit nicely.

**Comment by billziss-gh** [comment]
> What is the security implications of the first approach? Anyone who can forcible terminate the process should be able to ask it to quit nicely.

This is what I am wondering as well. I need to spend some time thinking about this.

I think the right thing to do here is to derive the security descriptor for the named event from the one in the process object. Obviously the access rights are different, but if the process object ACL specifies that a SID has the `PROCESS_TERMINATE` right, then the same SID should have the `EVENT_MODIFY_STATE` in the event object ACL. Something along those lines.

**Comment by clicx** [comment]
I also have the same problem, if I mount driver letter through explorer (like the showcast in your home page), the driver letter can't be removed, by explorer "Disconnect network drive", it can't find any drive, if I use net use z: /delete, it can't remove as well, even kill process.

**Comment by billziss-gh** [comment]
Sorry for late response. I am on vacation.

You probably have Dokany installed. Dokany interferes with WinFsp unmapping drives. See issue #17. Also this link: http://blogs.interfacett.com/changing-the-network-provider-order-in-windows-10

**Comment by netheril96** [comment]
Any updates? I still cannot run automatic integration tests on Windows.

**Comment by billziss-gh** [comment]
@netheril96 I have not progressed on this. The main reason is that I have not found it to be a problem in my use. I tend to integrate all my file systems with the launcher (`WinFsp.Launcher` service) which neatly solves this problem.

I have been mulling the possibility of creating a command line utility for WinFsp that could be used for various tasks including killing running file systems. Something along the lines of:

```
usage: fsptool COMMAND [OPTIONS] ARGS...

commands:
    lsvol       list file system devices (volumes)
    list        list running file system processes
    kill        kill file system process
    uid         get current POSIX UID
    gid         get current POSIX GID
    uidtosid    get SID from POSIX UID
    sidtouid    get POSIX UID from SID
    permtosd    get security descriptor from POSIX permissions
    sdtoperm    get POSIX permissions from security descriptor
    ...
```

Listing and killing file system process would work by using the `FspServiceConsoleModeEvent.<PID>` approach that we discussed earlier.

Unfortunately I have been and still am busy with other tasks and have not had time to look into this. Perhaps you have time to look into this yourself? As always I would provide help and support.

**Comment by netheril96** [comment]
Sorry, I am not familiar with Windows development.

**Comment by philrykoff** [comment]
I just started using jnr-fuse, which wraps WinFsp in a set of Java classes. Everything just works - with the exception of unmounting (https://github.com/SerCeMan/jnr-fuse/issues/28). 

For the other OSses (Linux, MacOS) there are callable APIs to unmount the file systems, but as there is no direct way to send CTRL C to a process in Java, this is not the case for WinFsp / Windows. It might be possible by invoking another native executable which would perform that task, but this would add another native third party dependancy.

A callable API instead of CTRL C would really help here. From my point of view, the fsptool would help, too (it would be shipped with the WinFsp installer, aye?). Would it be possible to prioritize the "kill" command in fsptool? 😁

**Comment by philrykoff** [comment]
Thanks @billziss-gh for the quick and positive response on the other ticket. 👍 

Just wanted to let folks following this ticket now that.

> Under WinFsp-FUSE fuse_exit is able to cleanly exit and unmount the file system.
> For example, here is how I handle FUSE unmount in cgofuse:
> https://github.com/billziss-gh/cgofuse/blob/v1.0.3/fuse/host.go#L459-L492

**Comment by billziss-gh** [comment]
I believe that @netheril96 wants an external method for stopping the file system, akin to `umount(8)` or `kill(1)`.

**Comment by billziss-gh** [comment]
File systems that need this functionality should use the launcher (WinFsp.Launcher) functionality. See the [Service Architecture](https://github.com/billziss-gh/winfsp/wiki/WinFsp-Service-Architecture) document.

Closing this as it is unlikely that this will be added.

**Comment by kkeybbs** [comment]
I found fsp_fuse_signal_handler(0) in winfsp-x86.dll works.

**Comment by kjrandez** [comment]
I'm writing a piece of software which presents a filesystem representing it's internal data structures.

The user should be able to mount and unmount the filesystem at will. Neither ctrl-c nor running the FS as a service is suitable. There should be something in the API to do it, or else a CLI (like FUSE's fusermount).

**Comment by earonesty** [comment]
if you want to have multiple mounts for a multi-tenant system with user-specific behavior, preferences & content ... it makes no sense to mount as a system drive.
