### ISSUE TITLE
Is it possible to get the process id of the originating process?

### ISSUE THREAD

**Issue by joemooney** [billziss-gh/winfsp#53]
Maybe a dumb question but I would like to know the  process id (and maybe user id) making the filesystem request. I am curious if I could write something that could log all the files read/written by a process (and its children). So if I had a script that read A and B and updated C and created D, I would like to store that information.  

p.s. this is brilliant work!

**Comment by billziss-gh** [comment]
No question is dumb. Thanks for asking it!

**Short answer**: WinFsp does not make the process id available and it only makes the user id available during `Create` (and `Rename`) requests. WinFsp could be extended to pass the process id during `Create` (and `Rename`) requests.

**Long answer**: In the Windows file system security model access checks are done during `Create` (with few exceptions). These checks involve checking the access token of the thread making the `Create` request against the file being created/opened. The access token contains information about the requesting user, but not the requesting process.

WinFsp could be extended to also pass the process id along with the access token during `Create` requests. It does not do so currently, because the Windows file system security model does not require it. I can however see a specialty file system that restricts access to a specific process or processes, in which case the process id would be useful.

It should be noted here that passing the process id would only be useful in the case of `Create` (and `Rename` if you want to use it for access checks). The reason is that file system requests as issued by a process do not always correspond to file system requests as received by a user mode file system. The easiest case to see this is when file caching is enabled: one or more processes may read/write a file, but all these requests may be serviced from the cache; the OS will issue its own reads/writes to fill/flush the cache when it sees fit.

> So if I had a script that read A and B and updated C and created D, I would like to store that information.

The best way to do this may not be a user mode file system, but a "filter". Look into this: [FileSpy](http://www.zezula.net/en/fstools/filespy.html). It's a brilliant tool that I also use at times when debugging issues with WinFsp.

**Comment by joemooney** [comment]
Thanks for the response. I had not thought of the nuances of caching. FileSpy looks interesting. I would like (in my dreams) to replicate the functionality of a tool called clearmake that is part of clearcase. For every .o/.exe etc it can tell you all the files that were read/written (and commands and env vars). It relies on the virtual filesystem that comes with clearcase. Sadly, clearcase is out of vogue. I looked at things like http://gittup.org/tup/ (among several others) which works fine at home but not where I want it. The inspection capability of clearmake was for me the killer app for the clearcase virtual filesystem. A versioning filesystem then has a simple language for specifying what view of the world you want to see is a pure joy. It got welded to a specific application that became a piece of bloatware while it itself did not receive any love for over 25 years and is dying from neglect. I realize from your perspective I am conflating two distinct needs  - it is just that in the domain of building software (or building files from files) having both monitoring and version presentation at the filesystem level makes the most sense.

**Comment by fsgeek** [comment]
In fact, having been down this road, what you really want (in create and set information, where you know that the credentials are right) is the _thread_ ID.  This ensures that even if the thread is impersonating, you can get the right credentials, whereas the process might have a different set of credentials. 

The challenging case is when SMB is exporting your file system - it will impersonate in only the two paths (and set information is because rename and hard link can cause deletion as a secondary effect, which means the file system needs to do a security check).  Sometimes you have to save away a handle to that token for other things as well (like directory change notifications, where you can't tell someone monitoring a directory about changes for which they don't have traverse permission to get to the directory.  NTFS does this.)

From the thread ID you can find the process ID, the security token, the image, any loaded DLLs (if you're doing white/black listing, for example), etc.

**Comment by billziss-gh** [comment]
@joemooney wrote:

> I would like (in my dreams) to replicate the functionality of a tool called clearmake that is part of clearcase. For every .o/.exe etc it can tell you all the files that were read/written (and commands and env vars). It relies on the virtual filesystem that comes with clearcase. Sadly, clearcase is out of vogue. I looked at things like http://gittup.org/tup/ (among several others) which works fine at home but not where I want it.

I remember looking at tup a couple of year ago and being intrigued by it. I am not familiar with clearcase/clearmake, but a bit googling points me to MVFS (Multi-version File System), which intrigues me even more. Unfortunately the documentation that I am finding does not describe the file system enough to see how it is used in practice.

[BTW, WinFsp provides a FUSE interface that can be used from Cygwin, so I am wondering how hard it is to port tup on Cygwin...]

> I had not thought of the nuances of caching.

You could disable caching in a WinFsp file system. Then (assuming we add process/thread ID's to WinFsp for `Create` / `Open` / `Rename` calls) you could store the process/thread ID during a `Create` / `Open` and then figure out what it was in `Read` / `Write`.

> I realize from your perspective I am conflating two distinct needs - it is just that in the domain of building software (or building files from files) having both monitoring and version presentation at the filesystem level makes the most sense.

If you are looking at both monitoring **and** versioning capabilities then perhaps a file system makes more sense for you than a filter.

@fsgeek wrote:
> In fact, having been down this road, what you really want (in create and set information, where you know that the credentials are right) is the thread ID. This ensures that even if the thread is impersonating, you can get the right credentials, whereas the process might have a different set of credentials.

It should be easy to return thread ID instead of process ID and then use something like `GetProcessIdOfThread` to get the process ID when required.

Note that WinFsp already passes the access token of the calling thread during `CREATE` (from `AccessState->SubjectSecurityContext`) and `SET_INFORMATION/Rename` (using `SeCaptureSubjectContext`) to the user mode file system (access checks are done in user mode in WinFsp). So there is perhaps less need to pass thread ID instead of process ID.

**Comment by joemooney** [comment]
With MVFS you have a drive that has as top directories one or more views. Each view can be mounted as a separate drive as a convenience. A view is a set of rules (top down). Each rule is a triplet which specifies either file|directory|both, a pattern (e.g. *.cpp), and a selection (e.g. a label). Starting at the top directory the version of that directory selected by the rules is resolved. If no rule matches you cannot see the file/directory. As you change directory, the selections are resolved. As you open a file, if it is not in the cache it is downloaded from the server (may be the same machine).  Each file/directory is a tree of versions. The view rules selects a specific version (or none). Changes create new nodes on the branch selected. You can apply labels and other metadata. That is the gist of it. It is much more powerful. In theory, if I understand the alternate stream data information you point to, they could be used to support the entire implementation without need for a server. Each file/directory would be self contained with its entire history and metadata and then the filesystem would present the appropriate contents based on the set of rules in place. Something along those lines (whether in the cloud or via ADS) is what I envisioned when I read about your (brilliant) WinFSP. Having the pid/threadid available would just help solve a different problem, which is not relevant to much of today's world where incremental compilation/linkage means what you read/wrote during one execution cycle is not necessary the whole story. 

Separately, Microsoft is working on something related called GVFS
https://blogs.msdn.microsoft.com/bharry/2017/02/03/scaling-git-and-some-back-story/
https://blogs.msdn.microsoft.com/visualstudioalm/2017/02/03/announcing-gvfs-git-virtual-file-system/

**Comment by billziss-gh** [comment]
> With MVFS you have a drive that has as top directories one or more views. Each view can be mounted as a separate drive as a convenience. A view is a set of rules (top down). Each rule is a triplet which specifies either file|directory|both, a pattern (e.g. *.cpp), and a selection (e.g. a label).

Thanks for the explanation. I think I can see how a file system like the one you describe could be used to select specific versions of a large software project (somewhat like how we do `git checkout BRANCH` with git, except that git has to checkout all files in the branch, which does not scale well with very large projects).

> In theory, if I understand the alternate stream data information you point to, they could be used to support the entire implementation without need for a server. Each file/directory would be self contained with its entire history and metadata and then the filesystem would present the appropriate contents based on the set of rules in place. Something along those lines (whether in the cloud or via ADS) is what I envisioned when I read about your (brilliant) WinFSP.

Are you thinking about building a new version control system? Or building a file system on top of an existing one? I believe building a new VCS is a huge undertaking.

> Separately, Microsoft is working on something related called GVFS.

Thank you for the link. I was not aware of GVFS. It looks like a hierarchical storage solution, where the git server is playing the role of the second tier storage.

If I was doing this I would use FUSE to bootstrap it on OSX/Linux and then port it to WinFsp-FUSE or even to the WinFsp native API for maximum performance/compatibility. This way everyone in the git world would benefit, not just Windows folks.

**Comment by joemooney** [comment]
I need to look more at GVFS. My initial thought was a clearcase like facade using WinFSP on top of git as a vehicle to transition off clearcase onto git but keep all the existing tools working. My biggest issue in leaving clearcase is build capability that the filesystem enables. It sounds like GVFS is intecepting file system calls, albeit for a different purpose.

**Comment by billziss-gh** [comment]
Commits fc1586eb82fea618b775600840e3301b4c4a3837 to 2227429d8e6c893490d98a952cf445d806496d0d add support for fetching the originating PID.

The originating PID is only available during `Create`/`Open` and `Rename`. It can be accessed using the new API `FspFileSystemOperationProcessId`. Note that it is possible for this PID to be `0`.

The FUSE layer also includes the originating PID in `fuse_context`.

**Comment by pavel-franc-me** [comment]
Hi, I have used beta release of WinFSP, v 1.2. but pid of the caller process doesn't work for me. I have always gotten pId of my user space process, in this case passthrough-x86.exe. Do you have some advice?

**Comment by billziss-gh** [comment]
@pavel-franc-me have you used the latest beta (`v1.2B2`)? This was an issue in the previous beta (`v1.2b1`), but it has now been fixed.

Link to `v1.2B2`:

https://github.com/billziss-gh/winfsp/releases/tag/v1.2B2

**Comment by pavel-franc-me** [comment]
Hi, You're right, have used winfsp-1.2.17274.msi, After I downloaded and installed winfsp-1.2.17298.msi, all is correct. Thank you very much for your advice.

**Comment by billziss-gh** [comment]
@pavel-franc-me thanks for confirming.

**Comment by psantosl** [comment]
Hi @billziss-gh,

Is this accessible from the C# layer? We're really interested on obtaining both pid and user :-)

**Comment by billziss-gh** [comment]
See [`FileSystemBase.GetOperationProcessId`](https://github.com/billziss-gh/winfsp/blob/v1.7/src/dotnet/FileSystemBase.cs#L1207-L1216).

**Comment by paratype-fonts** [comment]
Based on the earlier information in this thread, file system caching makes getting the process ID for read operations not that useful. With that, it seems that disabling caching would make obtaining the process ID quite meaningful. 

If my interpretation is correct, could FileSystemBase.GetOperationProcessId (and the corresponding C method) return the originating process ID for read and close operations when the file system caching is disabled?

In some usage scenarios knowing IDs of processes that are trying to read is critically important for the purpose of data protection.
