### ISSUE TITLE
capitalization of FUSE struct names/types/keywords?

### ISSUE THREAD

**Issue by samkelly** [billziss-gh/winfsp#57]
For a number of performance and stability reasons, I'm trying to convert https://github.com/mafintosh/fuse-bindings to use WinFSP instead of Dokany. I noticed that a number of the FUSE structs and keywords, like `FUSE_STAT` and `FUSE_OFF_T`, etc., are all lowercase in WinFSP, but are in all caps in Dokany and the FUSE code in fuse-bindings that integrates with all 3 OSes. Is it a convention to capitalize these normally, but you broke this convention in WinFSP, or is fuse-bindings and/or Dokany doing something weird/non-standard?

also things like `fuse_mode_t` instead of `mode_t`, etc?

**Comment by billziss-gh** [comment]
Thanks for trying WinFsp.

Regarding `FUSE_STAT` and `FUSE_OFF_T` symbols: I do not think these symbols exist in the original libfuse implementation. These symbols are needed because the `struct stat` and equivalent symbols from MSVC are inadequate (the ones from Cygwin are ok).

Since there is no standard for such symbols Dokany chose all capital letters for these symbols. WinFsp chose lowercase letters, which is the convention for API's found on POSIX (or UNIX-like) systems. Since FUSE originated on a POSIX (or UNIX-like) system I felt it made more sense.

**Comment by samkelly** [comment]
@billziss-gh thanks for clearing this up!

**Comment by billziss-gh** [comment]
You are welcome. Let me know if you need any additional information or whether we can close this.

**Comment by samkelly** [comment]
You can close this -- thanks!
