### ISSUE TITLE
External Change Notifications and Cache Invalidation Support

### ISSUE THREAD

**Issue by tstordyallison** [billziss-gh/winfsp#68]
Is there any way I can notify Windows of a change to a directory and/or file?

The file system I've been developing can be informed of changes to what it is representing as a 'file', so it would be great if I could relay that on to applications that are using the change notification APIs (https://msdn.microsoft.com/en-us/library/windows/desktop/aa364417(v=vs.85).aspx etc).

**Comment by billziss-gh** [comment]
WinFsp does this automatically. There is nothing that your file system needs to do in order to support change notifications.

For an example: try copying files in a command prompt while you are watching the same directory from Explorer; you will see the directory getting populated in Explorer, because it is receiving change notifications.

**Comment by billziss-gh** [comment]
> The file system I've been developing can be informed of changes to what it is representing as a 'file'

Rereading this I am realizing that you may be looking for a way to inform the OS (and apps running on it) of changes that happen outside that OS (e.g. by a different computer on a network). There is no way to do this currently in WinFsp.

**Comment by tstordyallison** [comment]
Yep - exactly. The data I'm showing using winfsp is really stored in a distributed database behind the scenes and can be modified separately.

Any desire to add this to winfsp? Any technical reasons why it wouldn't be possible? 

By no means a showstopper, but just something that would be nice to have. My users can press F5 for now :)

**Comment by billziss-gh** [comment]
> Any desire to add this to winfsp? Any technical reasons why it wouldn't be possible?

It is certainly desirable and possible, although perhaps non-trivial.

I have been thinking about adding cache invalidation (similar to FUSE `fuse_lowlevel_inval_*`) API's to WinFsp for some time now, to support file systems that would like to use the NTOS Cache Manager but have consistency issues (like yours). What you are asking is a natural extension of that, when not only we inform the kernel about the change (and the kernel invalidates its caches, etc.), but also any user mode apps listening on the file system.

As an added benefit some of my file systems could use this as well ;)

**Comment by tstordyallison** [comment]
From our friends at libfuse on this topic: 
https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE

**Comment by tstordyallison** [comment]
It looks like the above talks about taking this further than I really expected - where the kernel passes on the 'interest' from the userspace watcher to the FUSE filesystem (rather than it just being a an implicit part of the invalidation APIs. 

This makes sense if the cost of watching everything is high (e.g. their example being CIFS/SMB, which natively supports this on Windows today as part of the protocol, forwarding the watch to the remote server). 

I think shooting for something 'built in' to the invalidation API would be nice first, as this would allow for userspace filesystems that invalidate the cache correctly to magically support watchers straight away. 

Forwarding on the watcher detail could be separate piece of work for later (and maybe at some point if the libfuse API is settled for it, would could plumb that through too).

**Comment by billziss-gh** [comment]
I just read the article. Very interesting. Is any of this baked in libfuse yet? A search of `FUSE_FSNOTIFY_*` symbols did not reveal anything relevant.

I agree that a useful first step would be to get an invalidation API. Unfortunately something like this would require me to focus on the WinFsp internals uninterrupted for an extended period of time (say a couple of weeks) to understand the problem and retrofit the necessary support. I have not have found the necessary time for that yet.

**Comment by tstordyallison** [comment]
I did a similar search and didn't find anything either - I was just digging some more now to find some of the original posts. 

Some archived chat from the mailing list. [[link](http://fuse.996288.n3.nabble.com/Design-of-fsnotify-for-FUSE-nfs-and-cifs-when-how-to-send-a-watch-td13880.html)]

@stefbon around to give as update RE the patch to libfuse?

**Comment by billziss-gh** [comment]
I am sketching a potential design for this feature. I may update this post in the future.

## Notification API/Protocol

I propose the following API:

```
NTSTATUS FspFileSystemNotify(PWSTR FileName);
```

The `FileName` would be used to identify a particular open file within the FSD that we wish to notify. The FSD already maintains an internal map of `FileName->FileNode` for other purposes.

A potential problem is that the internal map may change at any time (e.g. due to a rename operation), while the file system is issuing `FspFileSystemNotify`. The potential interactions with the rest of the FSD must be carefully thought out to ensure that the file system cannot notify the wrong file.

The corresponding `FSCTL` protocol message would be an `FSP_FSCTL_NOTIFY` message sent to the fsctl device (i.e. the same device where `FSP_FSCTL_TRANSACT` messages are sent).

An alternative API which allows to specify the change in more detail is the following:
```
NTSTATUS FspFileSystemNotify(PWSTR FileName, ULONG Filter, ULONG Action);
```

Where `Filter` is one of the `FILE_NOTIFY_CHANGE_*` constants and `Action` is one of the `FILE_ACTION_*` constants as documented in [`FsRtlNotifyFullReportChange`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlnotifyfullreportchange).

## Cache Invalidation

Cache invalidation involves invalidating all metadata and data caches.

- Invalidating metadata caches can be achieved using the various internal `FspFileNodeInvalidate*` calls.
- Invalidating data caches can be achieved using the same technique as the one used by `FspFileNodeSetFileInfo` when `CcSetFileSizes` fails.

## Directory Change Notifications

Issuing a directory change notification should be feasible using the internal `FspFileNodeNotifyChange`.

**Comment by billziss-gh** [comment]
I am sketching a potential design for this feature. I may update this post in the future.

## Notification API/Protocol

I propose the following API:

```
NTSTATUS FspFileSystemNotify(FSP_FILE_SYSTEM *FileSystem, PWSTR FileName, BOOLEAN Recursive);
```

The `FileName` would be used to identify a particular open file within the FSD that we wish to notify. The FSD already maintains an internal map of `FileName->FileNode` for other purposes.

A potential problem is that the internal map may change at any time (e.g. due to a rename operation), while the file system is issuing `FspFileSystemNotify`. The potential interactions with the rest of the FSD must be carefully thought out to ensure that the file system cannot notify the wrong file.

The corresponding `FSCTL` protocol message would be an `FSP_FSCTL_NOTIFY` message sent to the fsctl device (i.e. the same device where `FSP_FSCTL_TRANSACT` messages are sent).

An alternative API which allows to specify the change in more detail is the following:
```
NTSTATUS FspFileSystemNotify(FSP_FILE_SYSTEM *FileSystem, PWSTR FileName, BOOLEAN Recursive, ULONG Filter, ULONG Action);
```

Where `Filter` is one of the `FILE_NOTIFY_CHANGE_*` constants and `Action` is one of the `FILE_ACTION_*` constants as documented in [`FsRtlNotifyFullReportChange`](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/nf-ntifs-_fsrtl_advanced_fcb_header-fsrtlnotifyfullreportchange).

## Cache Invalidation

Cache invalidation involves invalidating all metadata and data caches.

- Invalidating metadata caches can be achieved using the various internal `FspFileNodeInvalidate*` calls.
- Invalidating data caches can be achieved using the same technique as the one used by `FspFileNodeSetFileInfo` when `CcSetFileSizes` fails.

## Directory Change Notifications

Issuing a directory change notification should be feasible using the internal `FspFileNodeNotifyChange`.

**Comment by stefbon** [comment]
Why do I get this email? I don't want to contribute.

You better just ask.

S. Bon

Op do 24 sep. 2020 om 01:07 schreef Bill Zissimopoulos <
notifications@github.com>:

> I am sketching a potential design for this feature. I may update this post
> in the future.
> Notification API/Protocol
>
> I propose the following API:
>
> NTSTATUS FspFileSystemNotify(FSP_FILE_SYSTEM *FileSystem, PWSTR FileName, BOOLEAN Recursive);
>
>
>

**Comment by billziss-gh** [comment]
@stefbon you are probably getting emails because you are subscribed to this issue. (To clarify: I did not subscribe you.) The emails will likely stop once you unsubscribe.

**Comment by stefbon** [comment]
I am? I see myself in the participants list, but I cannot remember... It's
true though that I'm an expert on FUSE and making fs change notify work
together.
My conclusion: is does not go together. You have to change the kernel on
several places (with linux: the fsnotify and the fuse subsystems), and than
still the result is very limited.

Better is to use a special fs notify daemon which handles all the fs notify
requests (and is a system service) and let fuse filesystems make a
connection to it via socket when they
start, and when a fsnotify watch is set on a fuse flesystem, the watch with
the right parameters is send to the fuse filesystem to inform.
The fuse filesystem can then take the action it needs. It can always ignore
it (because it does not support fs change notify requests....) and it can
the network specific call to set the watch on the server, and receive
notifications from server, and forward those to the service, which informs
the user applications which are interested in these events.

See:

About making fsnotify and fuse work (old work):

https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE

Stef

**Comment by billziss-gh** [comment]
@stefbon thank you for your insights regarding a change notification mechanism to Linux. Much appreciated.

**Comment by billziss-gh** [comment]
I am closing this as this functionality has now been implemented. It is currently in the pvt-notify branch, but I will be merging into master soon. Expect a beta release with this feature in a few weeks.
