### ISSUE TITLE
Add version number to WinFsp API and compatability between different WinFsp Version

### ISSUE THREAD

**Issue by yogendersolanki91** [billziss-gh/winfsp#70]
While adding new feature or improving the existing feature, it might possible we end up breaking application that are running with older version. It is also required  that we should not change interface signature that is used by file system implementation in user mode. This will help developer to get rid of annoying crash that is happening currently due to function signature mismatch.

**Comment by samkelly** [comment]
on that note, would be cool if the installer was capable of "upgrading" an existing installation without first having to manually uninstall

**Comment by billziss-gh** [comment]
@yogendersolanki91 wrote:
> Add version number to WinFsp API

There is already a versioning API: `FspVersion`. It will return `0x00010000` for version `1.0` (the current version).

> It is also required that we should not change interface signature that is used by file system implementation in user mode. This will help developer to get rid of annoying crash that is happening currently due to function signature mismatch.

I agree completely and I apologize for this. When I released version "WinFsp 2017 RC1" (`1.0.17009`) I erroneously thought that the API was final. Unfortunately I then discovered that `ReadDirectory` had what I considered a design flaw and decided to fix it. At that point I had two options:

1. Immediately increase the major version to `2.0`, since this was a breaking API change.
2. Keep the major version number the same (`1.0`) (since I had not released the final "WinFsp 2017" version) and publicize the API change.

I mulled it over and decided that option (2) was the best one as in my mind the final "WinFsp 2017" version had not been released yet. This final "WinFsp 2017" has now been released and it is `1.0.17072`.

Again I apologize and I make the promise that:

(From https://github.com/billziss-gh/winfsp/blob/v1.0/Changelog.asciidoc)
> The API is now **FROZEN**. Breaking API changes will receive a major version update (`2.0`). Incremental API changes will receive a minor version update (`1.x`).

@samkelly wrote:
> on that note, would be cool if the installer was capable of "upgrading" an existing installation without first having to manually uninstall

I really tried to make this happen at some point, but it was not obvious to me how to do it. The issue is that if the FSD is loaded it cannot be unloaded without a reboot. While Windows allows the deletion of the executable file of a loaded driver, it does not allow the deletion of a running service. An FSD is also a Windows service (try `sc query WinFsp`).

This means that upgrades would succeed if the FSD was not loaded and fail when the FSD was loaded. In the end I chose to simplify things by disallowing upgrades. It might be possible to improve the installer so that it can do a reboot and continue the installation of the newer version during an upgrade, but I am not a Windows installer expert.

**Comment by yogendersolanki91** [comment]
> There is already a versioning API: FspVersion. It will return 0x00010000 for version 1.0 (the current version).

I think i missed that. But if in that case it should fail the mount process instead of reaching a point where it crashes the application. I noticed with memfs that even  if version mismatch is there process keeps running and mounted disk does not work. It would be better to refuse mount process if version in not matching.

**Comment by billziss-gh** [comment]
The file system could do such a check itself using `FspVersion` and bail out if it does not like the version.

As discussed though, going forward the API will remain backwards compatible (unless there is a major version number change). Therefore the need for strict API checking diminishes and I would not recommend it.

Here is what backwards compatible means:

- API **and** ABI compatibility should be maintained (i.e. no recompiles).
- New API's may be added, but existing ones should not be removed (API ordinal numbers may change however, imports should always be done by name).
- New file system operations (`FSP_FILE_SYSTEM_INTERFACE`) may be added, but existing ones should not be removed.
- Existing API's and file system operations may not change behavior / semantics.

**Comment by yogendersolanki91** [comment]
Seems ok to me. Closing the issue.
