### ISSUE TITLE
.NET Wrapper for WinFsp

### ISSUE THREAD

**Issue by yogendersolanki91** [billziss-gh/winfsp#71]
Working on this. I will push it after fixing some bug that came after API change and due to some implementation issue of mine.

**Comment by yogendersolanki91** [comment]
Please assign it to me. Thanks.

**Comment by billziss-gh** [comment]
Thank you for your work. Assigning as requested.

**Comment by billziss-gh** [comment]
BTW, I know we had a private discussion about this in the past, but since this is a rather big task, I would prefer if we had a public discussion on how you are structuring this and your general design.

This would allow us to ensure that it fits the current WinFsp concepts and ease the task of integrating the wrapper with the rest of WinFsp.

**Comment by yogendersolanki91** [comment]
Yeah sure. I would like to get some comment and it is actually needed to have some discussion. As I am not doing this in standard way of wrapping the function and data structure using internal marshalling of C#.  In next post I will post my design.

**Comment by yogendersolanki91** [comment]
I have written .NET wrapper using the C++/CLI. I prefer this way because it allows us to control memory and data structure marshaling with more granularity compared to standard wrapper writing. It also easy to debug memory corruption with C++/CLI. 

Basic design of the wrapper is to implement a file system in C++/CLI that invokes function of User-Mode file system interface implemented in .NET. For each WinFsp file system callback function we will have an equivalent function in interface. 




Fro all the buffer like (Read,Write,ReadDirectory) buffer there is a HandlerClass which is wrapper around actual native buffers and related parameters (Length,Offset,Marker). Each handler has function that is required (e.g. AddDirectory,SetEoF for ReadDirectory and GetWriteData for Write..). By doing wrapping this way we are avoiding one memory copy operation compared to the conventional way. This technique uses pin_ptr to access managed memory in native code.

#### Comparision
Using Marshaling
```
Managed DS ->(Marshaling) Native DS -> WinFsp Copy 
```
Using C++/CLI
```
Managed DS ->(pin_ptr copy)  WinFsp Copy 
```

This is how it will look (approx) :-)
```
                                    BufferCopy
WinFsp(C++) +-----> WinFsp(C++/CLI)  +------>  .NET Implementation
                                     ^------+
                                    BufferCopy
```

**Comment by billziss-gh** [comment]
I list here some of the WinFsp design concepts. Unfortunately this list is not complete as I have not had the need to communicate it before. Some of these I may have mentioned in our prior correspondence:

- Design decisions within WinFsp MUST be made to maximize (in this order): stability, file system semantics correctness, performance.
- Major components MUST be accompanied by good tests.
- Programmatic interfaces presented by WinFsp software components SHOULD be consistent.
- WinFsp MUST NOT have any dependencies to external components, except for those that ship with the OS. The minimum Windows OS version supported is Win7. [It is acceptable for a .NET layer to reference the .NET framework included with the OS.]

While I would love to see a .NET layer incorporated into WinFsp, I also want to manage expectations about getting something as big as this accepted. I would love to see a version of it, even if is not currently working. This would help us gauge whether it makes more sense to incorporate it into WinFsp or whether to keep it as a sister project (that would of course be linked from WinFsp).

> I have written .NET wrapper using the C++/CLI. I prefer this way because it allows us to control memory and data structure marshaling with more granularity compared to standard wrapper writing. It also easy to debug memory corruption with C++/CLI.

It is also possible to recompile the WinFsp DLL under C/C++ CLI (it requires a few changes to make sure that the C code compiles as C++). What do you see as the benefits of having an additional wrapper over the DLL? Is it that the interface presented is more .NET-like rather than C-like?

**Comment by yogendersolanki91** [comment]
> It is also possible to recompile the WinFsp DLL under C/C++ CLI (it requires a few changes to make sure that the C code compiles as C++). What do you see as the benefits of having an additional wrapper over the DLL? Is it that the interface presented is more .NET-like rather than C-like?

It is not about language or paradigm. The only issue that comes every time you do something between Windows Kernel and .NET is the memory which managed memory by CLR. Managed memory cannot be used to invoke any native  call. Even if you recompile it with CLI, there will be a point in code where you will do all these buffer copy operation between native to manage and vice-versa. 

> While I would love to see a .NET layer incorporated into WinFsp, I also want to manage expectations about getting something as big as this accepted. I would love to see a version of it, even if is not currently working. This would help us gauge whether it makes more sense to incorporate it into WinFsp or whether to keep it as a sister project (that would of course be linked from WinFsp).

We can do one thing, we can create a separate branch for wrapper and I can push my current code into that branch. You can have a look and give your comment. Code is still buggy. I could not get much time to fix the bug after first prototype implementation for wrapper.

**Comment by billziss-gh** [comment]
> We can do one thing, we can create a separate branch for wrapper and I can push my current code into that branch. You can have a look and give your comment. Code is still buggy. I could not get much time to fix the bug after first prototype implementation for wrapper.

That would be fantastic. I believe you already have a WinFsp fork. Just push your changes into it and then it will available for review.

**Comment by yogendersolanki91** [comment]
I have pushed the code. You can have a look.

**Comment by billziss-gh** [comment]
Thank you.

**Comment by billziss-gh** [comment]
@yogendersolanki91 I should be able to start reviewing this some time later today. I expect that it will take some time to fully review and consider all aspects. Thanks again for the (massive) contribution!

**Comment by yogendersolanki91** [comment]
No problem. Contribution is very small compared to your efforts.

**Comment by yogendersolanki91** [comment]
I think you might have not yet started looking at code. Just to remind you it is very basic prototype level code. So please keep in my while reviewing that It will be changed in terms of approach and coding style after we agree upon design.

**Comment by billziss-gh** [comment]
My apologies you are right :) I got distracted by other things. Will start looking at it right now.

**Comment by billziss-gh** [comment]
Is it possible to open Issues on your fork? I am thinking it might the easiest way for me to make comments.

**Comment by billziss-gh** [comment]
Some initial comments here (it would be preferable if you opened up "Issues" on your fork so that we could track them there).

## Remove .gitattributes and .gitignore files [minor]

These files in the root directory of the fork appear unnecessary. Furthermore they cause various issues with line endings (CRLF vs LF) on files.

Various files (e.g. vcxproj files) appear modified, but upon further examination it is only line endings that have been changed. I suspect that the .gitattributes file and the `* text=auto` line may be responsible.

I will keep updating this as I find more issues.

## Solution does not compile out of the box [minor]

I had to add `..\..\inc` to winfsp.net Properties > C/C++ > Additional Include Directories.

Also the winfsp_msi project should only build for the Installer.Debug and Installer.Release configurations.

## What is the purpose of FileNodeCollection?

What is the purpose of `FileNodeCollection` in `src/dotnet/fileNode.*`? It does not appear to actually be used.

**Comment by yogendersolanki91** [comment]
Thanks for the comment. As I told earlier it is just a rough prototype so sorry for the messed of code. Now you can add issue in fork, I have enabled the option. I will try to add these issue in fork after some time (now going to sleep [IST]) or you can add them now.

**Comment by billziss-gh** [comment]
No worries, @yogendersolanki91. We will get it fixed!

**Comment by billziss-gh** [comment]
I added the comments above as separate issues on your fork.

**Comment by billziss-gh** [comment]
Closing this as there is now a .NET layer for WinFsp. [[link](https://github.com/billziss-gh/winfsp/tree/master/src/dotnet)]
