### ISSUE TITLE
Testing framework

### ISSUE THREAD

**Issue by yogendersolanki91** [billziss-gh/winfsp#72]
Can we test a file system that is implemented using WinFsp. I know there is WinFsp-test which test operations. But I could not find a way to do this with my own file system implementation. There should be a testing framework with option to test all operation with possible parameters.

I am not sure whether we have this or not. So pardon me if i missed something.

**Comment by billziss-gh** [comment]
WinFsp uses multiple test suites; I recommend familiarizing yourself with `tools\run-tests.bat` to see how they are used.

## WinFsp-Tests

The primary WinFsp test suite is `winfsp-tests`. It must be built from source and by default tests an embedded version of MEMFS. It can however be run in an "external" mode against an already mounted file system (e.g. NTFS).

To do so switch to a directory on that file system and run:

    winfsp-tests --external --resilient

The `--external` switch instructs `winfsp-tests` to run NTFS-compatible tests only. It is possible for a file system not to pass all these tests and still be a useful file system. For example, the sample "passthrough" file system does not pass all `--external` tests. I can provide more information on tests that are not necessary to pass and why (usually tests that rename or delete memory mapped files, tests that have to do with allocation size, etc).

The `--resilient` switch instructs `winfsp-tests` to retry some operations that failed. This is unfortunately necessary because of the non-deterministic nature of the Windows file system.

Consider the following example: `winfsp-tests` creates a file and then deletes it with `DeleteFileW` and then checks that `CreateFileW` on it fails with`ERROR_FILE_NOT_FOUND`. It is actually possible for an unrelated process or system component to come in and open the file and keep it open long enough so that `DeleteFileW` succeeds, but the file's directory entry remains. In a case like this the final `CreateFileW` does not fail with `ERROR_FILE_NOT_FOUND`, but `ERROR_ACCESS_DENIED` instead (which derives from the NTOS error code `STATUS_DELETE_PENDING`). This will cause the test to fail, although in reality the file system did its job correctly.

For this reason `winfsp-tests` knows to retry some of the operations when the `--resilient` flag is set. Please keep in mind that I have not caught all cases where operations need to be retried (in particular `MoveFileExW` is not hooked at all although it should be) and that the `--resilient` flag can actually mask real problems with the file system! So use it judiciously.

`WinFsp-tests` is quite powerful and can do other things like check your file system when exported as a share (`--share=`), or in the presence of oplocks (`--oplock=`) or without certain privileges (e.g. `--no-traverse`). I recommend reading `tools\run-tests.bat` to see how some of its capabilities are used.

## Winfstest

A test suite included with the [secfs.test](https://github.com/billziss-gh/secfs.test) collection of test programs. This collection is included as a git submodule in WinFsp under `ext/test`.

`Winfstest` is rather small although it is written in such a way that new tests could very easily be added. The only drawback: it requires Python to run (but can be run under Windows or Cygwin Python).

## FSX

My port of Apple's FSX to Windows. Also found in [secfs.test](https://github.com/billziss-gh/secfs.test). Tests and verifies read/write and memory mapped I/O. Very useful, especially if your file system has complicated read/write logic.

## IfsTest

This is Microsoft's own file system test suite. Consider this one as the "gauntlet" of test suites, if your file system passes this one you are "NTFS" :) Many of the tests are highly esoteric or NTFS specific: for example testing weird rules about how NTFS updates its directory entries or testing defragmentation support.

I do not think most file systems need to pass this one, because most file systems do not need to behave exactly like NTFS in all cases. However the reference file system that ships with WinFsp (MEMFS) passes most tests and for the few ones that it does not, there is always a good reason for it (e.g. not EA support). We would probably have to make sure that .NET MEMFS also passes this test suite eventually (but hopefully it should not be hard if you have followed the C++ MEMFS general structure).

IfsTest comes with the Windows Hardware Certification Kit (HCK) and the Windows Hardware Lab Kit (HLK) although WinFsp/MEMFS is tested regularly against the HCK version.

**Comment by billziss-gh** [comment]
I am closing this as I do not have anything else to add on this subject. Please reopen if I misunderstood your question.
