### ISSUE TITLE
(fuse) legal filename characters

### ISSUE THREAD

**Issue by samkelly** [billziss-gh/winfsp#80]
Do the same restrictions that exist in windows for filenames (e.g. no ":" characters) apply to WinFsp FUSE file systems? My guess is this is enforced at the explorer.exe level as a UI thing, but at lower levels special characters will work as long as the underlying fuse filesystem supports them...

**Comment by billziss-gh** [comment]
The WinFsp-FUSE layer fully supports all POSIX characters. See "Step 3" in this document:

https://github.com/billziss-gh/winfsp/wiki/SSHFS-Port-Case-Study#step-3-mapping-windows-to-posix

OTOH Windows does not support a lot of those characters. So what the FUSE layer does is translate them by placing them into the "Unicode Private Area". For example, if a FUSE file system reports a filename `file*with*stars`, the FUSE layer will translate all `*` chars to `0xFF00 + '*'` (and vice-versa).

This mapping is compatible with Cygwin and Services for UNIX (I believe).

**Comment by samkelly** [comment]
ok that's great! On my end should I be validating file/folder basenames for legal POSIX filename characters?

**Comment by billziss-gh** [comment]
There are no illegal POSIX path characters (except the string terminator`'\0'`). In a POSIX file name the only illegal character is the path separator `'/'` (and `'\0'`). If your file system can handle any POSIX character, you should not need to do any validation.

---

Since your file system is FUSE-based you can get any character in a file path (except `'\0'`). For example, you may get a path such as: `"/file*with*stars"`. This will happen rarely, but it can happen more easily with Cygwin.

```
$ touch '/cygdrive/y/file*with*stars'
```

Cygwin will attempt to create/open a file with name `"\\file\uff2awith\uff2astars"` (`'\uff2a'==0xFF00+'*'`), which will eventually get routed to the WinFsp FSD. The FSD will check if the file name is valid (according to NTFS rules) and it will then forward it to the DLL and the WinFsp-FUSE layer. The FUSE layer will convert it back to `"/file*with*stars"`, because it knows about the "Unicode Private Area" scheme.

So it is perfectly legal to get any character in a FUSE file system. If OTOH your file system needs to store a file with a related file name back on NTFS, you have a problem because NTFS will not like a name like `"file*with*stars"`. There are a few approaches here:

- The WinFsp DLL includes API's that allow you to convert both ways: from `"file*with*stars"` to `"file\uff2awith\uff2astars"` and vice-versa. These may not be easily callable from node.js of course.

- You can attempt to do the mapping yourself, it is actually very easy. Here is the relevant C code: https://github.com/billziss-gh/winfsp/blob/master/src/dll/posix.c#L927-L952

- You can just ignore the problem. NTFS will not let you create/open a file with such a name.

**Comment by samkelly** [comment]
thanks!
