### ISSUE TITLE
Concurrency issue of Open/Close in MemFS

### ISSUE THREAD

**Issue by jggrant** [billziss-gh/winfsp#93]
As discussed in email:

I have seen problems with ref counting a file node in Open/Close operations.

Multiple Open/Close operations can happen near each other during the WinFSP test suite. Because Open is using a shared lock and Close no lock at all, ref count without atomics or locks can be faulty and lead to a double delete in memory, as I have experienced in my test case.

Take the scenario of two Open happening at the same time, which is possible with the read (shared) lock. Both try to increment the ref count, but with no synchronization, it is possible only 1 is added to it instead of 2 (two reads before the first write). Then you eventually get two Close later, but since only one of them was properly ref counted, the first one may delete the node, and the second one access invalid memory causing corruption or crash.

**Comment by fsgeek** [comment]
In the past, the technique I have used here is to utilize an atomic increment/decrement and a reader-writer lock. 

To increment you hold the reader lock and increment. To decrement, you also hold the reader lock, but to delete you must hold the writer lock. Thus, in close you read lock, decrement. If the decrement would trigger deletion you increment and drop the shared lock. Then you acquire the lock exclusive, decrement and if still zero, delete. Then release the exclusive lock. 

This technique yields excellent concurrent behavior while avoiding the ABA lookup/refcount race.

Thus the reader/writer lock is protecting the lookup mechanism (presumably a key/value store) and the atomic value manages the ref count on the object itself.

**Comment by billziss-gh** [comment]
@jggrant as discussed over private email:

Your analysis is correct. Because there is no lock around `Close`, ref counting should be done using “interlocked” operations, but is not. This is a bug in MEMFS.

I am not sure how this came to be. I note that I have an item in my internal TODO list reading "memfs: Close does unsynchronized dereference". I do not recall when this TODO was added or why it was not acted upon. I do recall that originally MEMFS was using the “coarse strategy” (i.e. exclusive lock over all operations), but then I slowly started relaxing the locks for it (and clearly I missed this case).

I believe that changing the [increment operation](https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L263) to use `InterlockedIncrement` and the [decrement operation](https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L269) to use `InterlockedDecrement` should be enough to fix this problem. Please let me know if you disagree or if I misunderstand the problem.

@fsgeek wrote:

> To increment you hold the reader lock and increment. To decrement, you also hold the reader lock, but to delete you must hold the writer lock. Thus, in close you read lock, decrement. If the decrement would trigger deletion you increment and drop the shared lock. Then you acquire the lock exclusive, decrement and if still zero, delete. Then release the exclusive lock.
>
> This technique yields excellent concurrent behavior while avoiding the ABA lookup/refcount race.
>
> Thus the reader/writer lock is protecting the lookup mechanism (presumably a key/value store) and the atomic value manages the ref count on the object itself.

I believe that in the MEMFS case things may be a bit simpler. MEMFS maintains an in-memory map for `FileName -> FileNode` associations that is protected by a read-write lock as you described. There is also a refcount for each `FileNode` which maintains the number of references to the file.

The read-write lock is taken exclusive whenever the file map is updated (e.g. `Create, Cleanup/Delete, Rename`). It is taken shared whenever the file map is read-accessed (e.g. `Open`). [It is not taken at all for operations that do not affect/access the file system namespace.]

The refcount is updated every time a file is entered into the file map (`Create`) or removed from the file map (`Cleanup/Delete`). [There is also `Rename`]. It is also updated when opening or closing a file. Because a `Cleanup/Delete` will always happen before `Close`, the file will have always be removed from the file map **(i.e. there will be no directory entry for it)** by the time the final `Close` after a `Cleanup/Delete` arrives (the one that makes `refcount==0` and triggers C++ `delete` of the `FileNode`).

This analysis is specific to MEMFS.

> Thus, in close you read lock, decrement. If the decrement would **trigger deletion** you increment and drop the shared lock. Then you acquire the lock exclusive, decrement and if still zero, delete. Then release the exclusive lock.

Interesting. What would be the reason that a file system would not update its directory entries until `Close` time (I am assuming that is what you mean by "trigger deletion")? Is it because of a file system specific design or to properly support the Windows file system in a specific scenario?

----

I need to do a better job documenting the WinFsp locking guarantees. A couple of concepts:

- A namespace lock is a read-write lock that is used when managing the file system namespace. For example, such locks are used during `Create`, `Rename`, etc. There is a specific number of such locks per file system namespace and they serve different purposes.

- A file lock is a read-write lock that is used when doing file I/O. For example such locks are taken exclusive when the file is being modified and shared when accessed (but not modified).

In WinFsp the primary components are the kernel-mode FSD and the user-mode DLL. They take locks as follows:

- The FSD maintains a number of namespace locks. These should be considered an implementation detail and user mode file systems should not rely on them.
- The FSD maintains a read-write lock per file. This read-write lock is taken exclusive when the file is being modified (e.g. `Write`, `SetBasicInfo`, etc.) and shared when the file is being read/accessed (e.g. `Read`, `GetFileInfo`, etc.) File systems can rely on them. For example, MEMFS does so for its `Read` / `Write` operations.
- The DLL maintains a read-write lock that acts as a namespace lock in “fine” mode and an exclusive lock in “coarse” mode.
- The DLL does not take any file locks.

**Comment by billziss-gh** [comment]
An additional complication is that `Overwrite` also [touches](https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L859) `RefCount`.

The semantics of the `Overwrite` operation require unopened named streams to be deleted upon overwriting. MEMFS accomplishes this with this [code](https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L852-L862).

[Opened named streams are supposed to be marked for delete at `Cleanup` time; this is accomplished by the [FSD](https://github.com/billziss-gh/winfsp/blob/v1.0/src/sys/file.c#L1018).]

I need to think how to cleanly implement this without race conditions.

**Comment by billziss-gh** [comment]
Commit 98a329e81bc12c7653e9a42740e2e63147d80710 fixes this issue.

This currently fails on AppVeyor but this appears to be related to this AppVeyor issue: AppVeyor/ci#1579

**Comment by fsgeek** [comment]
>
> Interesting. What would be the reason that a file system would not update
> its directory entries until Close time (I am assuming that is what you
> mean by "trigger deletion")? Is it because of a file system specific design
> or to properly support the Windows file system in a specific scenario?


In fact, these were just the in-memory data structures.  The given file (or
directory) might have been deleted on disk previously, or this might just
be a final release of the object.  One of the complications here was that
we did in fact do deferred teardown of objects, so the reference count
might drop to zero with little direct bearing upon the application(s) using
the given file.

Hence, the race between "thread opening file" and "deferred teardown thread
finally doing its housekeeping".

Of course Windows semantics (memory mapped files, forced dismount, device
removal) do make much of this complex, which is why the ref counting was so
important.  We had a rather elaborate reason-based reference count scheme -
so when you took out a reference, you specified a reason, which
corresponded with a bucket, and when you released it you specified the
matching reason.  This made it easier to find reference count leaks.


On Wed, Jun 7, 2017 at 5:40 PM, Bill Zissimopoulos <notifications@github.com
> wrote:

> @jggrant <https://github.com/jggrant> as discussed over private email:
>
> Your analysis is correct. Because there is no lock around Close, ref
> counting should be done using “interlocked” operations, but is not. This is
> a bug in MEMFS.
>
> I am not sure how this came to be. I note that I have an item in my
> internal TODO list reading "memfs: Close does unsynchronized dereference".
> I do not recall when this TODO was added or why it was not acted upon. I do
> recall that originally MEMFS was using the “coarse strategy” (i.e.
> exclusive lock over all operations), but then I slowly started relaxing the
> locks for it (and clearly I missed this case).
>
> I believe that changing the increment operation
> <https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L263>
> to use InterlockedIncrement and the decrement operation
> <https://github.com/billziss-gh/winfsp/blob/v1.0/tst/memfs/memfs.cpp#L269>
> to use InterlockedDecrement should be enough to fix this problem. Please
> let me know if you disagree or if I misunderstand the problem.
>

**Comment by billziss-gh** [comment]
@fsgeek thanks for your explanation, this makes sense, especially since I have now discovered I do something similar in the WinFsp FSD.

**Comment by billziss-gh** [comment]
@jggrant I have been unable to fully test this, because of the blocking AppVeyor issue linked earlier. The tests that currently fail are those that test MEMFS when it is exposed as a network share (`NetShareAdd`).

Since all other tests pass I am fairly confident that the fix is a valid one and have merged into the `release/1.1` branch and will be closing this issue soon.

**Comment by billziss-gh** [comment]
All tests now pass after the latest AppVeyor update. Closing this.
