### ISSUE TITLE
Write not called on empty file and other questions

### ISSUE THREAD

**Issue by FrKaram** [billziss-gh/winfsp#95]
Hi Bill,

I encounter a behaviour I do not understand while building my .NET file system.
I've implemented all the methods and so far I can do pretty much anything :-)
Except when I want to update a .txt file that is a 0 byte file in the repository.
I open the file in notepad, I see the "Open", "SetFileSize" and "Cleanup" calls but "Write" is never called.
When I do the same thing with a .txt file already containing data, the "write" method is called.

Any idea of what I do wrong ?

Moreover, now that I have a slightly better understanding of how all this is working, I have additionnal questions :

- When browsing the repository, I see multiple almost simultaneous "Open" calls for the same files/folders (having the same CreateOptions/GrantedAccess). Can I safely cache the first call for few seconds and reply from cache to next ones instead that making request to repository ?

- How do I decode the meaning of CreateOptions and GrantedAccess in open calls. I found info here https://msdn.microsoft.com/en-us/library/bb432380(v=vs.85).aspx but is there somewhere the enums that would allow me to have the meaning of those parameters ?

- Were can I find information about the return values that are accepted by Windows for each method ?

- When writing a file, the calls are usually Open -> SetFileSize -> Write -> Cleanup on the same FileNode 
object. I notice that, in the meantime, there are also other "Open" for the same file. Those Opens are creating other FileNodes which are not aware that the FileSize is being updated on a parallel thread. Is that a problem ? Should I submit the FileSize change to the repository ASAP before writing the actual content.

I hope that my questions make sense to you :-)

Thanks for your support !

**Comment by FrKaram** [comment]
I close the issue myself 
I since add a revelation on an aspect of WinFSP behaviour which I totally missed previously and my question are not relevant anymore ...

**Comment by billziss-gh** [comment]
> I since add a revelation on an aspect of WinFSP behaviour which I totally missed previously and my question are not relevant anymore ...

I am glad that your question got resolved. Nevertheless I add some comments on some of your questions in the hope that they are of help:

> When browsing the repository, I see multiple almost simultaneous "Open" calls for the same files/folders (having the same CreateOptions/GrantedAccess). Can I safely cache the first call for few seconds and reply from cache to next ones instead that making request to repository ?

Your file system can do its own caching and respond from cache to `Open` requests.

WinFsp also supports metadata and data caching. In the .NET layer this is controlled by the [`FileSystemHost.FileInfoTimeout`](https://github.com/billziss-gh/winfsp/blob/v1.1/src/dotnet/FileSystemHost.cs#L116-L123) property.

A value of `FileInfoTimeout` of `1000` will cache file metadata in the kernel for 1000 ms (milliseconds). A value of `FileInfoTimeout` of `(UInt32)-1` will cache metadata and data indefinitely (or until system memory pressure dictates otherwise).

> How do I decode the meaning of CreateOptions and GrantedAccess in open calls. I found info here https://msdn.microsoft.com/en-us/library/bb432380(v=vs.85).aspx but is there somewhere the enums that would allow me to have the meaning of those parameters ?

The [`NtCreateFile`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364399(v=vs.85).aspx) documentation is the appropriate place to learn about these parameters. There is also [File Security and Access Rights](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364399(v=vs.85).aspx) for some additional information.

In general though you can ignore the `GrantedAccess` parameter as all access checks have been performed by the time you receive the `Open` call. The `CreateOptions` parameter contains the `FILE_DIRECTORY_FILE` flag that is significant during `Create` calls as it instructs you to create a directory instead of a file. Most other `CreateOptions` bits can be ignored.

I have some additional information on these parameters in the C API documentation: [link](http://www.secfs.net/winfsp/apiref/)

> Were can I find information about the return values that are accepted by Windows for each method ?

You can return any status code from a file system operation. However a properly functioning file system will return specific status codes for specific error conditions.

There is no good documentation on this. The memfs and memfs.dotnet samples are probably your best bets here as I have tried very hard to return the correct status codes through extensive testing.

> When writing a file, the calls are usually Open -> SetFileSize -> Write -> Cleanup on the same FileNode
object. I notice that, in the meantime, there are also other "Open" for the same file. Those Opens are creating other FileNodes which are not aware that the FileSize is being updated on a parallel thread. Is that a problem ? Should I submit the FileSize change to the repository ASAP before writing the actual content.

In general, yes. You should not expect that a `SetFileSize` will always be followed by `Write`.

If you are worried about performing a potentially expensive file allocation operation that is going to be overwritten by a following `Write` I recommend implementing some form of the `ValidDataLength` optimization. In this optimization every file in your file system has a `FileSize`, but also a `ValidDataLength`. It will always be `ValidDataLength <= FileSize` and reads past the `ValidDataLength` return zeroes.

On `SetFileSize` you only update `FileSize` but not `ValidDataLength` (unless the new `FileSize` is less than the `ValidDataLength`). On `Write` you update `FileSize` and `ValidDataLength`.

**Comment by FrKaram** [comment]
Thanks a lot for those additionnal comments, this is quite usefull.
I solved all my problems by caching the FileNodes as long as there are open handles on them. So all the "Open" read from the cache instead than repository.
I've just implented that and the performance increase is impressive.
My file system even handle all the crazy operations Excel do when saving the files 😀

**Comment by billziss-gh** [comment]
@FrKaram fantastic :)
